'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; };

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

var _reactDocgen = require('react-docgen');

var _terraMarkdown = require('terra-markdown');

var _terraMarkdown2 = _interopRequireDefault(_terraMarkdown);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _objectWithoutProperties(obj, keys) { var target = {}; for (var i in obj) { if (keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; } /* eslint-disable import/no-extraneous-dependencies */


var propTypes = {
  src: _react.PropTypes.string.isRequired
};

/**
 * Renders a table view for the props metadata of a react component generated by react-docgen
 */
var PropsTable = function PropsTable(_ref) {
  var src = _ref.src,
      customProps = _objectWithoutProperties(_ref, ['src']);

  /**
   * Runs component source code through react-docgen
   * @type {Object}
   */
  var componentMetaData = (0, _reactDocgen.parse)(src);

  /**
   * Alias for props object from componentMetaData
   * @type {Object}
   */
  var componentProps = componentMetaData.props;

  return _react2.default.createElement(
    'div',
    { dir: 'ltr', className: 'markdown-body' },
    _react2.default.createElement(
      'h2',
      null,
      'Props'
    ),
    _react2.default.createElement(
      'table',
      customProps,
      _react2.default.createElement(
        'thead',
        null,
        _react2.default.createElement(
          'tr',
          null,
          _react2.default.createElement(
            'th',
            null,
            'Prop Name'
          ),
          _react2.default.createElement(
            'th',
            null,
            'Type'
          ),
          _react2.default.createElement(
            'th',
            null,
            'Is Required'
          ),
          _react2.default.createElement(
            'th',
            null,
            'Default Value'
          ),
          _react2.default.createElement(
            'th',
            null,
            'Description'
          )
        )
      ),
      _react2.default.createElement(
        'tbody',
        null,
        Object.keys(componentProps).map(function (key) {
          var prop = componentProps[key];
          var type = prop.type.name;

          // Pull the first value off and use that as type.
          // This assumes all enumerable values are the same type.
          if (type === 'enum') {
            type = _typeof(prop.type.value[0].value);
          }

          return _react2.default.createElement(
            'tr',
            { key: key, style: { fontSize: '90%' } },
            _react2.default.createElement(
              'td',
              { style: { fontWeight: 'bold' } },
              key
            ),
            _react2.default.createElement(
              'td',
              null,
              prop.type ? type : ''
            ),
            prop.required ? _react2.default.createElement(
              'td',
              { style: { color: '#d53700' } },
              'required'
            ) : _react2.default.createElement(
              'td',
              { style: { color: '#444' } },
              'optional'
            ),
            prop.defaultValue ? _react2.default.createElement(
              'td',
              { style: { fontWeight: 'bold' } },
              prop.defaultValue.value
            ) : _react2.default.createElement(
              'td',
              { style: { color: '#444' } },
              'none'
            ),
            _react2.default.createElement(
              'td',
              null,
              _react2.default.createElement(_terraMarkdown2.default, { src: prop.description })
            )
          );
        })
      )
    )
  );
};

PropsTable.propTypes = propTypes;

exports.default = PropsTable;