#  "eslintConfig": {
#    "extends": "@cerner/terra",
#    "globals": {
#      "enzyme":"readonly",
#      "enzymeIntl":"readonly"
#    }
#  },

extends: "@cerner/terra"
globals:
  enzyme: readonly
  enzymeIntl: readonly
