'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _fs = require('fs');

var _fs2 = _interopRequireDefault(_fs);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var outputfile = _fs2.default.createWriteStream('../../packages/terra-site/src/examples/icon/IconAll.jsx', { flags: 'w' });

var generateIconAll = function generateIconAll(iconObjs) {
  return new Promise(function (resolve) {
    outputfile.write('// This file is autogenerated from scripts/src/generate-example\n');
    outputfile.write('/* eslint-disable import/no-duplicates */\n');
    outputfile.write('import React from \'react\';\n');

    iconObjs.forEach(function (iconObj) {
      outputfile.write(iconObj.syntaxImport);
    });
    outputfile.write('/* eslint-enable import/no-duplicates */\n');

    outputfile.write('const IconAll = () => (\n');
    outputfile.write('  <div>\n');
    iconObjs.forEach(function (iconObj) {
      outputfile.write('    <div>\n');
      outputfile.write('      ' + iconObj.syntaxComponent + '\n');
      outputfile.write('      ' + iconObj.name + '\n');
      outputfile.write('    </div>\n');
    });
    outputfile.write('  </div>\n');
    outputfile.write(');\n\n');

    outputfile.write('export default IconAll;\n');

    resolve(iconObjs);
  });
};

exports.default = generateIconAll;