'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _fs = require('fs');

var _fs2 = _interopRequireDefault(_fs);

var _config = require('../config');

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

// import React from 'react';
// import { IconAdd } from '../src/Icon.jsx';
// import { IconAbnormal} from '../src/Icon.jsx';

// const IconAll = () => (
//   <div>
//     <IconAdd />
//     <IconAbnormal />
//   </div>
// );

// export default IconAll;

var outputfile = _fs2.default.createWriteStream('./examples/IconAll.jsx', { flags: 'w' });

var generateIconAll = function generateIconAll(iconObjs) {
  return new Promise(function (resolve, reject) {

    outputfile.write('// This file is autogenerated from scripts/src/generate-example \n');
    outputfile.write('import React from \'react\';\n');

    iconObjs.forEach(function (iconObj) {
      outputfile.write(iconObj.syntaxImport);
    });

    outputfile.write('const IconAll = () => (\n');
    outputfile.write('<div>\n');
    iconObjs.forEach(function (iconObj) {
      outputfile.write('  <div>\n');
      outputfile.write('    <div>\n');
      outputfile.write('      ' + iconObj.syntaxComponent + '\n');
      outputfile.write('      ' + iconObj.name + '\n');
      outputfile.write('    </div>\n');
      outputfile.write('  </div>\n');
    });
    outputfile.write('</div>\n');
    outputfile.write(');\n\n');

    outputfile.write('export default IconAll;');

    resolve(iconObjs);
  });
};

exports.default = generateIconAll;