// This file is autogenerated from scripts/src/generate-example
import React from 'react';
import classNames from 'classnames/bind';
import IconAlert from '../../../icon/IconAlert';
import styles from './IconHeightWidth.module.scss';

const cx = classNames.bind(styles);

const IconHeightWidth = () => (
  <div>
    <h3>Default</h3>
    <IconAlert />
    <h3>Height and Width are 50px</h3>
    <IconAlert id="icon-height-50-width-50" height="50" width="50" />
    <h3>Height and Width are 5em</h3>
    <IconAlert id="icon-height-5em-width-5em" height="5em" width="5em" />
    <h3>Container font size is 5em</h3>
    <div className={cx('icon-wrapper')}>
      <IconAlert />
    </div>
    <h3>Height of 5em</h3>
    <IconAlert id="icon-height-5em" height="5em" />
    <h3>Width of 5em</h3>
    <IconAlert id="icon-width-5em" width="5em" />
  </div>
);

export default IconHeightWidth;
