// This file is autogenerated from scripts/src/generate-example
/* eslint-disable */
import React from "react";
import IconMediaPlay from 'terra-icon/lib/icon/IconMediaPlay';
import IconMediaFastForward from 'terra-icon/lib/icon/IconMediaFastForward';
import IconMediaRewind from 'terra-icon/lib/icon/IconMediaRewind';
import {width, height} from './common';
import Card from 'terra-card';

const A11yMeaningfulInteractive = () => (
  <Card>
    <Card.Body>
      <div>Playback Controls</div>
      <div>
        <a href="#">
          <IconMediaRewind a11yLabel="Rewind" width={width} height={height} />
        </a>
        <a href="#">
          <IconMediaPlay a11yLabel="Play" width={width} height={height} />
        </a>
        <a href="#">
          <IconMediaFastForward a11yLabel="Fast Forward" width={width} height={height} />
        </a>
      </div>
    </Card.Body>
  </Card> 

);

export default A11yMeaningfulInteractive;
