// This file is autogenerated from scripts/src/generate-example
import React from 'react';
import Star from 'terra-icon/lib/icon/IconFeaturedOutlineYellow';
import DecorativeEmptyStar from 'terra-icon/lib/icon/IconFeaturedOutline';
import Card from 'terra-card';
import { width, height } from './common';

const InformativeStar = (<Star a11yLabel="Four out of five stars" width={width} height={height} />);
const DecorativeStar = (<Star width={width} height={height} />);
const A11yGroupReadOnly = () => (
  <Card>
    <Card.Body>
      Rating:&nbsp;
      {InformativeStar}
      {DecorativeStar}
      {DecorativeStar}
      <DecorativeEmptyStar width={width} height={height} />
    </Card.Body>
  </Card>
);

export default A11yGroupReadOnly;
