// This file is autogenerated from scripts/src/generate-example
/* eslint-disable */
import React from "react";
import IconAnnouncement from "terra-icon/lib/icon/IconAnnouncement";

const A11yMeaningful = () => (
  <p>
    <IconAnnouncement a11yLabel="Announcement" /> Facilities will be closed
    tomorrow.
  </p>
);

export default A11yMeaningful;
