// This file is autogenerated from scripts/src/generate-example
/* eslint-disable */
import React from "react";
import DecorativeIconAnnouncement from "terra-icon/lib/icon/decorative/IconAnnouncement";

const A11yDecorative = () => (
  <p>
    <DecorativeIconAnnouncement /> Announcement: Facilities will be closed tomorrow.
  </p>
);

export default A11yDecorative;
