// This file is autogenerated from scripts/src/generate-example
/* eslint-disable */
import React from "react";
import DecorativeStar from "terra-icon/lib/icon/decorative/IconFeaturedOutlineYellow";
import Star from "terra-icon/lib/icon/IconFeaturedOutlineYellow";
import DecorativeEmptyStar from "terra-icon/lib/icon/decorative/IconFeaturedOutline";

const A11yGroupReadOnly = () => (
  <p>
    Rating:&nbsp;
    <Star a11yLabel="Four out of five stars" />
    <DecorativeStar />
    <DecorativeStar />
    <DecorativeStar />
    <DecorativeEmptyStar />
  </p>
);

export default A11yGroupReadOnly;
