// This file is autogenerated from scripts/src/generate-example
/* eslint-disable */
import React from 'react';
import {
IconAdd, 
IconAddPerson, 
IconAllergy, 
IconAnalytics, 
IconAnnouncement, 
IconArchive, 
IconAttachment, 
IconAudio, 
IconAutoText, 
IconAway, 
IconBedRequested, 
IconBluetooth, 
IconBluetoothSlash, 
IconBookmark, 
IconBriefcase, 
IconBrokenImage, 
IconBrokenLinkUnlink, 
IconBusy, 
IconCalculator, 
IconCalendar, 
IconCamera, 
IconCancel, 
IconCaretDown, 
IconCaretLeft, 
IconCaretRight, 
IconCaretUp, 
IconCatalogueNumber, 
IconCaution, 
IconChecklist, 
IconCheckmark, 
IconChevron, 
IconChevronDown, 
IconChevronLeft, 
IconChevronRight, 
IconChevronUp, 
IconCircleLinesSymbol, 
IconCircleSymbol, 
IconCircleSymbolLight, 
IconClear, 
IconClipboard, 
IconClock, 
IconClose, 
IconCollapseRow, 
IconComment, 
IconCommit, 
IconCompose, 
IconConfidential, 
IconConsultInstructionsForUse, 
IconDateOfManufacture, 
IconDevice, 
IconDiamondSymbol, 
IconDiamondSymbolLight, 
IconDocumentPlus, 
IconDocuments, 
IconDoorOpen, 
IconDoubleChevronLeft, 
IconDoubleChevronRight, 
IconDown, 
IconDownload, 
IconDue, 
IconEcRep,
IconEdit, 
IconEllipses, 
IconEnvelope, 
IconEnvelopeFill, 
IconExclamation, 
IconExpandLess, 
IconExpandMore, 
IconExpandRow, 
IconExtensions, 
IconExternalLink, 
IconFeatured, 
IconFeaturedOff, 
IconFeaturedOutline, 
IconFirst, 
IconFitHeight, 
IconFitScale, 
IconFitWidth, 
IconFlag, 
IconFlipHorizontal, 
IconFlipVertical, 
IconFlowsheet, 
IconFolder, 
IconForward, 
IconFunnel, 
IconGapChecking, 
IconGlasses, 
IconGroup, 
IconHalfRating, 
IconHelpThemeable, 
IconHold, 
IconHospital, 
IconHouse, 
IconIPass, 
IconImage, 
IconImplant, 
IconIncomingCall, 
IconIncomplete, 
IconInformationThemeable, 
IconItalicI, 
IconKeyboard, 
IconKnurling, 
IconLast, 
IconLeft, 
IconLeftPane, 
IconLightbulb, 
IconLink, 
IconList, 
IconLocationPin, 
IconLookback, 
IconManufacturer, 
IconMaximize, 
IconMediaFastForward, 
IconMediaPause, 
IconMediaPlay, 
IconMediaRecord, 
IconMediaRewind, 
IconMediaStop, 
IconMedicationTablet, 
IconMedicationTabletHalf, 
IconMedicationTabletHalfOutline, 
IconMedicationTabletOutline, 
IconMenu, 
IconMerge, 
IconMicrophone, 
IconMicrophoneDisabled, 
IconMinimize, 
IconMinus, 
IconMissedCall, 
IconModified, 
IconMultipleResultsCritical, 
IconMultipleResultsNormal, 
IconMultipleResultsNotNormal, 
IconNavStackUp, 
IconNext, 
IconNoResults, 
IconNoSignal, 
IconNotMet, 
IconNotification, 
IconNotificationDisabled, 
IconNotificationOff, 
IconOutgoingCall, 
IconPadlock, 
IconPager, 
IconPanelLeft, 
IconPanelRight, 
IconPaperFolded, 
IconPaperPencil, 
IconPartiallyMet, 
IconPatientSearch, 
IconPending, 
IconPerson, 
IconPersonConnection, 
IconPersonDoor, 
IconPersonHospital, 
IconPersonnelPerson, 
IconPharmacyReview, 
IconPharmacyVerification, 
IconPhone, 
IconPhoneDown, 
IconPill, 
IconPinDiagonal, 
IconPinDown, 
IconPlusSymbol, 
IconPlusSymbolLight, 
IconPrevious, 
IconPrinter, 
IconProjects, 
IconProtocol, 
IconProvider, 
IconQuestion, 
IconQuestionOutline, 
IconRectangleSymbol, 
IconRectangleSymbolLight, 
IconRecurringEvent, 
IconRedo, 
IconRefresh, 
IconRefusedSlot, 
IconReply, 
IconReplyAll, 
IconRequired, 
IconRight, 
IconRotateLeft, 
IconRotateRight, 
IconSave, 
IconScratchPad, 
IconSearch, 
IconSecondaryProvider, 
IconSend, 
IconSeparate, 
IconSettings, 
IconSharedSchedules, 
IconSimulation, 
IconSortAscending, 
IconSortDescending, 
IconSpinner, 
IconSquareSymbol, 
IconSquareSymbolLight, 
IconStartPresenting, 
IconStopPresenting, 
IconSwap, 
IconTable, 
IconTag, 
IconTeardropSymbol, 
IconTeardropSymbolLight, 
IconTeardropUpSymbol, 
IconTeardropUpSymbolLight, 
IconThinDiamondSymbol, 
IconThinDiamondSymbolLight, 
IconTile, 
IconTrash, 
IconTreemap, 
IconTrendingDown, 
IconTrendingUp, 
IconTriangleDownSymbol, 
IconTriangleDownSymbolLight, 
IconTriangleSymbol, 
IconTriangleSymbolLight, 
IconTrophy, 
IconUnavailable, 
IconUndo, 
IconUnknown, 
IconUnlock, 
IconUnread, 
IconUp, 
IconUpload, 
IconUsers, 
IconVideoCamera, 
IconVideoCameraDisabled, 
IconVisualization, 
IconVolumeSetDecrease, 
IconVolumeSetDefault, 
IconVolumeSetIncrease, 
IconVolumeSetMute, 
IconWaveform, 
IconWifi, 
IconWifiSlash, 
IconXSymbol, 
IconXSymbolLight, 
IconZoomIn, 
IconZoomOut, 
} from 'terra-icon';

// IconCeMarking is a private icon for internal use
import IconCeMarking from 'terra-icon/lib/icon/IconCeMarking';

const cellStyle = { padding: '0.5rem' };
const IconAll = () => (
  <div>  <table>
    <thead>
    <tr>
      <th style={cellStyle} key={'svg'}>SVG</th>
      <th style={cellStyle} key={'concept'}>Concept</th>
      <th style={cellStyle} key={'code'}>Code</th>
    </tr>
    </thead>
    <tbody>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconAdd height='2em' width='2em' /></td>
        <td style={cellStyle}>add</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconAdd } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSearch height='2em' width='2em' /></td>
        <td style={cellStyle}>search</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSearch } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCommit height='2em' width='2em' /></td>
        <td style={cellStyle}>commit</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCommit } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCheckmark height='2em' width='2em' /></td>
        <td style={cellStyle}>checkmark</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCheckmark } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTrash height='2em' width='2em' /></td>
        <td style={cellStyle}>trash</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTrash } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPaperFolded height='2em' width='2em' /></td>
        <td style={cellStyle}>paperFolded</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPaperFolded } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPrinter height='2em' width='2em' /></td>
        <td style={cellStyle}>printer</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPrinter } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconComment height='2em' width='2em' /></td>
        <td style={cellStyle}>comment</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconComment } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconBookmark height='2em' width='2em' /></td>
        <td style={cellStyle}>bookmark</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconBookmark } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconModified height='2em' width='2em' /></td>
        <td style={cellStyle}>modified</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconModified } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconFirst height='2em' width='2em' /></td>
        <td style={cellStyle}>first</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconFirst } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconFolder height='2em' width='2em' /></td>
        <td style={cellStyle}>folder</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconFolder } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconAttachment height='2em' width='2em' /></td>
        <td style={cellStyle}>attachment</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconAttachment } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSend height='2em' width='2em' /></td>
        <td style={cellStyle}>send</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSend } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPill height='2em' width='2em' /></td>
        <td style={cellStyle}>pill</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPill } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconRedo height='2em' width='2em' /></td>
        <td style={cellStyle}>redo</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconRedo } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconVisualization height='2em' width='2em' /></td>
        <td style={cellStyle}>visualization</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconVisualization } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconLightbulb height='2em' width='2em' /></td>
        <td style={cellStyle}>lightbulb</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconLightbulb } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconForward height='2em' width='2em' /></td>
        <td style={cellStyle}>forward</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconForward } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconProjects height='2em' width='2em' /></td>
        <td style={cellStyle}>projects</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconProjects } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconReplyAll height='2em' width='2em' /></td>
        <td style={cellStyle}>replyAll</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconReplyAll } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconFlag height='2em' width='2em' /></td>
        <td style={cellStyle}>flag</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconFlag } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCalculator height='2em' width='2em' /></td>
        <td style={cellStyle}>calculator</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCalculator } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCaretRight height='2em' width='2em' /></td>
        <td style={cellStyle}>caretRight</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCaretRight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCaretLeft height='2em' width='2em' /></td>
        <td style={cellStyle}>caretLeft</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCaretLeft } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCaretUp height='2em' width='2em' /></td>
        <td style={cellStyle}>caretUp</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCaretUp } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCaretDown height='2em' width='2em' /></td>
        <td style={cellStyle}>caretDown</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCaretDown } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTrophy height='2em' width='2em' /></td>
        <td style={cellStyle}>trophy</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTrophy } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconChevronLeft height='2em' width='2em' /></td>
        <td style={cellStyle}>chevronLeft</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconChevronLeft } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPrevious height='2em' width='2em' /></td>
        <td style={cellStyle}>previous</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPrevious } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconChevronRight height='2em' width='2em' /></td>
        <td style={cellStyle}>chevronRight</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconChevronRight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconNext height='2em' width='2em' /></td>
        <td style={cellStyle}>next</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconNext } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconChevronUp height='2em' width='2em' /></td>
        <td style={cellStyle}>chevronUp</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconChevronUp } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconExpandLess height='2em' width='2em' /></td>
        <td style={cellStyle}>expandLess</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconExpandLess } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconChevron height='2em' width='2em' /></td>
        <td style={cellStyle}>chevron</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconChevron } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconChevronDown height='2em' width='2em' /></td>
        <td style={cellStyle}>chevronDown</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconChevronDown } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconExpandMore height='2em' width='2em' /></td>
        <td style={cellStyle}>expandMore</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconExpandMore } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconClock height='2em' width='2em' /></td>
        <td style={cellStyle}>clock</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconClock } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconAway height='2em' width='2em' /></td>
        <td style={cellStyle}>away</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconAway } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSortAscending height='2em' width='2em' /></td>
        <td style={cellStyle}>sortAscending</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSortAscending } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSortDescending height='2em' width='2em' /></td>
        <td style={cellStyle}>sortDescending</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSortDescending } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTreemap height='2em' width='2em' /></td>
        <td style={cellStyle}>treemap</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTreemap } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconGlasses height='2em' width='2em' /></td>
        <td style={cellStyle}>glasses</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconGlasses } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconImage height='2em' width='2em' /></td>
        <td style={cellStyle}>image</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconImage } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDoorOpen height='2em' width='2em' /></td>
        <td style={cellStyle}>doorOpen</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDoorOpen } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconEllipses height='2em' width='2em' /></td>
        <td style={cellStyle}>ellipses</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconEllipses } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconExclamation height='2em' width='2em' /></td>
        <td style={cellStyle}>exclamation</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconExclamation } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconItalicI height='2em' width='2em' /></td>
        <td style={cellStyle}>italic-i</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconItalicI } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconInformationThemeable height='2em' width='2em' /></td>
        <td style={cellStyle}>information_themeable</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconInformationThemeable } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMinus height='2em' width='2em' /></td>
        <td style={cellStyle}>minus</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMinus } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconClose height='2em' width='2em' /></td>
        <td style={cellStyle}>close</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconClose } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconClear height='2em' width='2em' /></td>
        <td style={cellStyle}>clear</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconClear } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconIncomplete height='2em' width='2em' /></td>
        <td style={cellStyle}>incomplete</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconIncomplete } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconNotMet height='2em' width='2em' /></td>
        <td style={cellStyle}>notMet</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconNotMet } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPerson height='2em' width='2em' /></td>
        <td style={cellStyle}>person</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPerson } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconLeft height='2em' width='2em' /></td>
        <td style={cellStyle}>left</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconLeft } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconRight height='2em' width='2em' /></td>
        <td style={cellStyle}>right</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconRight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconUp height='2em' width='2em' /></td>
        <td style={cellStyle}>up</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconUp } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDown height='2em' width='2em' /></td>
        <td style={cellStyle}>down</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDown } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSettings height='2em' width='2em' /></td>
        <td style={cellStyle}>settings</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSettings } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconEdit height='2em' width='2em' /></td>
        <td style={cellStyle}>edit</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconEdit } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCalendar height='2em' width='2em' /></td>
        <td style={cellStyle}>calendar</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCalendar } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconLookback height='2em' width='2em' /></td>
        <td style={cellStyle}>lookback</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconLookback } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconRefresh height='2em' width='2em' /></td>
        <td style={cellStyle}>refresh</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconRefresh } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconProvider height='2em' width='2em' /></td>
        <td style={cellStyle}>provider</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconProvider } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPadlock height='2em' width='2em' /></td>
        <td style={cellStyle}>padlock</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPadlock } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconFeatured height='2em' width='2em' /></td>
        <td style={cellStyle}>featured</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconFeatured } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconFeaturedOff height='2em' width='2em' /></td>
        <td style={cellStyle}>featuredOff</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconFeaturedOff } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconFeaturedOutline height='2em' width='2em' /></td>
        <td style={cellStyle}>featuredOutline</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconFeaturedOutline } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHalfRating height='2em' width='2em' /></td>
        <td style={cellStyle}>halfRating</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconHalfRating } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconArchive height='2em' width='2em' /></td>
        <td style={cellStyle}>archive</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconArchive } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconFunnel height='2em' width='2em' /></td>
        <td style={cellStyle}>funnel</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconFunnel } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDocuments height='2em' width='2em' /></td>
        <td style={cellStyle}>documents</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDocuments } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconQuestion height='2em' width='2em' /></td>
        <td style={cellStyle}>question</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconQuestion } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHelpThemeable height='2em' width='2em' /></td>
        <td style={cellStyle}>help_themeable</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconHelpThemeable } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconUnknown height='2em' width='2em' /></td>
        <td style={cellStyle}>unknown</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconUnknown } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconQuestionOutline height='2em' width='2em' /></td>
        <td style={cellStyle}>questionOutline</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconQuestionOutline } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHouse height='2em' width='2em' /></td>
        <td style={cellStyle}>house</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconHouse } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSave height='2em' width='2em' /></td>
        <td style={cellStyle}>save</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSave } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHospital height='2em' width='2em' /></td>
        <td style={cellStyle}>hospital</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconHospital } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPending height='2em' width='2em' /></td>
        <td style={cellStyle}>pending</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPending } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconAnalytics height='2em' width='2em' /></td>
        <td style={cellStyle}>analytics</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconAnalytics } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconAnnouncement height='2em' width='2em' /></td>
        <td style={cellStyle}>announcement</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconAnnouncement } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCamera height='2em' width='2em' /></td>
        <td style={cellStyle}>camera</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCamera } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconBriefcase height='2em' width='2em' /></td>
        <td style={cellStyle}>briefcase</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconBriefcase } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconLink height='2em' width='2em' /></td>
        <td style={cellStyle}>link</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconLink } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMenu height='2em' width='2em' /></td>
        <td style={cellStyle}>menu</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMenu } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconList height='2em' width='2em' /></td>
        <td style={cellStyle}>list</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconList } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconChecklist height='2em' width='2em' /></td>
        <td style={cellStyle}>checklist</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconChecklist } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconUnlock height='2em' width='2em' /></td>
        <td style={cellStyle}>unlock</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconUnlock } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDue height='2em' width='2em' /></td>
        <td style={cellStyle}>due</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDue } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSpinner height='2em' width='2em' /></td>
        <td style={cellStyle}>spinner</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSpinner } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTile height='2em' width='2em' /></td>
        <td style={cellStyle}>tile</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTile } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconUsers height='2em' width='2em' /></td>
        <td style={cellStyle}>users</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconUsers } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconKnurling height='2em' width='2em' /></td>
        <td style={cellStyle}>knurling</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconKnurling } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconAddPerson height='2em' width='2em' /></td>
        <td style={cellStyle}>addPerson</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconAddPerson } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconUpload height='2em' width='2em' /></td>
        <td style={cellStyle}>upload</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconUpload } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDownload height='2em' width='2em' /></td>
        <td style={cellStyle}>download</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDownload } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCancel height='2em' width='2em' /></td>
        <td style={cellStyle}>cancel</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCancel } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMaximize height='2em' width='2em' /></td>
        <td style={cellStyle}>maximize</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMaximize } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMinimize height='2em' width='2em' /></td>
        <td style={cellStyle}>minimize</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMinimize } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconReply height='2em' width='2em' /></td>
        <td style={cellStyle}>reply</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconReply } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTable height='2em' width='2em' /></td>
        <td style={cellStyle}>table</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTable } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconRequired height='2em' width='2em' /></td>
        <td style={cellStyle}>required</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconRequired } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconGapChecking height='2em' width='2em' /></td>
        <td style={cellStyle}>gap checking</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconGapChecking } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPersonHospital height='2em' width='2em' /></td>
        <td style={cellStyle}>personHospital</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPersonHospital } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPersonnelPerson height='2em' width='2em' /></td>
        <td style={cellStyle}>personnelPerson</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPersonnelPerson } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconLeftPane height='2em' width='2em' /></td>
        <td style={cellStyle}>leftPane</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconLeftPane } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconFlowsheet height='2em' width='2em' /></td>
        <td style={cellStyle}>flowsheet</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconFlowsheet } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconNotificationOff height='2em' width='2em' /></td>
        <td style={cellStyle}>notificationOff</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconNotificationOff } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconNotification height='2em' width='2em' /></td>
        <td style={cellStyle}>notification</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconNotification } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconNotificationDisabled height='2em' width='2em' /></td>
        <td style={cellStyle}>notificationDisabled</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconNotificationDisabled } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconLast height='2em' width='2em' /></td>
        <td style={cellStyle}>last</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconLast } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDevice height='2em' width='2em' /></td>
        <td style={cellStyle}>device</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDevice } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPaperPencil height='2em' width='2em' /></td>
        <td style={cellStyle}>paperPencil</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPaperPencil } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconClipboard height='2em' width='2em' /></td>
        <td style={cellStyle}>clipboard</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconClipboard } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconZoomOut height='2em' width='2em' /></td>
        <td style={cellStyle}>zoomOut</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconZoomOut } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconZoomIn height='2em' width='2em' /></td>
        <td style={cellStyle}>zoomIn</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconZoomIn } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconEnvelope height='2em' width='2em' /></td>
        <td style={cellStyle}>envelope</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconEnvelope } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconEnvelopeFill height='2em' width='2em' /></td>
        <td style={cellStyle}>envelopeFill</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconEnvelopeFill } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconAllergy height='2em' width='2em' /></td>
        <td style={cellStyle}>allergy</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconAllergy } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPhoneDown height='2em' width='2em' /></td>
        <td style={cellStyle}>phoneDown</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPhoneDown } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPhone height='2em' width='2em' /></td>
        <td style={cellStyle}>phone</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPhone } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPanelLeft height='2em' width='2em' /></td>
        <td style={cellStyle}>panelLeft</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPanelLeft } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPanelRight height='2em' width='2em' /></td>
        <td style={cellStyle}>panelRight</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPanelRight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTag height='2em' width='2em' /></td>
        <td style={cellStyle}>tag</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTag } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconIPass height='2em' width='2em' /></td>
        <td style={cellStyle}>iPass</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconIPass } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconScratchPad height='2em' width='2em' /></td>
        <td style={cellStyle}>scratchPad</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconScratchPad } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPharmacyReview height='2em' width='2em' /></td>
        <td style={cellStyle}>pharmacyReview</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPharmacyReview } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconBusy height='2em' width='2em' /></td>
        <td style={cellStyle}>busy</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconBusy } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconUnavailable height='2em' width='2em' /></td>
        <td style={cellStyle}>unavailable</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconUnavailable } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconImplant height='2em' width='2em' /></td>
        <td style={cellStyle}>implant</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconImplant } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconProtocol height='2em' width='2em' /></td>
        <td style={cellStyle}>protocol</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconProtocol } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconVideoCamera height='2em' width='2em' /></td>
        <td style={cellStyle}>videoCamera</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconVideoCamera } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconVideoCameraDisabled height='2em' width='2em' /></td>
        <td style={cellStyle}>videoCameraDisabled</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconVideoCameraDisabled } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconNoSignal height='2em' width='2em' /></td>
        <td style={cellStyle}>noSignal</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconNoSignal } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconUndo height='2em' width='2em' /></td>
        <td style={cellStyle}>undo</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconUndo } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconRecurringEvent height='2em' width='2em' /></td>
        <td style={cellStyle}>recurringEvent</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconRecurringEvent } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSeparate height='2em' width='2em' /></td>
        <td style={cellStyle}>separate</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSeparate } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMerge height='2em' width='2em' /></td>
        <td style={cellStyle}>merge</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMerge } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCompose height='2em' width='2em' /></td>
        <td style={cellStyle}>compose</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCompose } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconUnread height='2em' width='2em' /></td>
        <td style={cellStyle}>unread</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconUnread } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSwap height='2em' width='2em' /></td>
        <td style={cellStyle}>swap</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSwap } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMicrophone height='2em' width='2em' /></td>
        <td style={cellStyle}>microphone</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMicrophone } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMicrophoneDisabled height='2em' width='2em' /></td>
        <td style={cellStyle}>microphoneDisabled</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMicrophoneDisabled } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconOutgoingCall height='2em' width='2em' /></td>
        <td style={cellStyle}>outgoingCall</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconOutgoingCall } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconIncomingCall height='2em' width='2em' /></td>
        <td style={cellStyle}>incomingCall</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconIncomingCall } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMissedCall height='2em' width='2em' /></td>
        <td style={cellStyle}>missedCall</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMissedCall } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPinDown height='2em' width='2em' /></td>
        <td style={cellStyle}>pinDown</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPinDown } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPinDiagonal height='2em' width='2em' /></td>
        <td style={cellStyle}>pinDiagonal</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPinDiagonal } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconAudio height='2em' width='2em' /></td>
        <td style={cellStyle}>audio</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconAudio } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconExternalLink height='2em' width='2em' /></td>
        <td style={cellStyle}>externalLink</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconExternalLink } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconBedRequested height='2em' width='2em' /></td>
        <td style={cellStyle}>bedRequested</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconBedRequested } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconFlipVertical height='2em' width='2em' /></td>
        <td style={cellStyle}>flipVertical</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconFlipVertical } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconFlipHorizontal height='2em' width='2em' /></td>
        <td style={cellStyle}>flipHorizontal</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconFlipHorizontal } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconRotateLeft height='2em' width='2em' /></td>
        <td style={cellStyle}>rotateLeft</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconRotateLeft } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconRotateRight height='2em' width='2em' /></td>
        <td style={cellStyle}>rotateRight</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconRotateRight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHold height='2em' width='2em' /></td>
        <td style={cellStyle}>hold</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconHold } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconFitWidth height='2em' width='2em' /></td>
        <td style={cellStyle}>fitWidth</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconFitWidth } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconFitScale height='2em' width='2em' /></td>
        <td style={cellStyle}>fitScale</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconFitScale } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSecondaryProvider height='2em' width='2em' /></td>
        <td style={cellStyle}>secondaryProvider</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSecondaryProvider } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPartiallyMet height='2em' width='2em' /></td>
        <td style={cellStyle}>partiallyMet</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPartiallyMet } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSimulation height='2em' width='2em' /></td>
        <td style={cellStyle}>simulation</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSimulation } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCollapseRow height='2em' width='2em' /></td>
        <td style={cellStyle}>collapseRow</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCollapseRow } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconExpandRow height='2em' width='2em' /></td>
        <td style={cellStyle}>expandRow</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconExpandRow } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDoubleChevronLeft height='2em' width='2em' /></td>
        <td style={cellStyle}>doubleChevronLeft</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDoubleChevronLeft } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDoubleChevronRight height='2em' width='2em' /></td>
        <td style={cellStyle}>doubleChevronRight</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDoubleChevronRight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconExtensions height='2em' width='2em' /></td>
        <td style={cellStyle}>extensions</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconExtensions } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDocumentPlus height='2em' width='2em' /></td>
        <td style={cellStyle}>documentPlus</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDocumentPlus } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconRefusedSlot height='2em' width='2em' /></td>
        <td style={cellStyle}>refusedSlot</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconRefusedSlot } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPharmacyVerification height='2em' width='2em' /></td>
        <td style={cellStyle}>pharmacyVerification</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPharmacyVerification } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconFitHeight height='2em' width='2em' /></td>
        <td style={cellStyle}>fitHeight</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconFitHeight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPersonDoor height='2em' width='2em' /></td>
        <td style={cellStyle}>personDoor</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPersonDoor } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconLocationPin height='2em' width='2em' /></td>
        <td style={cellStyle}>locationPin</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconLocationPin } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMediaPlay height='2em' width='2em' /></td>
        <td style={cellStyle}>mediaPlay</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMediaPlay } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMediaPause height='2em' width='2em' /></td>
        <td style={cellStyle}>mediaPause</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMediaPause } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMediaStop height='2em' width='2em' /></td>
        <td style={cellStyle}>mediaStop</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMediaStop } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMediaRecord height='2em' width='2em' /></td>
        <td style={cellStyle}>mediaRecord</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMediaRecord } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMediaFastForward height='2em' width='2em' /></td>
        <td style={cellStyle}>mediaFastForward</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMediaFastForward } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMediaRewind height='2em' width='2em' /></td>
        <td style={cellStyle}>mediaRewind</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMediaRewind } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconBluetooth height='2em' width='2em' /></td>
        <td style={cellStyle}>bluetooth</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconBluetooth } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconBluetoothSlash height='2em' width='2em' /></td>
        <td style={cellStyle}>bluetoothSlash</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconBluetoothSlash } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconStartPresenting height='2em' width='2em' /></td>
        <td style={cellStyle}>startPresenting</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconStartPresenting } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconStopPresenting height='2em' width='2em' /></td>
        <td style={cellStyle}>stopPresenting</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconStopPresenting } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPager height='2em' width='2em' /></td>
        <td style={cellStyle}>pager</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPager } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconAutoText height='2em' width='2em' /></td>
        <td style={cellStyle}>autoText</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconAutoText } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconKeyboard height='2em' width='2em' /></td>
        <td style={cellStyle}>keyboard</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconKeyboard } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSharedSchedules height='2em' width='2em' /></td>
        <td style={cellStyle}>sharedSchedules</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSharedSchedules } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPatientSearch height='2em' width='2em' /></td>
        <td style={cellStyle}>patientSearch</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPatientSearch } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconGroup height='2em' width='2em' /></td>
        <td style={cellStyle}>group</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconGroup } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMedicationTablet height='2em' width='2em' /></td>
        <td style={cellStyle}>medicationTablet</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMedicationTablet } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMedicationTabletOutline height='2em' width='2em' /></td>
        <td style={cellStyle}>medicationTabletOutline</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMedicationTabletOutline } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMedicationTabletHalf height='2em' width='2em' /></td>
        <td style={cellStyle}>medicationTabletHalf</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMedicationTabletHalf } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMedicationTabletHalfOutline height='2em' width='2em' /></td>
        <td style={cellStyle}>medicationTabletHalfOutline</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMedicationTabletHalfOutline } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconWaveform height='2em' width='2em' /></td>
        <td style={cellStyle}>waveform</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconWaveform } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconConfidential height='2em' width='2em' /></td>
        <td style={cellStyle}>confidential</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconConfidential } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconWifi height='2em' width='2em' /></td>
        <td style={cellStyle}>wifi</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconWifi } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconWifiSlash height='2em' width='2em' /></td>
        <td style={cellStyle}>wifiSlash</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconWifiSlash } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconBrokenImage height='2em' width='2em' /></td>
        <td style={cellStyle}>brokenImage</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconBrokenImage } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconBrokenLinkUnlink height='2em' width='2em' /></td>
        <td style={cellStyle}>brokenLink_unlink</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconBrokenLinkUnlink } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconVolumeSetDefault height='2em' width='2em' /></td>
        <td style={cellStyle}>volumeSet_default</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconVolumeSetDefault } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconVolumeSetDecrease height='2em' width='2em' /></td>
        <td style={cellStyle}>volumeSet_decrease</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconVolumeSetDecrease } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconVolumeSetIncrease height='2em' width='2em' /></td>
        <td style={cellStyle}>volumeSet_increase</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconVolumeSetIncrease } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconVolumeSetMute height='2em' width='2em' /></td>
        <td style={cellStyle}>volumeSet_mute</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconVolumeSetMute } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPersonConnection height='2em' width='2em' /></td>
        <td style={cellStyle}>personConnection</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPersonConnection } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTrendingUp height='2em' width='2em' /></td>
        <td style={cellStyle}>trendingUp</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTrendingUp } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTrendingDown height='2em' width='2em' /></td>
        <td style={cellStyle}>trendingDown</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTrendingDown } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconNoResults height='2em' width='2em' /></td>
        <td style={cellStyle}>noResults</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconNoResults } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconNavStackUp height='2em' width='2em' /></td>
        <td style={cellStyle}>navStackUp</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconNavStackUp } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMultipleResultsNormal height='2em' width='2em' /></td>
        <td style={cellStyle}>multipleResultsNormal</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMultipleResultsNormal } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMultipleResultsNotNormal height='2em' width='2em' /></td>
        <td style={cellStyle}>multipleResultsNotNormal</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMultipleResultsNotNormal } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMultipleResultsCritical height='2em' width='2em' /></td>
        <td style={cellStyle}>multipleResultsCritical</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMultipleResultsCritical } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCircleSymbol height='2em' width='2em' /></td>
        <td style={cellStyle}>circle_symbol</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCircleSymbol } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCircleSymbolLight height='2em' width='2em' /></td>
        <td style={cellStyle}>circle_symbol_light</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCircleSymbolLight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDiamondSymbol height='2em' width='2em' /></td>
        <td style={cellStyle}>diamond_symbol</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDiamondSymbol } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDiamondSymbolLight height='2em' width='2em' /></td>
        <td style={cellStyle}>diamond_symbol_light</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDiamondSymbolLight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPlusSymbol height='2em' width='2em' /></td>
        <td style={cellStyle}>plus_symbol</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPlusSymbol } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPlusSymbolLight height='2em' width='2em' /></td>
        <td style={cellStyle}>plus_symbol_light</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPlusSymbolLight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconRectangleSymbol height='2em' width='2em' /></td>
        <td style={cellStyle}>rectangle_symbol</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconRectangleSymbol } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconRectangleSymbolLight height='2em' width='2em' /></td>
        <td style={cellStyle}>rectangle_symbol_light</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconRectangleSymbolLight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSquareSymbol height='2em' width='2em' /></td>
        <td style={cellStyle}>square_symbol</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSquareSymbol } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSquareSymbolLight height='2em' width='2em' /></td>
        <td style={cellStyle}>square_symbol_light</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSquareSymbolLight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTeardropSymbol height='2em' width='2em' /></td>
        <td style={cellStyle}>teardrop_symbol</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTeardropSymbol } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTeardropSymbolLight height='2em' width='2em' /></td>
        <td style={cellStyle}>teardrop_symbol_light</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTeardropSymbolLight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTeardropUpSymbol height='2em' width='2em' /></td>
        <td style={cellStyle}>teardropUp_symbol</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTeardropUpSymbol } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTeardropUpSymbolLight height='2em' width='2em' /></td>
        <td style={cellStyle}>teardropUp_symbol_light</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTeardropUpSymbolLight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconThinDiamondSymbol height='2em' width='2em' /></td>
        <td style={cellStyle}>thinDiamond_symbol</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconThinDiamondSymbol } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconThinDiamondSymbolLight height='2em' width='2em' /></td>
        <td style={cellStyle}>thinDiamond_symbol_light</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconThinDiamondSymbolLight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTriangleSymbol height='2em' width='2em' /></td>
        <td style={cellStyle}>triangle_symbol</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTriangleSymbol } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTriangleSymbolLight height='2em' width='2em' /></td>
        <td style={cellStyle}>triangle_symbol_light</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTriangleSymbolLight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTriangleDownSymbol height='2em' width='2em' /></td>
        <td style={cellStyle}>triangleDown_symbol</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTriangleDownSymbol } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconTriangleDownSymbolLight height='2em' width='2em' /></td>
        <td style={cellStyle}>triangleDown_symbol_light</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconTriangleDownSymbolLight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconXSymbol height='2em' width='2em' /></td>
        <td style={cellStyle}>x_symbol</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconXSymbol } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconXSymbolLight height='2em' width='2em' /></td>
        <td style={cellStyle}>x_symbol_light</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconXSymbolLight } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCircleLinesSymbol height='2em' width='2em' /></td>
        <td style={cellStyle}>circleLines_symbol</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCircleLinesSymbol } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCatalogueNumber height='2em' width='2em' /></td>
        <td style={cellStyle}>catalogueNumber</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCatalogueNumber } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCaution height='2em' width='2em' /></td>
        <td style={cellStyle}>caution</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCaution } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconConsultInstructionsForUse height='2em' width='2em' /></td>
        <td style={cellStyle}>consultInstructionsForUse</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconConsultInstructionsForUse } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDateOfManufacture height='2em' width='2em' /></td>
        <td style={cellStyle}>dateOfManufacture</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDateOfManufacture } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconManufacturer height='2em' width='2em' /></td>
        <td style={cellStyle}>manufacturer</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconManufacturer } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCeMarking height='2em' width='2em' /></td>
        <td style={cellStyle}>ceMarking</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconEcRep height='2em' width='2em' /></td>
        <td style={cellStyle}>ecRep</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconEcRep } from 'terra-icon';
          </code>
        </td>
      </tr>
    </tbody>
  </table>
  </div>);

export default IconAll;
