// This file is autogenerated from scripts/src/generate-example
/* eslint-disable */
import React from 'react';
import { 
  IconSuccess,
IconSuccessInverse ,
IconAvailable ,
IconComplete ,
IconNoRisk ,
IconScheduled ,
IconRollup ,
IconHighPriority ,
IconAlert ,
IconWarning ,
IconModerate ,
IconUnspecified ,
IconCritical ,
IconCriticalInverse ,
IconHazardLow ,
IconInformation ,
IconInformationInverse ,
IconInformationStatic ,
IconErrorDark ,
IconError ,
IconDoNotDisturb ,
IconIncompleteInverse ,
IconFeaturedOutlineYellow ,
IconHelp ,
IconHelpInverse ,
IconHelpStatic ,
IconUnexpected ,
IconDueSoon ,
IconOverDue ,
IconHigh ,
IconHighInverse ,
IconLow ,
IconLowRisk ,
IconMax ,
IconMin ,
IconAbnormal ,
IconDeviceCheck ,
IconDeviceAlert ,
IconDiamond ,
IconPharmacyReject, 
IconHide ,
IconBedAssigned ,
IconDischargeComplete ,
IconDischargeComingDue,
IconDischargeOverDue ,
IconDrugDrug ,
IconOutOfNetwork ,
IconStatusPositive ,
IconStatusPositiveWhite,
} from 'terra-icon';

const cellStyle = { padding: '0.5rem' };
const IconAll = () => (
  <div>  <table>
    <thead>
    <tr>
      <th style={cellStyle} key={'svg'}>SVG</th>
      <th style={cellStyle} key={'concept'}>Concept</th>
      <th style={cellStyle} key={'code'}>Code</th>
    </tr>
    </thead>
    <tbody>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSuccess height='2em' width='2em' /></td>
        <td style={cellStyle}>success</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSuccess } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSuccessInverse height='2em' width='2em' /></td>
        <td style={cellStyle}>success_inverse</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconSuccessInverse } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconAvailable height='2em' width='2em' /></td>
        <td style={cellStyle}>available</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconAvailable } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconComplete height='2em' width='2em' /></td>
        <td style={cellStyle}>complete</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconComplete } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconNoRisk height='2em' width='2em' /></td>
        <td style={cellStyle}>noRisk</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconNoRisk } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconScheduled height='2em' width='2em' /></td>
        <td style={cellStyle}>scheduled</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconScheduled } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconRollup height='2em' width='2em' /></td>
        <td style={cellStyle}>rollup</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconRollup } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHighPriority height='2em' width='2em' /></td>
        <td style={cellStyle}>highPriority</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconHighPriority } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconAlert height='2em' width='2em' /></td>
        <td style={cellStyle}>alert</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconAlert } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconWarning height='2em' width='2em' /></td>
        <td style={cellStyle}>warning</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconWarning } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconModerate height='2em' width='2em' /></td>
        <td style={cellStyle}>moderate</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconModerate } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconUnspecified height='2em' width='2em' /></td>
        <td style={cellStyle}>unspecified</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconUnspecified } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCritical height='2em' width='2em' /></td>
        <td style={cellStyle}>critical</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCritical } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCriticalInverse height='2em' width='2em' /></td>
        <td style={cellStyle}>critical_inverse</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconCriticalInverse } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHazardLow height='2em' width='2em' /></td>
        <td style={cellStyle}>hazardLow</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconHazardLow } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconInformation height='2em' width='2em' /></td>
        <td style={cellStyle}>information</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconInformation } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconInformationInverse height='2em' width='2em' /></td>
        <td style={cellStyle}>information_inverse</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconInformationInverse } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconInformationStatic height='2em' width='2em' /></td>
        <td style={cellStyle}>information_static</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconInformationStatic } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconErrorDark height='2em' width='2em' /></td>
        <td style={cellStyle}>error_dark</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconErrorDark } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconError height='2em' width='2em' /></td>
        <td style={cellStyle}>error</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconError } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDoNotDisturb height='2em' width='2em' /></td>
        <td style={cellStyle}>doNotDisturb</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDoNotDisturb } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconIncompleteInverse height='2em' width='2em' /></td>
        <td style={cellStyle}>incomplete_inverse</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconIncompleteInverse } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconFeaturedOutlineYellow height='2em' width='2em' /></td>
        <td style={cellStyle}>featuredOutlineYellow</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconFeaturedOutlineYellow } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHelp height='2em' width='2em' /></td>
        <td style={cellStyle}>help</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconHelp } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHelpInverse height='2em' width='2em' /></td>
        <td style={cellStyle}>help_inverse</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconHelpInverse } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHelpStatic height='2em' width='2em' /></td>
        <td style={cellStyle}>help_static</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconHelpStatic } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconUnexpected height='2em' width='2em' /></td>
        <td style={cellStyle}>unexpected</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconUnexpected } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDueSoon height='2em' width='2em' /></td>
        <td style={cellStyle}>dueSoon</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDueSoon } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconOverDue height='2em' width='2em' /></td>
        <td style={cellStyle}>overDue</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconOverDue } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHigh height='2em' width='2em' /></td>
        <td style={cellStyle}>high</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconHigh } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHighInverse height='2em' width='2em' /></td>
        <td style={cellStyle}>high_inverse</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconHighInverse } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconLow height='2em' width='2em' /></td>
        <td style={cellStyle}>low</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconLow } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconLowRisk height='2em' width='2em' /></td>
        <td style={cellStyle}>lowRisk</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconLowRisk } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMax height='2em' width='2em' /></td>
        <td style={cellStyle}>max</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMax } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMin height='2em' width='2em' /></td>
        <td style={cellStyle}>min</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconMin } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconAbnormal height='2em' width='2em' /></td>
        <td style={cellStyle}>abnormal</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconAbnormal } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDeviceCheck height='2em' width='2em' /></td>
        <td style={cellStyle}>deviceCheck</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDeviceCheck } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDeviceAlert height='2em' width='2em' /></td>
        <td style={cellStyle}>deviceAlert</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDeviceAlert } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDiamond height='2em' width='2em' /></td>
        <td style={cellStyle}>diamond</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDiamond } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPharmacyReject height='2em' width='2em' /></td>
        <td style={cellStyle}>pharmacyReject</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconPharmacyReject } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHide height='2em' width='2em' /></td>
        <td style={cellStyle}>hide</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconHide } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconBedAssigned height='2em' width='2em' /></td>
        <td style={cellStyle}>bedAssigned</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconBedAssigned } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDischargeComplete height='2em' width='2em' /></td>
        <td style={cellStyle}>dischargeComplete</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDischargeComplete } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDischargeComingDue height='2em' width='2em' /></td>
        <td style={cellStyle}>dischargeComingDue</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDischargeComingDue } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDischargeOverDue height='2em' width='2em' /></td>
        <td style={cellStyle}>dischargeOverDue</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDischargeOverDue } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDrugDrug height='2em' width='2em' /></td>
        <td style={cellStyle}>drugDrug</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconDrugDrug } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconOutOfNetwork height='2em' width='2em' /></td>
        <td style={cellStyle}>outOfNetwork</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconOutOfNetwork } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconStatusPositive height='2em' width='2em' /></td>
        <td style={cellStyle}>statusPositive</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconStatusPositive } from 'terra-icon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconStatusPositiveWhite height='2em' width='2em' /></td>
        <td style={cellStyle}>statusPositiveWhite</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import { IconStatusPositiveWhite } from 'terra-icon';
          </code>
        </td>
      </tr>
    </tbody>
  </table>
  </div>);

export default IconAll;
