// This file is autogenerated from scripts/src/generate-example
/* eslint-disable */
import React from 'react';
import IconSuccess from 'terra-icon/lib/icon/IconSuccess';
import IconSuccessInverse from 'terra-icon/lib/icon/IconSuccessInverse';
import IconAvailable from 'terra-icon/lib/icon/IconAvailable';
import IconComplete from 'terra-icon/lib/icon/IconComplete';
import IconNoRisk from 'terra-icon/lib/icon/IconNoRisk';
import IconScheduled from 'terra-icon/lib/icon/IconScheduled';
import IconRollup from 'terra-icon/lib/icon/IconRollup';
import IconHighPriority from 'terra-icon/lib/icon/IconHighPriority';
import IconAlert from 'terra-icon/lib/icon/IconAlert';
import IconWarning from 'terra-icon/lib/icon/IconWarning';
import IconModerate from 'terra-icon/lib/icon/IconModerate';
import IconUnspecified from 'terra-icon/lib/icon/IconUnspecified';
import IconCritical from 'terra-icon/lib/icon/IconCritical';
import IconCriticalInverse from 'terra-icon/lib/icon/IconCriticalInverse';
import IconInformation from 'terra-icon/lib/icon/IconInformation';
import IconInformationInverse from 'terra-icon/lib/icon/IconInformationInverse';
import IconErrorDark from 'terra-icon/lib/icon/IconErrorDark';
import IconError from 'terra-icon/lib/icon/IconError';
import IconDoNotDisturb from 'terra-icon/lib/icon/IconDoNotDisturb';
import IconIncompleteInverse from 'terra-icon/lib/icon/IconIncompleteInverse';
import IconFeaturedOutlineYellow from 'terra-icon/lib/icon/IconFeaturedOutlineYellow';
import IconHelp from 'terra-icon/lib/icon/IconHelp';
import IconHelpInverse from 'terra-icon/lib/icon/IconHelpInverse';
import IconUnexpected from 'terra-icon/lib/icon/IconUnexpected';
import IconDueSoon from 'terra-icon/lib/icon/IconDueSoon';
import IconOverDue from 'terra-icon/lib/icon/IconOverDue';
import IconHigh from 'terra-icon/lib/icon/IconHigh';
import IconHighInverse from 'terra-icon/lib/icon/IconHighInverse';
import IconLow from 'terra-icon/lib/icon/IconLow';
import IconLowRisk from 'terra-icon/lib/icon/IconLowRisk';
import IconMax from 'terra-icon/lib/icon/IconMax';
import IconMin from 'terra-icon/lib/icon/IconMin';
import IconAbnormal from 'terra-icon/lib/icon/IconAbnormal';
import IconDeviceCheck from 'terra-icon/lib/icon/IconDeviceCheck';
import IconDeviceAlert from 'terra-icon/lib/icon/IconDeviceAlert';
import IconDiamond from 'terra-icon/lib/icon/IconDiamond';
import IconPharmacyReject from 'terra-icon/lib/icon/IconPharmacyReject';
import IconHide from 'terra-icon/lib/icon/IconHide';
import IconBedAssigned from 'terra-icon/lib/icon/IconBedAssigned';
import IconDischargeComplete from 'terra-icon/lib/icon/IconDischargeComplete';
import IconDischargeComingDue from 'terra-icon/lib/icon/IconDischargeComingDue';
import IconDischargeOverDue from 'terra-icon/lib/icon/IconDischargeOverDue';
import IconDrugDrug from 'terra-icon/lib/icon/IconDrugDrug';
import IconOutOfNetwork from 'terra-icon/lib/icon/IconOutOfNetwork';
const cellStyle = { padding: '0.5rem' };
const IconAll = () => (
  <div>  <table>
    <thead>
    <tr>
      <th style={cellStyle} key={'svg'}>SVG</th>
      <th style={cellStyle} key={'concept'}>Concept</th>
      <th style={cellStyle} key={'code'}>Code</th>
    </tr>
    </thead>
    <tbody>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSuccess height='2em' width='2em' /></td>
        <td style={cellStyle}>success</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconSuccess from 'terra-icon/lib/icon/IconSuccess';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconSuccessInverse height='2em' width='2em' /></td>
        <td style={cellStyle}>success_inverse</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconSuccessInverse from 'terra-icon/lib/icon/IconSuccessInverse';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconAvailable height='2em' width='2em' /></td>
        <td style={cellStyle}>available</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconAvailable from 'terra-icon/lib/icon/IconAvailable';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconComplete height='2em' width='2em' /></td>
        <td style={cellStyle}>complete</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconComplete from 'terra-icon/lib/icon/IconComplete';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconNoRisk height='2em' width='2em' /></td>
        <td style={cellStyle}>noRisk</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconNoRisk from 'terra-icon/lib/icon/IconNoRisk';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconScheduled height='2em' width='2em' /></td>
        <td style={cellStyle}>scheduled</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconScheduled from 'terra-icon/lib/icon/IconScheduled';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconRollup height='2em' width='2em' /></td>
        <td style={cellStyle}>rollup</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconRollup from 'terra-icon/lib/icon/IconRollup';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHighPriority height='2em' width='2em' /></td>
        <td style={cellStyle}>highPriority</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconHighPriority from 'terra-icon/lib/icon/IconHighPriority';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconAlert height='2em' width='2em' /></td>
        <td style={cellStyle}>alert</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconAlert from 'terra-icon/lib/icon/IconAlert';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconWarning height='2em' width='2em' /></td>
        <td style={cellStyle}>warning</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconWarning from 'terra-icon/lib/icon/IconWarning';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconModerate height='2em' width='2em' /></td>
        <td style={cellStyle}>moderate</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconModerate from 'terra-icon/lib/icon/IconModerate';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconUnspecified height='2em' width='2em' /></td>
        <td style={cellStyle}>unspecified</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconUnspecified from 'terra-icon/lib/icon/IconUnspecified';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCritical height='2em' width='2em' /></td>
        <td style={cellStyle}>critical</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconCritical from 'terra-icon/lib/icon/IconCritical';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconCriticalInverse height='2em' width='2em' /></td>
        <td style={cellStyle}>critical_inverse</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconCriticalInverse from 'terra-icon/lib/icon/IconCriticalInverse';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconInformation height='2em' width='2em' /></td>
        <td style={cellStyle}>information</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconInformation from 'terra-icon/lib/icon/IconInformation';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconInformationInverse height='2em' width='2em' /></td>
        <td style={cellStyle}>information_inverse</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconInformationInverse from 'terra-icon/lib/icon/IconInformationInverse';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconErrorDark height='2em' width='2em' /></td>
        <td style={cellStyle}>error_dark</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconErrorDark from 'terra-icon/lib/icon/IconErrorDark';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconError height='2em' width='2em' /></td>
        <td style={cellStyle}>error</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconError from 'terra-icon/lib/icon/IconError';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDoNotDisturb height='2em' width='2em' /></td>
        <td style={cellStyle}>doNotDisturb</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconDoNotDisturb from 'terra-icon/lib/icon/IconDoNotDisturb';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconIncompleteInverse height='2em' width='2em' /></td>
        <td style={cellStyle}>incomplete_inverse</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconIncompleteInverse from 'terra-icon/lib/icon/IconIncompleteInverse';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconFeaturedOutlineYellow height='2em' width='2em' /></td>
        <td style={cellStyle}>featuredOutlineYellow</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconFeaturedOutlineYellow from 'terra-icon/lib/icon/IconFeaturedOutlineYellow';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHelp height='2em' width='2em' /></td>
        <td style={cellStyle}>help</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconHelp from 'terra-icon/lib/icon/IconHelp';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHelpInverse height='2em' width='2em' /></td>
        <td style={cellStyle}>help_inverse</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconHelpInverse from 'terra-icon/lib/icon/IconHelpInverse';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconUnexpected height='2em' width='2em' /></td>
        <td style={cellStyle}>unexpected</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconUnexpected from 'terra-icon/lib/icon/IconUnexpected';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDueSoon height='2em' width='2em' /></td>
        <td style={cellStyle}>dueSoon</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconDueSoon from 'terra-icon/lib/icon/IconDueSoon';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconOverDue height='2em' width='2em' /></td>
        <td style={cellStyle}>overDue</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconOverDue from 'terra-icon/lib/icon/IconOverDue';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHigh height='2em' width='2em' /></td>
        <td style={cellStyle}>high</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconHigh from 'terra-icon/lib/icon/IconHigh';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHighInverse height='2em' width='2em' /></td>
        <td style={cellStyle}>high_inverse</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconHighInverse from 'terra-icon/lib/icon/IconHighInverse';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconLow height='2em' width='2em' /></td>
        <td style={cellStyle}>low</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconLow from 'terra-icon/lib/icon/IconLow';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconLowRisk height='2em' width='2em' /></td>
        <td style={cellStyle}>lowRisk</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconLowRisk from 'terra-icon/lib/icon/IconLowRisk';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMax height='2em' width='2em' /></td>
        <td style={cellStyle}>max</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconMax from 'terra-icon/lib/icon/IconMax';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconMin height='2em' width='2em' /></td>
        <td style={cellStyle}>min</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconMin from 'terra-icon/lib/icon/IconMin';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconAbnormal height='2em' width='2em' /></td>
        <td style={cellStyle}>abnormal</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconAbnormal from 'terra-icon/lib/icon/IconAbnormal';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDeviceCheck height='2em' width='2em' /></td>
        <td style={cellStyle}>deviceCheck</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconDeviceCheck from 'terra-icon/lib/icon/IconDeviceCheck';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDeviceAlert height='2em' width='2em' /></td>
        <td style={cellStyle}>deviceAlert</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconDeviceAlert from 'terra-icon/lib/icon/IconDeviceAlert';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDiamond height='2em' width='2em' /></td>
        <td style={cellStyle}>diamond</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconDiamond from 'terra-icon/lib/icon/IconDiamond';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconPharmacyReject height='2em' width='2em' /></td>
        <td style={cellStyle}>pharmacyReject</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconPharmacyReject from 'terra-icon/lib/icon/IconPharmacyReject';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconHide height='2em' width='2em' /></td>
        <td style={cellStyle}>hide</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconHide from 'terra-icon/lib/icon/IconHide';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconBedAssigned height='2em' width='2em' /></td>
        <td style={cellStyle}>bedAssigned</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconBedAssigned from 'terra-icon/lib/icon/IconBedAssigned';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDischargeComplete height='2em' width='2em' /></td>
        <td style={cellStyle}>dischargeComplete</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconDischargeComplete from 'terra-icon/lib/icon/IconDischargeComplete';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDischargeComingDue height='2em' width='2em' /></td>
        <td style={cellStyle}>dischargeComingDue</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconDischargeComingDue from 'terra-icon/lib/icon/IconDischargeComingDue';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDischargeOverDue height='2em' width='2em' /></td>
        <td style={cellStyle}>dischargeOverDue</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconDischargeOverDue from 'terra-icon/lib/icon/IconDischargeOverDue';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconDrugDrug height='2em' width='2em' /></td>
        <td style={cellStyle}>drugDrug</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconDrugDrug from 'terra-icon/lib/icon/IconDrugDrug';
          </code>
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td style={cellStyle}><IconOutOfNetwork height='2em' width='2em' /></td>
        <td style={cellStyle}>outOfNetwork</td>
        <td style={{ fontWeight: 'bold', padding: '0.5rem' }}>
          <code>
            import IconOutOfNetwork from 'terra-icon/lib/icon/IconOutOfNetwork';
          </code>
        </td>
      </tr>
    </tbody>
  </table>
  </div>);

export default IconAll;
