// This file is autogenerated from scripts/src/generate-example
/* eslint-disable */
import React from 'react';
import IconAdd from 'terra-icon/lib/icon/IconAdd';
import IconSearch from 'terra-icon/lib/icon/IconSearch';
import IconCommit from 'terra-icon/lib/icon/IconCommit';
import IconCheckmark from 'terra-icon/lib/icon/IconCheckmark';
import IconTrash from 'terra-icon/lib/icon/IconTrash';
import IconPaperFolded from 'terra-icon/lib/icon/IconPaperFolded';
import IconPrinter from 'terra-icon/lib/icon/IconPrinter';
import IconComment from 'terra-icon/lib/icon/IconComment';
import IconBookmark from 'terra-icon/lib/icon/IconBookmark';
import IconModified from 'terra-icon/lib/icon/IconModified';
import IconFirst from 'terra-icon/lib/icon/IconFirst';
import IconFolder from 'terra-icon/lib/icon/IconFolder';
import IconAttachment from 'terra-icon/lib/icon/IconAttachment';
import IconSend from 'terra-icon/lib/icon/IconSend';
import IconPill from 'terra-icon/lib/icon/IconPill';
import IconVisualization from 'terra-icon/lib/icon/IconVisualization';
import IconLightbulb from 'terra-icon/lib/icon/IconLightbulb';
import IconForward from 'terra-icon/lib/icon/IconForward';
import IconProjects from 'terra-icon/lib/icon/IconProjects';
import IconReplyAll from 'terra-icon/lib/icon/IconReplyAll';
import IconFlag from 'terra-icon/lib/icon/IconFlag';
import IconCalculator from 'terra-icon/lib/icon/IconCalculator';
import IconCaretRight from 'terra-icon/lib/icon/IconCaretRight';
import IconCaretLeft from 'terra-icon/lib/icon/IconCaretLeft';
import IconCaretUp from 'terra-icon/lib/icon/IconCaretUp';
import IconCaretDown from 'terra-icon/lib/icon/IconCaretDown';
import IconTrophy from 'terra-icon/lib/icon/IconTrophy';
import IconChevronLeft from 'terra-icon/lib/icon/IconChevronLeft';
import IconPrevious from 'terra-icon/lib/icon/IconPrevious';
import IconChevronRight from 'terra-icon/lib/icon/IconChevronRight';
import IconNext from 'terra-icon/lib/icon/IconNext';
import IconChevronUp from 'terra-icon/lib/icon/IconChevronUp';
import IconExpandLess from 'terra-icon/lib/icon/IconExpandLess';
import IconChevron from 'terra-icon/lib/icon/IconChevron';
import IconChevronDown from 'terra-icon/lib/icon/IconChevronDown';
import IconExpandMore from 'terra-icon/lib/icon/IconExpandMore';
import IconClock from 'terra-icon/lib/icon/IconClock';
import IconAway from 'terra-icon/lib/icon/IconAway';
import IconSortAscending from 'terra-icon/lib/icon/IconSortAscending';
import IconSortDescending from 'terra-icon/lib/icon/IconSortDescending';
import IconTreemap from 'terra-icon/lib/icon/IconTreemap';
import IconGlasses from 'terra-icon/lib/icon/IconGlasses';
import IconImage from 'terra-icon/lib/icon/IconImage';
import IconDoorOpen from 'terra-icon/lib/icon/IconDoorOpen';
import IconEllipses from 'terra-icon/lib/icon/IconEllipses';
import IconExclamation from 'terra-icon/lib/icon/IconExclamation';
import IconItalicI from 'terra-icon/lib/icon/IconItalicI';
import IconMinus from 'terra-icon/lib/icon/IconMinus';
import IconClose from 'terra-icon/lib/icon/IconClose';
import IconClear from 'terra-icon/lib/icon/IconClear';
import IconIncomplete from 'terra-icon/lib/icon/IconIncomplete';
import IconNotMet from 'terra-icon/lib/icon/IconNotMet';
import IconPerson from 'terra-icon/lib/icon/IconPerson';
import IconLeft from 'terra-icon/lib/icon/IconLeft';
import IconRight from 'terra-icon/lib/icon/IconRight';
import IconUp from 'terra-icon/lib/icon/IconUp';
import IconDown from 'terra-icon/lib/icon/IconDown';
import IconSettings from 'terra-icon/lib/icon/IconSettings';
import IconEdit from 'terra-icon/lib/icon/IconEdit';
import IconCalendar from 'terra-icon/lib/icon/IconCalendar';
import IconLookback from 'terra-icon/lib/icon/IconLookback';
import IconRefresh from 'terra-icon/lib/icon/IconRefresh';
import IconProvider from 'terra-icon/lib/icon/IconProvider';
import IconPadlock from 'terra-icon/lib/icon/IconPadlock';
import IconFeatured from 'terra-icon/lib/icon/IconFeatured';
import IconFeaturedOff from 'terra-icon/lib/icon/IconFeaturedOff';
import IconFeaturedOutline from 'terra-icon/lib/icon/IconFeaturedOutline';
import IconHalfRating from 'terra-icon/lib/icon/IconHalfRating';
import IconArchive from 'terra-icon/lib/icon/IconArchive';
import IconFunnel from 'terra-icon/lib/icon/IconFunnel';
import IconDocuments from 'terra-icon/lib/icon/IconDocuments';
import IconQuestion from 'terra-icon/lib/icon/IconQuestion';
import IconUnknown from 'terra-icon/lib/icon/IconUnknown';
import IconQuestionOutline from 'terra-icon/lib/icon/IconQuestionOutline';
import IconHouse from 'terra-icon/lib/icon/IconHouse';
import IconSave from 'terra-icon/lib/icon/IconSave';
import IconHospital from 'terra-icon/lib/icon/IconHospital';
import IconPending from 'terra-icon/lib/icon/IconPending';
import IconAnalytics from 'terra-icon/lib/icon/IconAnalytics';
import IconAnnouncement from 'terra-icon/lib/icon/IconAnnouncement';
import IconCamera from 'terra-icon/lib/icon/IconCamera';
import IconBriefcase from 'terra-icon/lib/icon/IconBriefcase';
import IconLink from 'terra-icon/lib/icon/IconLink';
import IconMenu from 'terra-icon/lib/icon/IconMenu';
import IconList from 'terra-icon/lib/icon/IconList';
import IconChecklist from 'terra-icon/lib/icon/IconChecklist';
import IconUnlock from 'terra-icon/lib/icon/IconUnlock';
import IconDue from 'terra-icon/lib/icon/IconDue';
import IconSpinner from 'terra-icon/lib/icon/IconSpinner';
import IconTile from 'terra-icon/lib/icon/IconTile';
import IconUsers from 'terra-icon/lib/icon/IconUsers';
import IconKnurling from 'terra-icon/lib/icon/IconKnurling';
import IconAddPerson from 'terra-icon/lib/icon/IconAddPerson';
import IconUpload from 'terra-icon/lib/icon/IconUpload';
import IconDownload from 'terra-icon/lib/icon/IconDownload';
import IconCancel from 'terra-icon/lib/icon/IconCancel';
import IconMaximize from 'terra-icon/lib/icon/IconMaximize';
import IconMinimize from 'terra-icon/lib/icon/IconMinimize';
import IconReply from 'terra-icon/lib/icon/IconReply';
import IconTable from 'terra-icon/lib/icon/IconTable';
import IconRequired from 'terra-icon/lib/icon/IconRequired';
import IconGapChecking from 'terra-icon/lib/icon/IconGapChecking';
import IconPersonHospital from 'terra-icon/lib/icon/IconPersonHospital';
import IconPersonnelPerson from 'terra-icon/lib/icon/IconPersonnelPerson';
import IconLeftPane from 'terra-icon/lib/icon/IconLeftPane';
import IconFlowsheet from 'terra-icon/lib/icon/IconFlowsheet';
import IconNotificationOff from 'terra-icon/lib/icon/IconNotificationOff';
import IconNotification from 'terra-icon/lib/icon/IconNotification';
import IconLast from 'terra-icon/lib/icon/IconLast';
import IconDevice from 'terra-icon/lib/icon/IconDevice';
import IconPaperPencil from 'terra-icon/lib/icon/IconPaperPencil';
import IconClipboard from 'terra-icon/lib/icon/IconClipboard';
import IconZoomOut from 'terra-icon/lib/icon/IconZoomOut';
import IconZoomIn from 'terra-icon/lib/icon/IconZoomIn';
import IconEnvelope from 'terra-icon/lib/icon/IconEnvelope';
import IconAllergy from 'terra-icon/lib/icon/IconAllergy';
import IconPhoneDown from 'terra-icon/lib/icon/IconPhoneDown';
import IconPhone from 'terra-icon/lib/icon/IconPhone';
import IconPanelLeft from 'terra-icon/lib/icon/IconPanelLeft';
import IconPanelRight from 'terra-icon/lib/icon/IconPanelRight';
import IconTag from 'terra-icon/lib/icon/IconTag';
import IconIPass from 'terra-icon/lib/icon/IconIPass';
import IconScratchPad from 'terra-icon/lib/icon/IconScratchPad';
import IconPharmacyReview from 'terra-icon/lib/icon/IconPharmacyReview';
import IconBusy from 'terra-icon/lib/icon/IconBusy';
import IconUnavailable from 'terra-icon/lib/icon/IconUnavailable';
import IconImplant from 'terra-icon/lib/icon/IconImplant';
import IconProtocol from 'terra-icon/lib/icon/IconProtocol';
import IconVideoCamera from 'terra-icon/lib/icon/IconVideoCamera';
import IconVideoCameraDisabled from 'terra-icon/lib/icon/IconVideoCameraDisabled';
import IconNoSignal from 'terra-icon/lib/icon/IconNoSignal';
import IconReload from 'terra-icon/lib/icon/IconReload';
import IconRecurringEvent from 'terra-icon/lib/icon/IconRecurringEvent';
import IconSeparate from 'terra-icon/lib/icon/IconSeparate';
import IconMerge from 'terra-icon/lib/icon/IconMerge';
import IconCompose from 'terra-icon/lib/icon/IconCompose';
import IconUnread from 'terra-icon/lib/icon/IconUnread';
import IconSwap from 'terra-icon/lib/icon/IconSwap';
import IconMicrophone from 'terra-icon/lib/icon/IconMicrophone';
import IconMicrophoneDisabled from 'terra-icon/lib/icon/IconMicrophoneDisabled';
import IconOutgoingCall from 'terra-icon/lib/icon/IconOutgoingCall';
import IconIncomingCall from 'terra-icon/lib/icon/IconIncomingCall';
import IconMissedCall from 'terra-icon/lib/icon/IconMissedCall';
import IconPinDown from 'terra-icon/lib/icon/IconPinDown';
import IconPinDiagonal from 'terra-icon/lib/icon/IconPinDiagonal';
import IconPause from 'terra-icon/lib/icon/IconPause';
import IconAudio from 'terra-icon/lib/icon/IconAudio';
import IconExternalLink from 'terra-icon/lib/icon/IconExternalLink';
import IconBedRequested from 'terra-icon/lib/icon/IconBedRequested';
import IconFlipVertical from 'terra-icon/lib/icon/IconFlipVertical';
import IconFlipHorizontal from 'terra-icon/lib/icon/IconFlipHorizontal';
import IconRotateLeft from 'terra-icon/lib/icon/IconRotateLeft';
import IconRotateRight from 'terra-icon/lib/icon/IconRotateRight';
import IconHold from 'terra-icon/lib/icon/IconHold';
import IconFitWidth from 'terra-icon/lib/icon/IconFitWidth';
import IconFitScale from 'terra-icon/lib/icon/IconFitScale';
import IconSecondaryProvider from 'terra-icon/lib/icon/IconSecondaryProvider';
import IconPartiallyMet from 'terra-icon/lib/icon/IconPartiallyMet';
import IconSimulation from 'terra-icon/lib/icon/IconSimulation';
import IconCollapseRow from 'terra-icon/lib/icon/IconCollapseRow';
import IconExpandRow from 'terra-icon/lib/icon/IconExpandRow';
import IconDoubleChevronLeft from 'terra-icon/lib/icon/IconDoubleChevronLeft';
import IconDoubleChevronRight from 'terra-icon/lib/icon/IconDoubleChevronRight';
import IconCircleSymbol from 'terra-icon/lib/icon/IconCircleSymbol';
import IconDiamondSymbol from 'terra-icon/lib/icon/IconDiamondSymbol';
import IconPlusSymbol from 'terra-icon/lib/icon/IconPlusSymbol';
import IconRectangleSymbol from 'terra-icon/lib/icon/IconRectangleSymbol';
import IconSquareSymbol from 'terra-icon/lib/icon/IconSquareSymbol';
import IconTeardropSymbol from 'terra-icon/lib/icon/IconTeardropSymbol';
import IconTeardropUpSymbol from 'terra-icon/lib/icon/IconTeardropUpSymbol';
import IconThinDiamondSymbol from 'terra-icon/lib/icon/IconThinDiamondSymbol';
import IconTriangleSymbol from 'terra-icon/lib/icon/IconTriangleSymbol';
import IconTriangleDownSymbol from 'terra-icon/lib/icon/IconTriangleDownSymbol';
import IconXSymbol from 'terra-icon/lib/icon/IconXSymbol';
import './IconTable.scss';

const IconThemeable = () => (
  <table className="icon-table">
    <thead>
      <tr>
        <th>SVG</th>
        <th>Concept</th>
        <th>Code</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><IconAdd height='2em' width='2em' /></td>
        <td>add</td>
        <td>
          <code>
            import IconAdd from 'terra-icon/lib/icon/IconAdd';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconSearch height='2em' width='2em' /></td>
        <td>search</td>
        <td>
          <code>
            import IconSearch from 'terra-icon/lib/icon/IconSearch';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconCommit height='2em' width='2em' /></td>
        <td>commit</td>
        <td>
          <code>
            import IconCommit from 'terra-icon/lib/icon/IconCommit';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconCheckmark height='2em' width='2em' /></td>
        <td>checkmark</td>
        <td>
          <code>
            import IconCheckmark from 'terra-icon/lib/icon/IconCheckmark';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconTrash height='2em' width='2em' /></td>
        <td>trash</td>
        <td>
          <code>
            import IconTrash from 'terra-icon/lib/icon/IconTrash';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPaperFolded height='2em' width='2em' /></td>
        <td>paperFolded</td>
        <td>
          <code>
            import IconPaperFolded from 'terra-icon/lib/icon/IconPaperFolded';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPrinter height='2em' width='2em' /></td>
        <td>printer</td>
        <td>
          <code>
            import IconPrinter from 'terra-icon/lib/icon/IconPrinter';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconComment height='2em' width='2em' /></td>
        <td>comment</td>
        <td>
          <code>
            import IconComment from 'terra-icon/lib/icon/IconComment';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconBookmark height='2em' width='2em' /></td>
        <td>bookmark</td>
        <td>
          <code>
            import IconBookmark from 'terra-icon/lib/icon/IconBookmark';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconModified height='2em' width='2em' /></td>
        <td>modified</td>
        <td>
          <code>
            import IconModified from 'terra-icon/lib/icon/IconModified';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconFirst height='2em' width='2em' /></td>
        <td>first</td>
        <td>
          <code>
            import IconFirst from 'terra-icon/lib/icon/IconFirst';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconFolder height='2em' width='2em' /></td>
        <td>folder</td>
        <td>
          <code>
            import IconFolder from 'terra-icon/lib/icon/IconFolder';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconAttachment height='2em' width='2em' /></td>
        <td>attachment</td>
        <td>
          <code>
            import IconAttachment from 'terra-icon/lib/icon/IconAttachment';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconSend height='2em' width='2em' /></td>
        <td>send</td>
        <td>
          <code>
            import IconSend from 'terra-icon/lib/icon/IconSend';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPill height='2em' width='2em' /></td>
        <td>pill</td>
        <td>
          <code>
            import IconPill from 'terra-icon/lib/icon/IconPill';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconVisualization height='2em' width='2em' /></td>
        <td>visualization</td>
        <td>
          <code>
            import IconVisualization from 'terra-icon/lib/icon/IconVisualization';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconLightbulb height='2em' width='2em' /></td>
        <td>lightbulb</td>
        <td>
          <code>
            import IconLightbulb from 'terra-icon/lib/icon/IconLightbulb';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconForward height='2em' width='2em' /></td>
        <td>forward</td>
        <td>
          <code>
            import IconForward from 'terra-icon/lib/icon/IconForward';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconProjects height='2em' width='2em' /></td>
        <td>projects</td>
        <td>
          <code>
            import IconProjects from 'terra-icon/lib/icon/IconProjects';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconReplyAll height='2em' width='2em' /></td>
        <td>replyAll</td>
        <td>
          <code>
            import IconReplyAll from 'terra-icon/lib/icon/IconReplyAll';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconFlag height='2em' width='2em' /></td>
        <td>flag</td>
        <td>
          <code>
            import IconFlag from 'terra-icon/lib/icon/IconFlag';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconCalculator height='2em' width='2em' /></td>
        <td>calculator</td>
        <td>
          <code>
            import IconCalculator from 'terra-icon/lib/icon/IconCalculator';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconCaretRight height='2em' width='2em' /></td>
        <td>caretRight</td>
        <td>
          <code>
            import IconCaretRight from 'terra-icon/lib/icon/IconCaretRight';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconCaretLeft height='2em' width='2em' /></td>
        <td>caretLeft</td>
        <td>
          <code>
            import IconCaretLeft from 'terra-icon/lib/icon/IconCaretLeft';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconCaretUp height='2em' width='2em' /></td>
        <td>caretUp</td>
        <td>
          <code>
            import IconCaretUp from 'terra-icon/lib/icon/IconCaretUp';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconCaretDown height='2em' width='2em' /></td>
        <td>caretDown</td>
        <td>
          <code>
            import IconCaretDown from 'terra-icon/lib/icon/IconCaretDown';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconTrophy height='2em' width='2em' /></td>
        <td>trophy</td>
        <td>
          <code>
            import IconTrophy from 'terra-icon/lib/icon/IconTrophy';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconChevronLeft height='2em' width='2em' /></td>
        <td>chevronLeft</td>
        <td>
          <code>
            import IconChevronLeft from 'terra-icon/lib/icon/IconChevronLeft';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPrevious height='2em' width='2em' /></td>
        <td>previous</td>
        <td>
          <code>
            import IconPrevious from 'terra-icon/lib/icon/IconPrevious';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconChevronRight height='2em' width='2em' /></td>
        <td>chevronRight</td>
        <td>
          <code>
            import IconChevronRight from 'terra-icon/lib/icon/IconChevronRight';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconNext height='2em' width='2em' /></td>
        <td>next</td>
        <td>
          <code>
            import IconNext from 'terra-icon/lib/icon/IconNext';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconChevronUp height='2em' width='2em' /></td>
        <td>chevronUp</td>
        <td>
          <code>
            import IconChevronUp from 'terra-icon/lib/icon/IconChevronUp';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconExpandLess height='2em' width='2em' /></td>
        <td>expandLess</td>
        <td>
          <code>
            import IconExpandLess from 'terra-icon/lib/icon/IconExpandLess';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconChevron height='2em' width='2em' /></td>
        <td>chevron</td>
        <td>
          <code>
            import IconChevron from 'terra-icon/lib/icon/IconChevron';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconChevronDown height='2em' width='2em' /></td>
        <td>chevronDown</td>
        <td>
          <code>
            import IconChevronDown from 'terra-icon/lib/icon/IconChevronDown';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconExpandMore height='2em' width='2em' /></td>
        <td>expandMore</td>
        <td>
          <code>
            import IconExpandMore from 'terra-icon/lib/icon/IconExpandMore';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconClock height='2em' width='2em' /></td>
        <td>clock</td>
        <td>
          <code>
            import IconClock from 'terra-icon/lib/icon/IconClock';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconAway height='2em' width='2em' /></td>
        <td>away</td>
        <td>
          <code>
            import IconAway from 'terra-icon/lib/icon/IconAway';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconSortAscending height='2em' width='2em' /></td>
        <td>sortAscending</td>
        <td>
          <code>
            import IconSortAscending from 'terra-icon/lib/icon/IconSortAscending';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconSortDescending height='2em' width='2em' /></td>
        <td>sortDescending</td>
        <td>
          <code>
            import IconSortDescending from 'terra-icon/lib/icon/IconSortDescending';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconTreemap height='2em' width='2em' /></td>
        <td>treemap</td>
        <td>
          <code>
            import IconTreemap from 'terra-icon/lib/icon/IconTreemap';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconGlasses height='2em' width='2em' /></td>
        <td>glasses</td>
        <td>
          <code>
            import IconGlasses from 'terra-icon/lib/icon/IconGlasses';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconImage height='2em' width='2em' /></td>
        <td>image</td>
        <td>
          <code>
            import IconImage from 'terra-icon/lib/icon/IconImage';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconDoorOpen height='2em' width='2em' /></td>
        <td>doorOpen</td>
        <td>
          <code>
            import IconDoorOpen from 'terra-icon/lib/icon/IconDoorOpen';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconEllipses height='2em' width='2em' /></td>
        <td>ellipses</td>
        <td>
          <code>
            import IconEllipses from 'terra-icon/lib/icon/IconEllipses';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconExclamation height='2em' width='2em' /></td>
        <td>exclamation</td>
        <td>
          <code>
            import IconExclamation from 'terra-icon/lib/icon/IconExclamation';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconItalicI height='2em' width='2em' /></td>
        <td>italic-i</td>
        <td>
          <code>
            import IconItalicI from 'terra-icon/lib/icon/IconItalicI';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconMinus height='2em' width='2em' /></td>
        <td>minus</td>
        <td>
          <code>
            import IconMinus from 'terra-icon/lib/icon/IconMinus';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconClose height='2em' width='2em' /></td>
        <td>close</td>
        <td>
          <code>
            import IconClose from 'terra-icon/lib/icon/IconClose';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconClear height='2em' width='2em' /></td>
        <td>clear</td>
        <td>
          <code>
            import IconClear from 'terra-icon/lib/icon/IconClear';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconIncomplete height='2em' width='2em' /></td>
        <td>incomplete</td>
        <td>
          <code>
            import IconIncomplete from 'terra-icon/lib/icon/IconIncomplete';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconNotMet height='2em' width='2em' /></td>
        <td>notMet</td>
        <td>
          <code>
            import IconNotMet from 'terra-icon/lib/icon/IconNotMet';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPerson height='2em' width='2em' /></td>
        <td>person</td>
        <td>
          <code>
            import IconPerson from 'terra-icon/lib/icon/IconPerson';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconLeft height='2em' width='2em' /></td>
        <td>left</td>
        <td>
          <code>
            import IconLeft from 'terra-icon/lib/icon/IconLeft';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconRight height='2em' width='2em' /></td>
        <td>right</td>
        <td>
          <code>
            import IconRight from 'terra-icon/lib/icon/IconRight';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconUp height='2em' width='2em' /></td>
        <td>up</td>
        <td>
          <code>
            import IconUp from 'terra-icon/lib/icon/IconUp';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconDown height='2em' width='2em' /></td>
        <td>down</td>
        <td>
          <code>
            import IconDown from 'terra-icon/lib/icon/IconDown';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconSettings height='2em' width='2em' /></td>
        <td>settings</td>
        <td>
          <code>
            import IconSettings from 'terra-icon/lib/icon/IconSettings';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconEdit height='2em' width='2em' /></td>
        <td>edit</td>
        <td>
          <code>
            import IconEdit from 'terra-icon/lib/icon/IconEdit';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconCalendar height='2em' width='2em' /></td>
        <td>calendar</td>
        <td>
          <code>
            import IconCalendar from 'terra-icon/lib/icon/IconCalendar';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconLookback height='2em' width='2em' /></td>
        <td>lookback</td>
        <td>
          <code>
            import IconLookback from 'terra-icon/lib/icon/IconLookback';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconRefresh height='2em' width='2em' /></td>
        <td>refresh</td>
        <td>
          <code>
            import IconRefresh from 'terra-icon/lib/icon/IconRefresh';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconProvider height='2em' width='2em' /></td>
        <td>provider</td>
        <td>
          <code>
            import IconProvider from 'terra-icon/lib/icon/IconProvider';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPadlock height='2em' width='2em' /></td>
        <td>padlock</td>
        <td>
          <code>
            import IconPadlock from 'terra-icon/lib/icon/IconPadlock';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconFeatured height='2em' width='2em' /></td>
        <td>featured</td>
        <td>
          <code>
            import IconFeatured from 'terra-icon/lib/icon/IconFeatured';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconFeaturedOff height='2em' width='2em' /></td>
        <td>featuredOff</td>
        <td>
          <code>
            import IconFeaturedOff from 'terra-icon/lib/icon/IconFeaturedOff';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconFeaturedOutline height='2em' width='2em' /></td>
        <td>featuredOutline</td>
        <td>
          <code>
            import IconFeaturedOutline from 'terra-icon/lib/icon/IconFeaturedOutline';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconHalfRating height='2em' width='2em' /></td>
        <td>halfRating</td>
        <td>
          <code>
            import IconHalfRating from 'terra-icon/lib/icon/IconHalfRating';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconArchive height='2em' width='2em' /></td>
        <td>archive</td>
        <td>
          <code>
            import IconArchive from 'terra-icon/lib/icon/IconArchive';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconFunnel height='2em' width='2em' /></td>
        <td>funnel</td>
        <td>
          <code>
            import IconFunnel from 'terra-icon/lib/icon/IconFunnel';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconDocuments height='2em' width='2em' /></td>
        <td>documents</td>
        <td>
          <code>
            import IconDocuments from 'terra-icon/lib/icon/IconDocuments';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconQuestion height='2em' width='2em' /></td>
        <td>question</td>
        <td>
          <code>
            import IconQuestion from 'terra-icon/lib/icon/IconQuestion';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconUnknown height='2em' width='2em' /></td>
        <td>unknown</td>
        <td>
          <code>
            import IconUnknown from 'terra-icon/lib/icon/IconUnknown';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconQuestionOutline height='2em' width='2em' /></td>
        <td>questionOutline</td>
        <td>
          <code>
            import IconQuestionOutline from 'terra-icon/lib/icon/IconQuestionOutline';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconHouse height='2em' width='2em' /></td>
        <td>house</td>
        <td>
          <code>
            import IconHouse from 'terra-icon/lib/icon/IconHouse';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconSave height='2em' width='2em' /></td>
        <td>save</td>
        <td>
          <code>
            import IconSave from 'terra-icon/lib/icon/IconSave';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconHospital height='2em' width='2em' /></td>
        <td>hospital</td>
        <td>
          <code>
            import IconHospital from 'terra-icon/lib/icon/IconHospital';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPending height='2em' width='2em' /></td>
        <td>pending</td>
        <td>
          <code>
            import IconPending from 'terra-icon/lib/icon/IconPending';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconAnalytics height='2em' width='2em' /></td>
        <td>analytics</td>
        <td>
          <code>
            import IconAnalytics from 'terra-icon/lib/icon/IconAnalytics';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconAnnouncement height='2em' width='2em' /></td>
        <td>announcement</td>
        <td>
          <code>
            import IconAnnouncement from 'terra-icon/lib/icon/IconAnnouncement';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconCamera height='2em' width='2em' /></td>
        <td>camera</td>
        <td>
          <code>
            import IconCamera from 'terra-icon/lib/icon/IconCamera';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconBriefcase height='2em' width='2em' /></td>
        <td>briefcase</td>
        <td>
          <code>
            import IconBriefcase from 'terra-icon/lib/icon/IconBriefcase';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconLink height='2em' width='2em' /></td>
        <td>link</td>
        <td>
          <code>
            import IconLink from 'terra-icon/lib/icon/IconLink';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconMenu height='2em' width='2em' /></td>
        <td>menu</td>
        <td>
          <code>
            import IconMenu from 'terra-icon/lib/icon/IconMenu';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconList height='2em' width='2em' /></td>
        <td>list</td>
        <td>
          <code>
            import IconList from 'terra-icon/lib/icon/IconList';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconChecklist height='2em' width='2em' /></td>
        <td>checklist</td>
        <td>
          <code>
            import IconChecklist from 'terra-icon/lib/icon/IconChecklist';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconUnlock height='2em' width='2em' /></td>
        <td>unlock</td>
        <td>
          <code>
            import IconUnlock from 'terra-icon/lib/icon/IconUnlock';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconDue height='2em' width='2em' /></td>
        <td>due</td>
        <td>
          <code>
            import IconDue from 'terra-icon/lib/icon/IconDue';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconSpinner height='2em' width='2em' /></td>
        <td>spinner</td>
        <td>
          <code>
            import IconSpinner from 'terra-icon/lib/icon/IconSpinner';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconTile height='2em' width='2em' /></td>
        <td>tile</td>
        <td>
          <code>
            import IconTile from 'terra-icon/lib/icon/IconTile';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconUsers height='2em' width='2em' /></td>
        <td>users</td>
        <td>
          <code>
            import IconUsers from 'terra-icon/lib/icon/IconUsers';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconKnurling height='2em' width='2em' /></td>
        <td>knurling</td>
        <td>
          <code>
            import IconKnurling from 'terra-icon/lib/icon/IconKnurling';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconAddPerson height='2em' width='2em' /></td>
        <td>addPerson</td>
        <td>
          <code>
            import IconAddPerson from 'terra-icon/lib/icon/IconAddPerson';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconUpload height='2em' width='2em' /></td>
        <td>upload</td>
        <td>
          <code>
            import IconUpload from 'terra-icon/lib/icon/IconUpload';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconDownload height='2em' width='2em' /></td>
        <td>download</td>
        <td>
          <code>
            import IconDownload from 'terra-icon/lib/icon/IconDownload';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconCancel height='2em' width='2em' /></td>
        <td>cancel</td>
        <td>
          <code>
            import IconCancel from 'terra-icon/lib/icon/IconCancel';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconMaximize height='2em' width='2em' /></td>
        <td>maximize</td>
        <td>
          <code>
            import IconMaximize from 'terra-icon/lib/icon/IconMaximize';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconMinimize height='2em' width='2em' /></td>
        <td>minimize</td>
        <td>
          <code>
            import IconMinimize from 'terra-icon/lib/icon/IconMinimize';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconReply height='2em' width='2em' /></td>
        <td>reply</td>
        <td>
          <code>
            import IconReply from 'terra-icon/lib/icon/IconReply';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconTable height='2em' width='2em' /></td>
        <td>table</td>
        <td>
          <code>
            import IconTable from 'terra-icon/lib/icon/IconTable';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconRequired height='2em' width='2em' /></td>
        <td>required</td>
        <td>
          <code>
            import IconRequired from 'terra-icon/lib/icon/IconRequired';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconGapChecking height='2em' width='2em' /></td>
        <td>gap checking</td>
        <td>
          <code>
            import IconGapChecking from 'terra-icon/lib/icon/IconGapChecking';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPersonHospital height='2em' width='2em' /></td>
        <td>personHospital</td>
        <td>
          <code>
            import IconPersonHospital from 'terra-icon/lib/icon/IconPersonHospital';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPersonnelPerson height='2em' width='2em' /></td>
        <td>personnelPerson</td>
        <td>
          <code>
            import IconPersonnelPerson from 'terra-icon/lib/icon/IconPersonnelPerson';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconLeftPane height='2em' width='2em' /></td>
        <td>leftPane</td>
        <td>
          <code>
            import IconLeftPane from 'terra-icon/lib/icon/IconLeftPane';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconFlowsheet height='2em' width='2em' /></td>
        <td>flowsheet</td>
        <td>
          <code>
            import IconFlowsheet from 'terra-icon/lib/icon/IconFlowsheet';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconNotificationOff height='2em' width='2em' /></td>
        <td>notificationOff</td>
        <td>
          <code>
            import IconNotificationOff from 'terra-icon/lib/icon/IconNotificationOff';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconNotification height='2em' width='2em' /></td>
        <td>notification</td>
        <td>
          <code>
            import IconNotification from 'terra-icon/lib/icon/IconNotification';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconLast height='2em' width='2em' /></td>
        <td>last</td>
        <td>
          <code>
            import IconLast from 'terra-icon/lib/icon/IconLast';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconDevice height='2em' width='2em' /></td>
        <td>device</td>
        <td>
          <code>
            import IconDevice from 'terra-icon/lib/icon/IconDevice';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPaperPencil height='2em' width='2em' /></td>
        <td>paperPencil</td>
        <td>
          <code>
            import IconPaperPencil from 'terra-icon/lib/icon/IconPaperPencil';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconClipboard height='2em' width='2em' /></td>
        <td>clipboard</td>
        <td>
          <code>
            import IconClipboard from 'terra-icon/lib/icon/IconClipboard';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconZoomOut height='2em' width='2em' /></td>
        <td>zoomOut</td>
        <td>
          <code>
            import IconZoomOut from 'terra-icon/lib/icon/IconZoomOut';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconZoomIn height='2em' width='2em' /></td>
        <td>zoomIn</td>
        <td>
          <code>
            import IconZoomIn from 'terra-icon/lib/icon/IconZoomIn';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconEnvelope height='2em' width='2em' /></td>
        <td>envelope</td>
        <td>
          <code>
            import IconEnvelope from 'terra-icon/lib/icon/IconEnvelope';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconAllergy height='2em' width='2em' /></td>
        <td>allergy</td>
        <td>
          <code>
            import IconAllergy from 'terra-icon/lib/icon/IconAllergy';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPhoneDown height='2em' width='2em' /></td>
        <td>phoneDown</td>
        <td>
          <code>
            import IconPhoneDown from 'terra-icon/lib/icon/IconPhoneDown';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPhone height='2em' width='2em' /></td>
        <td>phone</td>
        <td>
          <code>
            import IconPhone from 'terra-icon/lib/icon/IconPhone';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPanelLeft height='2em' width='2em' /></td>
        <td>panelLeft</td>
        <td>
          <code>
            import IconPanelLeft from 'terra-icon/lib/icon/IconPanelLeft';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPanelRight height='2em' width='2em' /></td>
        <td>panelRight</td>
        <td>
          <code>
            import IconPanelRight from 'terra-icon/lib/icon/IconPanelRight';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconTag height='2em' width='2em' /></td>
        <td>tag</td>
        <td>
          <code>
            import IconTag from 'terra-icon/lib/icon/IconTag';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconIPass height='2em' width='2em' /></td>
        <td>iPass</td>
        <td>
          <code>
            import IconIPass from 'terra-icon/lib/icon/IconIPass';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconScratchPad height='2em' width='2em' /></td>
        <td>scratchPad</td>
        <td>
          <code>
            import IconScratchPad from 'terra-icon/lib/icon/IconScratchPad';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPharmacyReview height='2em' width='2em' /></td>
        <td>pharmacyReview</td>
        <td>
          <code>
            import IconPharmacyReview from 'terra-icon/lib/icon/IconPharmacyReview';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconBusy height='2em' width='2em' /></td>
        <td>busy</td>
        <td>
          <code>
            import IconBusy from 'terra-icon/lib/icon/IconBusy';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconUnavailable height='2em' width='2em' /></td>
        <td>unavailable</td>
        <td>
          <code>
            import IconUnavailable from 'terra-icon/lib/icon/IconUnavailable';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconImplant height='2em' width='2em' /></td>
        <td>implant</td>
        <td>
          <code>
            import IconImplant from 'terra-icon/lib/icon/IconImplant';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconProtocol height='2em' width='2em' /></td>
        <td>protocol</td>
        <td>
          <code>
            import IconProtocol from 'terra-icon/lib/icon/IconProtocol';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconVideoCamera height='2em' width='2em' /></td>
        <td>videoCamera</td>
        <td>
          <code>
            import IconVideoCamera from 'terra-icon/lib/icon/IconVideoCamera';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconVideoCameraDisabled height='2em' width='2em' /></td>
        <td>videoCameraDisabled</td>
        <td>
          <code>
            import IconVideoCameraDisabled from 'terra-icon/lib/icon/IconVideoCameraDisabled';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconNoSignal height='2em' width='2em' /></td>
        <td>noSignal</td>
        <td>
          <code>
            import IconNoSignal from 'terra-icon/lib/icon/IconNoSignal';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconReload height='2em' width='2em' /></td>
        <td>reload</td>
        <td>
          <code>
            import IconReload from 'terra-icon/lib/icon/IconReload';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconRecurringEvent height='2em' width='2em' /></td>
        <td>recurringEvent</td>
        <td>
          <code>
            import IconRecurringEvent from 'terra-icon/lib/icon/IconRecurringEvent';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconSeparate height='2em' width='2em' /></td>
        <td>separate</td>
        <td>
          <code>
            import IconSeparate from 'terra-icon/lib/icon/IconSeparate';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconMerge height='2em' width='2em' /></td>
        <td>merge</td>
        <td>
          <code>
            import IconMerge from 'terra-icon/lib/icon/IconMerge';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconCompose height='2em' width='2em' /></td>
        <td>compose</td>
        <td>
          <code>
            import IconCompose from 'terra-icon/lib/icon/IconCompose';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconUnread height='2em' width='2em' /></td>
        <td>unread</td>
        <td>
          <code>
            import IconUnread from 'terra-icon/lib/icon/IconUnread';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconSwap height='2em' width='2em' /></td>
        <td>swap</td>
        <td>
          <code>
            import IconSwap from 'terra-icon/lib/icon/IconSwap';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconMicrophone height='2em' width='2em' /></td>
        <td>microphone</td>
        <td>
          <code>
            import IconMicrophone from 'terra-icon/lib/icon/IconMicrophone';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconMicrophoneDisabled height='2em' width='2em' /></td>
        <td>microphoneDisabled</td>
        <td>
          <code>
            import IconMicrophoneDisabled from 'terra-icon/lib/icon/IconMicrophoneDisabled';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconOutgoingCall height='2em' width='2em' /></td>
        <td>outgoingCall</td>
        <td>
          <code>
            import IconOutgoingCall from 'terra-icon/lib/icon/IconOutgoingCall';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconIncomingCall height='2em' width='2em' /></td>
        <td>incomingCall</td>
        <td>
          <code>
            import IconIncomingCall from 'terra-icon/lib/icon/IconIncomingCall';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconMissedCall height='2em' width='2em' /></td>
        <td>missedCall</td>
        <td>
          <code>
            import IconMissedCall from 'terra-icon/lib/icon/IconMissedCall';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPinDown height='2em' width='2em' /></td>
        <td>pinDown</td>
        <td>
          <code>
            import IconPinDown from 'terra-icon/lib/icon/IconPinDown';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPinDiagonal height='2em' width='2em' /></td>
        <td>pinDiagonal</td>
        <td>
          <code>
            import IconPinDiagonal from 'terra-icon/lib/icon/IconPinDiagonal';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPause height='2em' width='2em' /></td>
        <td>pause</td>
        <td>
          <code>
            import IconPause from 'terra-icon/lib/icon/IconPause';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconAudio height='2em' width='2em' /></td>
        <td>audio</td>
        <td>
          <code>
            import IconAudio from 'terra-icon/lib/icon/IconAudio';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconExternalLink height='2em' width='2em' /></td>
        <td>externalLink</td>
        <td>
          <code>
            import IconExternalLink from 'terra-icon/lib/icon/IconExternalLink';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconBedRequested height='2em' width='2em' /></td>
        <td>bedRequested</td>
        <td>
          <code>
            import IconBedRequested from 'terra-icon/lib/icon/IconBedRequested';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconFlipVertical height='2em' width='2em' /></td>
        <td>flipVertical</td>
        <td>
          <code>
            import IconFlipVertical from 'terra-icon/lib/icon/IconFlipVertical';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconFlipHorizontal height='2em' width='2em' /></td>
        <td>flipHorizontal</td>
        <td>
          <code>
            import IconFlipHorizontal from 'terra-icon/lib/icon/IconFlipHorizontal';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconRotateLeft height='2em' width='2em' /></td>
        <td>rotateLeft</td>
        <td>
          <code>
            import IconRotateLeft from 'terra-icon/lib/icon/IconRotateLeft';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconRotateRight height='2em' width='2em' /></td>
        <td>rotateRight</td>
        <td>
          <code>
            import IconRotateRight from 'terra-icon/lib/icon/IconRotateRight';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconHold height='2em' width='2em' /></td>
        <td>hold</td>
        <td>
          <code>
            import IconHold from 'terra-icon/lib/icon/IconHold';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconFitWidth height='2em' width='2em' /></td>
        <td>fitWidth</td>
        <td>
          <code>
            import IconFitWidth from 'terra-icon/lib/icon/IconFitWidth';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconFitScale height='2em' width='2em' /></td>
        <td>fitScale</td>
        <td>
          <code>
            import IconFitScale from 'terra-icon/lib/icon/IconFitScale';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconSecondaryProvider height='2em' width='2em' /></td>
        <td>secondaryProvider</td>
        <td>
          <code>
            import IconSecondaryProvider from 'terra-icon/lib/icon/IconSecondaryProvider';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPartiallyMet height='2em' width='2em' /></td>
        <td>partiallyMet</td>
        <td>
          <code>
            import IconPartiallyMet from 'terra-icon/lib/icon/IconPartiallyMet';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconSimulation height='2em' width='2em' /></td>
        <td>simulation</td>
        <td>
          <code>
            import IconSimulation from 'terra-icon/lib/icon/IconSimulation';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconCollapseRow height='2em' width='2em' /></td>
        <td>collapseRow</td>
        <td>
          <code>
            import IconCollapseRow from 'terra-icon/lib/icon/IconCollapseRow';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconExpandRow height='2em' width='2em' /></td>
        <td>expandRow</td>
        <td>
          <code>
            import IconExpandRow from 'terra-icon/lib/icon/IconExpandRow';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconDoubleChevronLeft height='2em' width='2em' /></td>
        <td>doubleChevronLeft</td>
        <td>
          <code>
            import IconDoubleChevronLeft from 'terra-icon/lib/icon/IconDoubleChevronLeft';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconDoubleChevronRight height='2em' width='2em' /></td>
        <td>doubleChevronRight</td>
        <td>
          <code>
            import IconDoubleChevronRight from 'terra-icon/lib/icon/IconDoubleChevronRight';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconCircleSymbol height='2em' width='2em' /></td>
        <td>circle_symbol</td>
        <td>
          <code>
            import IconCircleSymbol from 'terra-icon/lib/icon/IconCircleSymbol';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconDiamondSymbol height='2em' width='2em' /></td>
        <td>diamond_symbol</td>
        <td>
          <code>
            import IconDiamondSymbol from 'terra-icon/lib/icon/IconDiamondSymbol';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconPlusSymbol height='2em' width='2em' /></td>
        <td>plus_symbol</td>
        <td>
          <code>
            import IconPlusSymbol from 'terra-icon/lib/icon/IconPlusSymbol';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconRectangleSymbol height='2em' width='2em' /></td>
        <td>rectangle_symbol</td>
        <td>
          <code>
            import IconRectangleSymbol from 'terra-icon/lib/icon/IconRectangleSymbol';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconSquareSymbol height='2em' width='2em' /></td>
        <td>square_symbol</td>
        <td>
          <code>
            import IconSquareSymbol from 'terra-icon/lib/icon/IconSquareSymbol';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconTeardropSymbol height='2em' width='2em' /></td>
        <td>teardrop_symbol</td>
        <td>
          <code>
            import IconTeardropSymbol from 'terra-icon/lib/icon/IconTeardropSymbol';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconTeardropUpSymbol height='2em' width='2em' /></td>
        <td>teardropUp_symbol</td>
        <td>
          <code>
            import IconTeardropUpSymbol from 'terra-icon/lib/icon/IconTeardropUpSymbol';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconThinDiamondSymbol height='2em' width='2em' /></td>
        <td>thinDiamond_symbol</td>
        <td>
          <code>
            import IconThinDiamondSymbol from 'terra-icon/lib/icon/IconThinDiamondSymbol';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconTriangleSymbol height='2em' width='2em' /></td>
        <td>triangle_symbol</td>
        <td>
          <code>
            import IconTriangleSymbol from 'terra-icon/lib/icon/IconTriangleSymbol';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconTriangleDownSymbol height='2em' width='2em' /></td>
        <td>triangleDown_symbol</td>
        <td>
          <code>
            import IconTriangleDownSymbol from 'terra-icon/lib/icon/IconTriangleDownSymbol';
          </code>
        </td>
      </tr>
      <tr>
        <td><IconXSymbol height='2em' width='2em' /></td>
        <td>x_symbol</td>
        <td>
          <code>
            import IconXSymbol from 'terra-icon/lib/icon/IconXSymbol';
          </code>
        </td>
      </tr>
    </tbody>
  </table>
);

export default IconThemeable;
