import fs from 'fs';

const outputfile = fs.createWriteStream('../../packages/terra-site/src/examples/icon/IconAll.jsx', { flags: 'w' });

const generateIconAll = iconObjs => new Promise((resolve) => {
  outputfile.write('// This file is autogenerated from scripts/src/generate-example\n');
  outputfile.write('/* eslint-disable import/no-duplicates */\n');
  outputfile.write('import React from \'react\';\n');

  iconObjs.forEach((iconObj) => {
    outputfile.write(iconObj.syntaxImport);
  });
  outputfile.write('/* eslint-enable import/no-duplicates */\n');

  outputfile.write('const IconAll = () => (\n');
  outputfile.write('  <div>\n');
  iconObjs.forEach((iconObj) => {
    outputfile.write('    <div>\n');
    outputfile.write(`      ${iconObj.syntaxComponent}\n`);
    outputfile.write(`      ${iconObj.name}\n`);
    outputfile.write('    </div>\n');
  });
  outputfile.write('  </div>\n');
  outputfile.write(');\n\n');

  outputfile.write('export default IconAll;\n');

  resolve(iconObjs);
});

export default generateIconAll;
