/* eslint-disable */
import fs from 'fs';

const outputfile = fs.createWriteStream('../../packages/terra-icon/src/terra-dev-site/doc/example/IconThemeable.jsx', { flags: 'w' });

const generateIconThemeable = iconObjs => new Promise((resolve) => {

  const themeableIcons = iconObjs.filter(function(iconObj){
    if (iconObj.themeable) {
      return iconObj;
    }
  });

  outputfile.write('// This file is autogenerated from scripts/src/generate-example\n');
  outputfile.write('/* eslint-disable */\n');
  outputfile.write('import React from \'react\';\n');
  themeableIcons.forEach((iconObj) => {
    outputfile.write(iconObj.syntaxImport);
  });
  outputfile.write('import \'./IconTable.scss\';\n\n');

  outputfile.write('const IconThemeable = () => (\n');
  outputfile.write('  <table className="icon-table">\n');

  outputfile.write('    <thead>\n');
  outputfile.write('      <tr>\n');
  outputfile.write(`        <th>SVG</th>\n`);
  outputfile.write(`        <th>Concept</th>\n`);
  outputfile.write(`        <th>Code</th>\n`);
  outputfile.write('      </tr>\n');
  outputfile.write('    </thead>\n');

  outputfile.write('    <tbody>\n');
  themeableIcons.forEach((iconObj) => {
    outputfile.write(`      <tr>\n`);
    outputfile.write(`        <td>${iconObj.syntaxComponent}</td>\n`);
    outputfile.write(`        <td>${iconObj.name}</td>\n`);
    outputfile.write(`        <td>\n`);
    outputfile.write('          <code>\n');
    outputfile.write(`            ${iconObj.syntaxImport}`);
    outputfile.write('          </code>\n');
    outputfile.write('        </td>\n');
    outputfile.write('      </tr>\n');
  });
  outputfile.write('    </tbody>\n');

  outputfile.write('  </table>\n');
  outputfile.write(');\n\n');

  outputfile.write('export default IconThemeable;\n');

  resolve(iconObjs);
});

export default generateIconThemeable;
