/* eslint-disable import/no-extraneous-dependencies */
import React from 'react';
import PropTypes from 'prop-types';
import { parse } from 'react-docgen';
import Markdown from 'terra-markdown';

const propTypes = {
  /**
   * markdown file
   */
  src: PropTypes.string.isRequired,
};

/**
 * Renders a table view for the props metadata of a react component generated by react-docgen
 */
const PropsTable = ({ src, ...customProps }) => {
  /**
   * Runs component source code through react-docgen
   * @type {Object}
   */
  const componentMetaData = parse(src);

  /**
   * Alias for props object from componentMetaData
   * @type {Object}
   */
  const componentProps = componentMetaData.props;

  return (
    <div dir="ltr" className="markdown-body">
      <h2>Props</h2>
      <table {...customProps}>
        <thead>
          <tr>
            <th>Prop Name</th>
            <th>Type</th>
            <th>Is Required</th>
            <th>Default Value</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          {Object.keys(componentProps).map((key) => {
            const prop = componentProps[key];
            let type = prop.type.name;

            // Pull the first value off and use that as type.
            // This assumes all enumerable values are the same type.
            if (type === 'enum') {
              if (isNaN(prop.type.value[0].value)) {
                type = typeof prop.type.value[0].value;
              } else {
                type = 'number';
              }
            }

            return (
              <tr key={key} style={{ fontSize: '90%' }}>
                <td style={{ fontWeight: 'bold' }}>{key}</td>
                <td>{(prop.type ? type : '')}</td>
                {(prop.required ?
                  <td style={{ color: '#d53700' }}>required</td>
              : <td style={{ color: '#444' }}>optional</td>)}
                {(prop.defaultValue ?
                  <td style={{ fontWeight: 'bold' }}>{prop.defaultValue.value}</td>
              : <td style={{ color: '#444' }}>none</td>)}
                <td><Markdown src={prop.description} /></td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
};

PropsTable.propTypes = propTypes;

export default PropsTable;
