// This file is autogenerated from scripts/src/generate-example
import React from 'react';
import IconHospital from '../../../lib/icon/IconHospital';

const IconAria = () => (
  <div>
    <h3>No aria-label</h3>
    <p>If ariaLabel is null: </p>
    <ul>
      <li>{'aria-hidden="true"'}</li>
    </ul>
    <IconHospital />
    <h4>Set aria-label to Hospital</h4>
    <p>If ariaLabel is not null: </p>
    <ul>
      <li>{'aria-hidden="false"'}</li>
      <li>{'role="img"'}</li>
    </ul>
    <IconHospital ariaLabel="Hospital" />
  </div>
);

export default IconAria;
