import React from 'react';
import classNames from 'classnames/bind';
import Icon from 'terra-icon/lib/IconExports';
import styles from './IconAll.module.scss';

const cx = classNames.bind(styles);

const IconAll = () => (
  <div>
    <Icon.IconAbnormal height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconAbnormalLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconAdd height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconAddPerson height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconAlert height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconAlertLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconAllergy height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconAnalytics height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconAnnouncement height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconArchive height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconAttachment height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconAudio height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconAutoText height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconAvailable height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconAway height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconBedAssigned height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconBedAssignedLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconBedRequested height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconBluetooth height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconBluetoothSlash height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconBookmark height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconBriefcase height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconBrokenImage height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconBrokenLinkUnlink height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconBusy height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCalculator height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCalendar height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCamera height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCancel height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCaretDown height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCaretLeft height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCaretRight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCaretUp height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCatalogueNumber height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCaution height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconChecklist height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCheckmark height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconChevron height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconChevronDown height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconChevronLeft height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconChevronRight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconChevronUp height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCircleLinesSymbol height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCircleSymbol height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCircleSymbolLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconClear height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconClipboard height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconClock height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconClose height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCollapseRow height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconComment height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCommit height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconComplete height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCompose height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconConfidential height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconConsultInstructionsForUse height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCritical height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCriticalInverse height="40px" width="40px" className={cx(['icon', 'icon-inverse'])} />
    <Icon.IconCriticalInverseLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconCriticalLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDateOfManufacture height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDevice height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDeviceAlert height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDeviceAlertLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDeviceCheck height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDeviceCheckLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDiamond height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDiamondLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDiamondSymbol height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDiamondSymbolLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDischargeComingDue height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDischargeComingDueLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDischargeComplete height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDischargeCompleteLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDischargeOverDue height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDischargeOverDueLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDocumentPlus height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDocuments height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDoNotDisturb height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDoorOpen height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDoubleChevronLeft height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDoubleChevronRight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDown height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDownload height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDrugDrug height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDrugDrugLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDue height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDueSoon height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconDueSoonLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconEcRep height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconEdit height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconEllipses height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconEnvelope height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconEnvelopeFill height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconError height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconErrorDark height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconErrorLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconExclamation height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconExpandLess height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconExpandMore height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconExpandRow height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconExtensions height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconExternalLink height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconFeatured height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconFeaturedOff height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconFeaturedOutline height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconFeaturedOutlineYellow height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconFirst height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconFitHeight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconFitScale height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconFitWidth height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconFlag height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconFlipHorizontal height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconFlipVertical height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconFlowsheet height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconFolder height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconForward height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconFunnel height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconGapChecking height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconGlasses height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconGroup height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconHalfRating height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconHazardLow height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconHelp height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconHelpInverse height="40px" width="40px" className={cx(['icon', 'icon-inverse'])} />
    <Icon.IconHelpInverseLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconHelpLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconHide height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconHigh height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconHighInverse height="40px" width="40px" className={cx(['icon', 'icon-inverse'])} />
    <Icon.IconHighInverseLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconHighLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconHighPriority height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconHold height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconHospital height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconHouse height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconImage height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconImplant height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconIncomingCall height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconIncomplete height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconIncompleteInverse height="40px" width="40px" className={cx(['icon', 'icon-inverse'])} />
    <Icon.IconIncompleteInverseLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconInformation height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconInformationInverse height="40px" width="40px" className={cx(['icon', 'icon-inverse'])} />
    <Icon.IconInformationInverseLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconInformationLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconIPass height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconItalicI height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconKeyboard height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconKnurling height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconLast height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconLeft height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconLeftPane height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconLightbulb height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconLink height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconList height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconLocationPin height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconLookback height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconLow height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconLowLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconLowRisk height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconLowRiskLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconManufacturer height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMax height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMaximize height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMediaFastForward height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMediaPause height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMediaPlay height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMediaRecord height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMediaRewind height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMediaStop height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMedicationTablet height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMedicationTabletOutline height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMedicationTabletHalf height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMedicationTabletHalfOutline height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMenu height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMerge height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMicrophone height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMicrophoneDisabled height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMin height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMinimize height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMinus height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconMissedCall height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconModerate height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconModerateLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconModified height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconNext height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconNoRisk height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconNoRiskLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconNoSignal height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconNotification height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconNotificationDisabled height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconNotificationOff height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconNotMet height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconOutgoingCall height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconOutOfNetwork height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconOverDue height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconOverDueLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPadlock height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPager height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPanelLeft height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPanelRight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPaperFolded height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPaperPencil height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPartiallyMet height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPatientSearch height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPending height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPerson height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPersonDoor height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPersonHospital height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPersonnelPerson height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPharmacyReject height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPharmacyRejectLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPharmacyReview height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPharmacyVerification height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPhone height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPhoneDown height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPill height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPinDiagonal height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPinDown height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPlusSymbol height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPlusSymbolLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPrevious height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconPrinter height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconProjects height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconProtocol height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconProvider height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconQuestion height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconQuestionOutline height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconRectangleSymbol height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconRectangleSymbolLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconRecurringEvent height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconRedo height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconRefresh height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconRefusedSlot height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconReload height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconReply height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconReplyAll height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconRequired height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconRight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconRollup height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconRotateLeft height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconRotateRight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSave height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconScheduled height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconScheduledLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconScratchPad height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSearch height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSecondaryProvider height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSend height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSeparate height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSettings height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSharedSchedules height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSimulation height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSortAscending height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSortDescending height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSpinner height="40px" width="40px" className={cx(['icon'])} isSpin={false} />
    <Icon.IconSquareSymbol height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSquareSymbolLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconStatusPositive height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconStatusPositiveWhite height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconStatusPositiveLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconStatusPositiveWhiteLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconStartPresenting height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconStopPresenting height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSuccess height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSuccessInverse height="40px" width="40px" className={cx(['icon', 'icon-inverse'])} />
    <Icon.IconSuccessInverseLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSuccessLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconSwap height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconTable height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconTag height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconTeardropSymbol height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconTeardropSymbolLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconTeardropUpSymbol height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconTeardropUpSymbolLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconThinDiamondSymbol height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconThinDiamondSymbolLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconTile height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconTrash height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconTreemap height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconTriangleDownSymbol height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconTriangleDownSymbolLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconTriangleSymbol height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconTriangleSymbolLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconTrophy height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconUnavailable height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconUndo height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconUnexpected height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconUnexpectedLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconUnknown height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconUnlock height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconUnread height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconUnspecified height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconUp height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconUpload height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconUsers height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconVideoCamera height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconVideoCameraDisabled height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconVisualization height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconWarning height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconWarningLowLight height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconWaveform height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconWifi height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconWifiSlash height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconXSymbol height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconZoomIn height="40px" width="40px" className={cx(['icon'])} />
    <Icon.IconZoomOut height="40px" width="40px" className={cx(['icon'])} />
  </div>
);

export default IconAll;
