// This file is autogenerated from scripts/src/generate-example
/* eslint-disable import/no-duplicates */
import React from 'react';
import IconAdd from 'terra-icon/src/icon/IconAdd';
import IconSearch from 'terra-icon/src/icon/IconSearch';
import IconCommit from 'terra-icon/src/icon/IconCommit';
import IconCheckmark from 'terra-icon/src/icon/IconCheckmark';
import IconSuccess from 'terra-icon/src/icon/IconSuccess';
import IconSuccessInverse from 'terra-icon/src/icon/IconSuccessInverse';
import IconAvailable from 'terra-icon/src/icon/IconAvailable';
import IconComplete from 'terra-icon/src/icon/IconComplete';
import IconTrash from 'terra-icon/src/icon/IconTrash';
import IconPaperFolded from 'terra-icon/src/icon/IconPaperFolded';
import IconPrinter from 'terra-icon/src/icon/IconPrinter';
import IconComment from 'terra-icon/src/icon/IconComment';
import IconBookmark from 'terra-icon/src/icon/IconBookmark';
import IconModified from 'terra-icon/src/icon/IconModified';
import IconFirst from 'terra-icon/src/icon/IconFirst';
import IconFolder from 'terra-icon/src/icon/IconFolder';
import IconAttachment from 'terra-icon/src/icon/IconAttachment';
import IconSend from 'terra-icon/src/icon/IconSend';
import IconPill from 'terra-icon/src/icon/IconPill';
import IconCritical from 'terra-icon/src/icon/IconCritical';
import IconVisualization from 'terra-icon/src/icon/IconVisualization';
import IconLightbulb from 'terra-icon/src/icon/IconLightbulb';
import IconForward from 'terra-icon/src/icon/IconForward';
import IconProjects from 'terra-icon/src/icon/IconProjects';
import IconReplyAll from 'terra-icon/src/icon/IconReplyAll';
import IconFlag from 'terra-icon/src/icon/IconFlag';
import IconCalculator from 'terra-icon/src/icon/IconCalculator';
import IconCaretRight from 'terra-icon/src/icon/IconCaretRight';
import IconCaretLeft from 'terra-icon/src/icon/IconCaretLeft';
import IconCaretUp from 'terra-icon/src/icon/IconCaretUp';
import IconCaretDown from 'terra-icon/src/icon/IconCaretDown';
import IconScheduled from 'terra-icon/src/icon/IconScheduled';
import IconTrophy from 'terra-icon/src/icon/IconTrophy';
import IconChevronLeft from 'terra-icon/src/icon/IconChevronLeft';
import IconPrevious from 'terra-icon/src/icon/IconPrevious';
import IconChevronRight from 'terra-icon/src/icon/IconChevronRight';
import IconNext from 'terra-icon/src/icon/IconNext';
import IconChevronUp from 'terra-icon/src/icon/IconChevronUp';
import IconExpandLess from 'terra-icon/src/icon/IconExpandLess';
import IconChevron from 'terra-icon/src/icon/IconChevron';
import IconChevronDown from 'terra-icon/src/icon/IconChevronDown';
import IconExpandMore from 'terra-icon/src/icon/IconExpandMore';
import IconClock from 'terra-icon/src/icon/IconClock';
import IconAway from 'terra-icon/src/icon/IconAway';
import IconSortAscending from 'terra-icon/src/icon/IconSortAscending';
import IconSortDescending from 'terra-icon/src/icon/IconSortDescending';
import IconTreemap from 'terra-icon/src/icon/IconTreemap';
import IconGlasses from 'terra-icon/src/icon/IconGlasses';
import IconImage from 'terra-icon/src/icon/IconImage';
import IconDoorOpen from 'terra-icon/src/icon/IconDoorOpen';
import IconEllipses from 'terra-icon/src/icon/IconEllipses';
import IconExclamation from 'terra-icon/src/icon/IconExclamation';
import IconHighPriority from 'terra-icon/src/icon/IconHighPriority';
import IconAlert from 'terra-icon/src/icon/IconAlert';
import IconWarning from 'terra-icon/src/icon/IconWarning';
import IconItalicI from 'terra-icon/src/icon/IconItalicI';
import IconInformation from 'terra-icon/src/icon/IconInformation';
import IconInformationInverse from 'terra-icon/src/icon/IconInformationInverse';
import IconMinus from 'terra-icon/src/icon/IconMinus';
import IconError from 'terra-icon/src/icon/IconError';
import IconDoNotDisturb from 'terra-icon/src/icon/IconDoNotDisturb';
import IconClose from 'terra-icon/src/icon/IconClose';
import IconClear from 'terra-icon/src/icon/IconClear';
import IconNotMet from 'terra-icon/src/icon/IconNotMet';
import IconIncomplete from 'terra-icon/src/icon/IconIncomplete';
import IconPerson from 'terra-icon/src/icon/IconPerson';
import IconLeft from 'terra-icon/src/icon/IconLeft';
import IconRight from 'terra-icon/src/icon/IconRight';
import IconUp from 'terra-icon/src/icon/IconUp';
import IconDown from 'terra-icon/src/icon/IconDown';
import IconSettings from 'terra-icon/src/icon/IconSettings';
import IconEdit from 'terra-icon/src/icon/IconEdit';
import IconCalendar from 'terra-icon/src/icon/IconCalendar';
import IconLookback from 'terra-icon/src/icon/IconLookback';
import IconRefresh from 'terra-icon/src/icon/IconRefresh';
import IconProvider from 'terra-icon/src/icon/IconProvider';
import IconPadlock from 'terra-icon/src/icon/IconPadlock';
import IconFeatured from 'terra-icon/src/icon/IconFeatured';
import IconArchive from 'terra-icon/src/icon/IconArchive';
import IconFunnel from 'terra-icon/src/icon/IconFunnel';
import IconDocuments from 'terra-icon/src/icon/IconDocuments';
import IconHelp from 'terra-icon/src/icon/IconHelp';
import IconHelpInverse from 'terra-icon/src/icon/IconHelpInverse';
import IconUnknown from 'terra-icon/src/icon/IconUnknown';
import IconHouse from 'terra-icon/src/icon/IconHouse';
import IconSave from 'terra-icon/src/icon/IconSave';
import IconHospital from 'terra-icon/src/icon/IconHospital';
import IconPending from 'terra-icon/src/icon/IconPending';
import IconAnalytics from 'terra-icon/src/icon/IconAnalytics';
import IconAnnouncement from 'terra-icon/src/icon/IconAnnouncement';
import IconCamera from 'terra-icon/src/icon/IconCamera';
import IconBriefcase from 'terra-icon/src/icon/IconBriefcase';
import IconLink from 'terra-icon/src/icon/IconLink';
import IconList from 'terra-icon/src/icon/IconList';
import IconMenu from 'terra-icon/src/icon/IconMenu';
import IconChecklist from 'terra-icon/src/icon/IconChecklist';
import IconUnlock from 'terra-icon/src/icon/IconUnlock';
import IconDue from 'terra-icon/src/icon/IconDue';
import IconDueSoon from 'terra-icon/src/icon/IconDueSoon';
import IconSpinner from 'terra-icon/src/icon/IconSpinner';
import IconTile from 'terra-icon/src/icon/IconTile';
import IconOverDue from 'terra-icon/src/icon/IconOverDue';
import IconUsers from 'terra-icon/src/icon/IconUsers';
import IconKnurling from 'terra-icon/src/icon/IconKnurling';
import IconAddPerson from 'terra-icon/src/icon/IconAddPerson';
import IconUpload from 'terra-icon/src/icon/IconUpload';
import IconDownload from 'terra-icon/src/icon/IconDownload';
import IconCancel from 'terra-icon/src/icon/IconCancel';
import IconMaximize from 'terra-icon/src/icon/IconMaximize';
import IconMinimize from 'terra-icon/src/icon/IconMinimize';
import IconReply from 'terra-icon/src/icon/IconReply';
import IconTable from 'terra-icon/src/icon/IconTable';
import IconRequired from 'terra-icon/src/icon/IconRequired';
import IconGapChecking from 'terra-icon/src/icon/IconGapChecking';
import IconPersonHospital from 'terra-icon/src/icon/IconPersonHospital';
import IconPersonnelPerson from 'terra-icon/src/icon/IconPersonnelPerson';
import IconHigh from 'terra-icon/src/icon/IconHigh';
import IconLow from 'terra-icon/src/icon/IconLow';
import IconMax from 'terra-icon/src/icon/IconMax';
import IconMin from 'terra-icon/src/icon/IconMin';
import IconAbnormal from 'terra-icon/src/icon/IconAbnormal';
import IconLeftPane from 'terra-icon/src/icon/IconLeftPane';
import IconFlowsheet from 'terra-icon/src/icon/IconFlowsheet';
import IconNotification from 'terra-icon/src/icon/IconNotification';
import IconLast from 'terra-icon/src/icon/IconLast';
import IconDevice from 'terra-icon/src/icon/IconDevice';
import IconDeviceCheck from 'terra-icon/src/icon/IconDeviceCheck';
import IconDeviceAlert from 'terra-icon/src/icon/IconDeviceAlert';
import IconPaperPencil from 'terra-icon/src/icon/IconPaperPencil';
import IconClipboard from 'terra-icon/src/icon/IconClipboard';
import IconZoomOut from 'terra-icon/src/icon/IconZoomOut';
import IconZoomIn from 'terra-icon/src/icon/IconZoomIn';
import IconDiamond from 'terra-icon/src/icon/IconDiamond';
import IconEnvelope from 'terra-icon/src/icon/IconEnvelope';
import IconAllergy from 'terra-icon/src/icon/IconAllergy';
import IconPhone from 'terra-icon/src/icon/IconPhone';
import IconPanelLeft from 'terra-icon/src/icon/IconPanelLeft';
import IconPanelRight from 'terra-icon/src/icon/IconPanelRight';
import IconTag from 'terra-icon/src/icon/IconTag';
import IconIPass from 'terra-icon/src/icon/IconIPass';
import IconScratchPad from 'terra-icon/src/icon/IconScratchPad';
import IconPharmacyReview from 'terra-icon/src/icon/IconPharmacyReview';
import IconPharmacyReject from 'terra-icon/src/icon/IconPharmacyReject';
import IconBusy from 'terra-icon/src/icon/IconBusy';
import IconUnavailable from 'terra-icon/src/icon/IconUnavailable';
import IconImplant from 'terra-icon/src/icon/IconImplant';
/* eslint-enable import/no-duplicates */
const IconAll = () => (
  <div>
    <div>
      <IconAdd />
      add
    </div>
    <div>
      <IconSearch />
      search
    </div>
    <div>
      <IconCommit />
      commit
    </div>
    <div>
      <IconCheckmark />
      checkmark
    </div>
    <div>
      <IconSuccess />
      success
    </div>
    <div>
      <IconSuccessInverse />
      success_inverse
    </div>
    <div>
      <IconAvailable />
      available
    </div>
    <div>
      <IconComplete />
      complete
    </div>
    <div>
      <IconTrash />
      trash
    </div>
    <div>
      <IconPaperFolded />
      paperFolded
    </div>
    <div>
      <IconPrinter />
      printer
    </div>
    <div>
      <IconComment />
      comment
    </div>
    <div>
      <IconBookmark />
      bookmark
    </div>
    <div>
      <IconModified />
      modified
    </div>
    <div>
      <IconFirst />
      first
    </div>
    <div>
      <IconFolder />
      folder
    </div>
    <div>
      <IconAttachment />
      attachment
    </div>
    <div>
      <IconSend />
      send
    </div>
    <div>
      <IconPill />
      pill
    </div>
    <div>
      <IconCritical />
      critical
    </div>
    <div>
      <IconVisualization />
      visualization
    </div>
    <div>
      <IconLightbulb />
      lightbulb
    </div>
    <div>
      <IconForward />
      forward
    </div>
    <div>
      <IconProjects />
      projects
    </div>
    <div>
      <IconReplyAll />
      replyAll
    </div>
    <div>
      <IconFlag />
      flag
    </div>
    <div>
      <IconCalculator />
      calculator
    </div>
    <div>
      <IconCaretRight />
      caretRight
    </div>
    <div>
      <IconCaretLeft />
      caretLeft
    </div>
    <div>
      <IconCaretUp />
      caretUp
    </div>
    <div>
      <IconCaretDown />
      caretDown
    </div>
    <div>
      <IconScheduled />
      scheduled
    </div>
    <div>
      <IconTrophy />
      trophy
    </div>
    <div>
      <IconChevronLeft />
      chevronLeft
    </div>
    <div>
      <IconPrevious />
      previous
    </div>
    <div>
      <IconChevronRight />
      chevronRight
    </div>
    <div>
      <IconNext />
      next
    </div>
    <div>
      <IconChevronUp />
      chevronUp
    </div>
    <div>
      <IconExpandLess />
      expandLess
    </div>
    <div>
      <IconChevron />
      chevron
    </div>
    <div>
      <IconChevronDown />
      chevronDown
    </div>
    <div>
      <IconExpandMore />
      expandMore
    </div>
    <div>
      <IconClock />
      clock
    </div>
    <div>
      <IconAway />
      away
    </div>
    <div>
      <IconSortAscending />
      sortAscending
    </div>
    <div>
      <IconSortDescending />
      sortDescending
    </div>
    <div>
      <IconTreemap />
      treemap
    </div>
    <div>
      <IconGlasses />
      glasses
    </div>
    <div>
      <IconImage />
      image
    </div>
    <div>
      <IconDoorOpen />
      doorOpen
    </div>
    <div>
      <IconEllipses />
      ellipses
    </div>
    <div>
      <IconExclamation />
      exclamation
    </div>
    <div>
      <IconHighPriority />
      highPriority
    </div>
    <div>
      <IconAlert />
      alert
    </div>
    <div>
      <IconWarning />
      warning
    </div>
    <div>
      <IconItalicI />
      italic-i
    </div>
    <div>
      <IconInformation />
      information
    </div>
    <div>
      <IconInformationInverse />
      information_inverse
    </div>
    <div>
      <IconMinus />
      minus
    </div>
    <div>
      <IconError />
      error
    </div>
    <div>
      <IconDoNotDisturb />
      doNotDisturb
    </div>
    <div>
      <IconClose />
      close
    </div>
    <div>
      <IconClear />
      clear
    </div>
    <div>
      <IconNotMet />
      notMet
    </div>
    <div>
      <IconIncomplete />
      incomplete
    </div>
    <div>
      <IconPerson />
      person
    </div>
    <div>
      <IconLeft />
      left
    </div>
    <div>
      <IconRight />
      right
    </div>
    <div>
      <IconUp />
      up
    </div>
    <div>
      <IconDown />
      down
    </div>
    <div>
      <IconSettings />
      settings
    </div>
    <div>
      <IconEdit />
      edit
    </div>
    <div>
      <IconCalendar />
      calendar
    </div>
    <div>
      <IconLookback />
      lookback
    </div>
    <div>
      <IconRefresh />
      refresh
    </div>
    <div>
      <IconProvider />
      provider
    </div>
    <div>
      <IconPadlock />
      padlock
    </div>
    <div>
      <IconFeatured />
      featured
    </div>
    <div>
      <IconArchive />
      archive
    </div>
    <div>
      <IconFunnel />
      funnel
    </div>
    <div>
      <IconDocuments />
      documents
    </div>
    <div>
      <IconHelp />
      help
    </div>
    <div>
      <IconHelpInverse />
      help_inverse
    </div>
    <div>
      <IconUnknown />
      unknown
    </div>
    <div>
      <IconHouse />
      house
    </div>
    <div>
      <IconSave />
      save
    </div>
    <div>
      <IconHospital />
      hospital
    </div>
    <div>
      <IconPending />
      pending
    </div>
    <div>
      <IconAnalytics />
      analytics
    </div>
    <div>
      <IconAnnouncement />
      announcement
    </div>
    <div>
      <IconCamera />
      camera
    </div>
    <div>
      <IconBriefcase />
      briefcase
    </div>
    <div>
      <IconLink />
      link
    </div>
    <div>
      <IconList />
      list
    </div>
    <div>
      <IconMenu />
      menu
    </div>
    <div>
      <IconChecklist />
      checklist
    </div>
    <div>
      <IconUnlock />
      unlock
    </div>
    <div>
      <IconDue />
      due
    </div>
    <div>
      <IconDueSoon />
      dueSoon
    </div>
    <div>
      <IconSpinner />
      spinner
    </div>
    <div>
      <IconTile />
      tile
    </div>
    <div>
      <IconOverDue />
      overDue
    </div>
    <div>
      <IconUsers />
      users
    </div>
    <div>
      <IconKnurling />
      knurling
    </div>
    <div>
      <IconAddPerson />
      addPerson
    </div>
    <div>
      <IconUpload />
      upload
    </div>
    <div>
      <IconDownload />
      download
    </div>
    <div>
      <IconCancel />
      cancel
    </div>
    <div>
      <IconMaximize />
      maximize
    </div>
    <div>
      <IconMinimize />
      minimize
    </div>
    <div>
      <IconReply />
      reply
    </div>
    <div>
      <IconTable />
      table
    </div>
    <div>
      <IconRequired />
      required
    </div>
    <div>
      <IconGapChecking />
      gap checking
    </div>
    <div>
      <IconPersonHospital />
      personHospital
    </div>
    <div>
      <IconPersonnelPerson />
      personnelPerson
    </div>
    <div>
      <IconHigh />
      high
    </div>
    <div>
      <IconLow />
      low
    </div>
    <div>
      <IconMax />
      max
    </div>
    <div>
      <IconMin />
      min
    </div>
    <div>
      <IconAbnormal />
      abnormal
    </div>
    <div>
      <IconLeftPane />
      leftPane
    </div>
    <div>
      <IconFlowsheet />
      flowsheet
    </div>
    <div>
      <IconNotification />
      notification
    </div>
    <div>
      <IconLast />
      last
    </div>
    <div>
      <IconDevice />
      device
    </div>
    <div>
      <IconDeviceCheck />
      deviceCheck
    </div>
    <div>
      <IconDeviceAlert />
      deviceAlert
    </div>
    <div>
      <IconPaperPencil />
      paperPencil
    </div>
    <div>
      <IconClipboard />
      clipboard
    </div>
    <div>
      <IconZoomOut />
      zoomOut
    </div>
    <div>
      <IconZoomIn />
      zoomIn
    </div>
    <div>
      <IconDiamond />
      diamond
    </div>
    <div>
      <IconEnvelope />
      envelope
    </div>
    <div>
      <IconAllergy />
      allergy
    </div>
    <div>
      <IconPhone />
      phone
    </div>
    <div>
      <IconPanelLeft />
      panelLeft
    </div>
    <div>
      <IconPanelRight />
      panelRight
    </div>
    <div>
      <IconTag />
      tag
    </div>
    <div>
      <IconIPass />
      iPass
    </div>
    <div>
      <IconScratchPad />
      scratchPad
    </div>
    <div>
      <IconPharmacyReview />
      pharmacyReview
    </div>
    <div>
      <IconPharmacyReject />
      pharmacyReject
    </div>
    <div>
      <IconBusy />
      busy
    </div>
    <div>
      <IconUnavailable />
      unavailable
    </div>
    <div>
      <IconImplant />
      implant
    </div>
  </div>
);

export default IconAll;
