// This file is autogenerated from scripts/src/generate-example
/* eslint-disable */
import React from 'react';
import Table from 'terra-table';
import IconAdd from 'terra-icon/lib/icon/IconAdd';
import IconSearch from 'terra-icon/lib/icon/IconSearch';
import IconCommit from 'terra-icon/lib/icon/IconCommit';
import IconCheckmark from 'terra-icon/lib/icon/IconCheckmark';
import IconTrash from 'terra-icon/lib/icon/IconTrash';
import IconPaperFolded from 'terra-icon/lib/icon/IconPaperFolded';
import IconPrinter from 'terra-icon/lib/icon/IconPrinter';
import IconComment from 'terra-icon/lib/icon/IconComment';
import IconBookmark from 'terra-icon/lib/icon/IconBookmark';
import IconModified from 'terra-icon/lib/icon/IconModified';
import IconFirst from 'terra-icon/lib/icon/IconFirst';
import IconFolder from 'terra-icon/lib/icon/IconFolder';
import IconAttachment from 'terra-icon/lib/icon/IconAttachment';
import IconSend from 'terra-icon/lib/icon/IconSend';
import IconPill from 'terra-icon/lib/icon/IconPill';
import IconVisualization from 'terra-icon/lib/icon/IconVisualization';
import IconLightbulb from 'terra-icon/lib/icon/IconLightbulb';
import IconForward from 'terra-icon/lib/icon/IconForward';
import IconProjects from 'terra-icon/lib/icon/IconProjects';
import IconReplyAll from 'terra-icon/lib/icon/IconReplyAll';
import IconFlag from 'terra-icon/lib/icon/IconFlag';
import IconCalculator from 'terra-icon/lib/icon/IconCalculator';
import IconCaretRight from 'terra-icon/lib/icon/IconCaretRight';
import IconCaretLeft from 'terra-icon/lib/icon/IconCaretLeft';
import IconCaretUp from 'terra-icon/lib/icon/IconCaretUp';
import IconCaretDown from 'terra-icon/lib/icon/IconCaretDown';
import IconTrophy from 'terra-icon/lib/icon/IconTrophy';
import IconChevronLeft from 'terra-icon/lib/icon/IconChevronLeft';
import IconPrevious from 'terra-icon/lib/icon/IconPrevious';
import IconChevronRight from 'terra-icon/lib/icon/IconChevronRight';
import IconNext from 'terra-icon/lib/icon/IconNext';
import IconChevronUp from 'terra-icon/lib/icon/IconChevronUp';
import IconExpandLess from 'terra-icon/lib/icon/IconExpandLess';
import IconChevron from 'terra-icon/lib/icon/IconChevron';
import IconChevronDown from 'terra-icon/lib/icon/IconChevronDown';
import IconExpandMore from 'terra-icon/lib/icon/IconExpandMore';
import IconClock from 'terra-icon/lib/icon/IconClock';
import IconAway from 'terra-icon/lib/icon/IconAway';
import IconSortAscending from 'terra-icon/lib/icon/IconSortAscending';
import IconSortDescending from 'terra-icon/lib/icon/IconSortDescending';
import IconTreemap from 'terra-icon/lib/icon/IconTreemap';
import IconGlasses from 'terra-icon/lib/icon/IconGlasses';
import IconImage from 'terra-icon/lib/icon/IconImage';
import IconDoorOpen from 'terra-icon/lib/icon/IconDoorOpen';
import IconEllipses from 'terra-icon/lib/icon/IconEllipses';
import IconExclamation from 'terra-icon/lib/icon/IconExclamation';
import IconItalicI from 'terra-icon/lib/icon/IconItalicI';
import IconMinus from 'terra-icon/lib/icon/IconMinus';
import IconClose from 'terra-icon/lib/icon/IconClose';
import IconClear from 'terra-icon/lib/icon/IconClear';
import IconNotMet from 'terra-icon/lib/icon/IconNotMet';
import IconIncomplete from 'terra-icon/lib/icon/IconIncomplete';
import IconPerson from 'terra-icon/lib/icon/IconPerson';
import IconLeft from 'terra-icon/lib/icon/IconLeft';
import IconRight from 'terra-icon/lib/icon/IconRight';
import IconUp from 'terra-icon/lib/icon/IconUp';
import IconDown from 'terra-icon/lib/icon/IconDown';
import IconSettings from 'terra-icon/lib/icon/IconSettings';
import IconEdit from 'terra-icon/lib/icon/IconEdit';
import IconCalendar from 'terra-icon/lib/icon/IconCalendar';
import IconLookback from 'terra-icon/lib/icon/IconLookback';
import IconRefresh from 'terra-icon/lib/icon/IconRefresh';
import IconProvider from 'terra-icon/lib/icon/IconProvider';
import IconPadlock from 'terra-icon/lib/icon/IconPadlock';
import IconFeatured from 'terra-icon/lib/icon/IconFeatured';
import IconFeaturedOutline from 'terra-icon/lib/icon/IconFeaturedOutline';
import IconArchive from 'terra-icon/lib/icon/IconArchive';
import IconFunnel from 'terra-icon/lib/icon/IconFunnel';
import IconDocuments from 'terra-icon/lib/icon/IconDocuments';
import IconUnknown from 'terra-icon/lib/icon/IconUnknown';
import IconHouse from 'terra-icon/lib/icon/IconHouse';
import IconSave from 'terra-icon/lib/icon/IconSave';
import IconHospital from 'terra-icon/lib/icon/IconHospital';
import IconPending from 'terra-icon/lib/icon/IconPending';
import IconAnalytics from 'terra-icon/lib/icon/IconAnalytics';
import IconAnnouncement from 'terra-icon/lib/icon/IconAnnouncement';
import IconCamera from 'terra-icon/lib/icon/IconCamera';
import IconBriefcase from 'terra-icon/lib/icon/IconBriefcase';
import IconLink from 'terra-icon/lib/icon/IconLink';
import IconList from 'terra-icon/lib/icon/IconList';
import IconMenu from 'terra-icon/lib/icon/IconMenu';
import IconChecklist from 'terra-icon/lib/icon/IconChecklist';
import IconUnlock from 'terra-icon/lib/icon/IconUnlock';
import IconDue from 'terra-icon/lib/icon/IconDue';
import IconSpinner from 'terra-icon/lib/icon/IconSpinner';
import IconTile from 'terra-icon/lib/icon/IconTile';
import IconUsers from 'terra-icon/lib/icon/IconUsers';
import IconKnurling from 'terra-icon/lib/icon/IconKnurling';
import IconAddPerson from 'terra-icon/lib/icon/IconAddPerson';
import IconUpload from 'terra-icon/lib/icon/IconUpload';
import IconDownload from 'terra-icon/lib/icon/IconDownload';
import IconCancel from 'terra-icon/lib/icon/IconCancel';
import IconMaximize from 'terra-icon/lib/icon/IconMaximize';
import IconMinimize from 'terra-icon/lib/icon/IconMinimize';
import IconReply from 'terra-icon/lib/icon/IconReply';
import IconTable from 'terra-icon/lib/icon/IconTable';
import IconRequired from 'terra-icon/lib/icon/IconRequired';
import IconGapChecking from 'terra-icon/lib/icon/IconGapChecking';
import IconPersonHospital from 'terra-icon/lib/icon/IconPersonHospital';
import IconPersonnelPerson from 'terra-icon/lib/icon/IconPersonnelPerson';
import IconLeftPane from 'terra-icon/lib/icon/IconLeftPane';
import IconFlowsheet from 'terra-icon/lib/icon/IconFlowsheet';
import IconNotification from 'terra-icon/lib/icon/IconNotification';
import IconLast from 'terra-icon/lib/icon/IconLast';
import IconDevice from 'terra-icon/lib/icon/IconDevice';
import IconPaperPencil from 'terra-icon/lib/icon/IconPaperPencil';
import IconClipboard from 'terra-icon/lib/icon/IconClipboard';
import IconZoomOut from 'terra-icon/lib/icon/IconZoomOut';
import IconZoomIn from 'terra-icon/lib/icon/IconZoomIn';
import IconEnvelope from 'terra-icon/lib/icon/IconEnvelope';
import IconAllergy from 'terra-icon/lib/icon/IconAllergy';
import IconPhone from 'terra-icon/lib/icon/IconPhone';
import IconPanelLeft from 'terra-icon/lib/icon/IconPanelLeft';
import IconPanelRight from 'terra-icon/lib/icon/IconPanelRight';
import IconTag from 'terra-icon/lib/icon/IconTag';
import IconIPass from 'terra-icon/lib/icon/IconIPass';
import IconScratchPad from 'terra-icon/lib/icon/IconScratchPad';
import IconPharmacyReview from 'terra-icon/lib/icon/IconPharmacyReview';
import IconBusy from 'terra-icon/lib/icon/IconBusy';
import IconUnavailable from 'terra-icon/lib/icon/IconUnavailable';
import IconImplant from 'terra-icon/lib/icon/IconImplant';
import IconProtocol from 'terra-icon/lib/icon/IconProtocol';
import IconVideoCamera from 'terra-icon/lib/icon/IconVideoCamera';
import IconNoSignal from 'terra-icon/lib/icon/IconNoSignal';
import IconReload from 'terra-icon/lib/icon/IconReload';
import IconRecurringEvent from 'terra-icon/lib/icon/IconRecurringEvent';
import IconSeparate from 'terra-icon/lib/icon/IconSeparate';
import IconMerge from 'terra-icon/lib/icon/IconMerge';
const IconAll = () => (
  <div>  <Table isStriped={false} >
    <Table.Header>
      <Table.HeaderCell content={'SVG'} key={'svg'} />
      <Table.HeaderCell content={'Concept'} key={'concept'} />
      <Table.HeaderCell content={'Code'} key={'code'} />
    </Table.Header>
    <Table.Rows>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconAdd height='2em' width='2em' /></td>
        <td>add</td>
        <td>
          import IconAdd from 'terra-icon/lib/icon/IconAdd';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconSearch height='2em' width='2em' /></td>
        <td>search</td>
        <td>
          import IconSearch from 'terra-icon/lib/icon/IconSearch';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconCommit height='2em' width='2em' /></td>
        <td>commit</td>
        <td>
          import IconCommit from 'terra-icon/lib/icon/IconCommit';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconCheckmark height='2em' width='2em' /></td>
        <td>checkmark</td>
        <td>
          import IconCheckmark from 'terra-icon/lib/icon/IconCheckmark';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconTrash height='2em' width='2em' /></td>
        <td>trash</td>
        <td>
          import IconTrash from 'terra-icon/lib/icon/IconTrash';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconPaperFolded height='2em' width='2em' /></td>
        <td>paperFolded</td>
        <td>
          import IconPaperFolded from 'terra-icon/lib/icon/IconPaperFolded';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconPrinter height='2em' width='2em' /></td>
        <td>printer</td>
        <td>
          import IconPrinter from 'terra-icon/lib/icon/IconPrinter';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconComment height='2em' width='2em' /></td>
        <td>comment</td>
        <td>
          import IconComment from 'terra-icon/lib/icon/IconComment';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconBookmark height='2em' width='2em' /></td>
        <td>bookmark</td>
        <td>
          import IconBookmark from 'terra-icon/lib/icon/IconBookmark';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconModified height='2em' width='2em' /></td>
        <td>modified</td>
        <td>
          import IconModified from 'terra-icon/lib/icon/IconModified';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconFirst height='2em' width='2em' /></td>
        <td>first</td>
        <td>
          import IconFirst from 'terra-icon/lib/icon/IconFirst';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconFolder height='2em' width='2em' /></td>
        <td>folder</td>
        <td>
          import IconFolder from 'terra-icon/lib/icon/IconFolder';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconAttachment height='2em' width='2em' /></td>
        <td>attachment</td>
        <td>
          import IconAttachment from 'terra-icon/lib/icon/IconAttachment';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconSend height='2em' width='2em' /></td>
        <td>send</td>
        <td>
          import IconSend from 'terra-icon/lib/icon/IconSend';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconPill height='2em' width='2em' /></td>
        <td>pill</td>
        <td>
          import IconPill from 'terra-icon/lib/icon/IconPill';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconVisualization height='2em' width='2em' /></td>
        <td>visualization</td>
        <td>
          import IconVisualization from 'terra-icon/lib/icon/IconVisualization';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconLightbulb height='2em' width='2em' /></td>
        <td>lightbulb</td>
        <td>
          import IconLightbulb from 'terra-icon/lib/icon/IconLightbulb';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconForward height='2em' width='2em' /></td>
        <td>forward</td>
        <td>
          import IconForward from 'terra-icon/lib/icon/IconForward';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconProjects height='2em' width='2em' /></td>
        <td>projects</td>
        <td>
          import IconProjects from 'terra-icon/lib/icon/IconProjects';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconReplyAll height='2em' width='2em' /></td>
        <td>replyAll</td>
        <td>
          import IconReplyAll from 'terra-icon/lib/icon/IconReplyAll';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconFlag height='2em' width='2em' /></td>
        <td>flag</td>
        <td>
          import IconFlag from 'terra-icon/lib/icon/IconFlag';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconCalculator height='2em' width='2em' /></td>
        <td>calculator</td>
        <td>
          import IconCalculator from 'terra-icon/lib/icon/IconCalculator';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconCaretRight height='2em' width='2em' /></td>
        <td>caretRight</td>
        <td>
          import IconCaretRight from 'terra-icon/lib/icon/IconCaretRight';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconCaretLeft height='2em' width='2em' /></td>
        <td>caretLeft</td>
        <td>
          import IconCaretLeft from 'terra-icon/lib/icon/IconCaretLeft';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconCaretUp height='2em' width='2em' /></td>
        <td>caretUp</td>
        <td>
          import IconCaretUp from 'terra-icon/lib/icon/IconCaretUp';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconCaretDown height='2em' width='2em' /></td>
        <td>caretDown</td>
        <td>
          import IconCaretDown from 'terra-icon/lib/icon/IconCaretDown';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconTrophy height='2em' width='2em' /></td>
        <td>trophy</td>
        <td>
          import IconTrophy from 'terra-icon/lib/icon/IconTrophy';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconChevronLeft height='2em' width='2em' /></td>
        <td>chevronLeft</td>
        <td>
          import IconChevronLeft from 'terra-icon/lib/icon/IconChevronLeft';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconPrevious height='2em' width='2em' /></td>
        <td>previous</td>
        <td>
          import IconPrevious from 'terra-icon/lib/icon/IconPrevious';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconChevronRight height='2em' width='2em' /></td>
        <td>chevronRight</td>
        <td>
          import IconChevronRight from 'terra-icon/lib/icon/IconChevronRight';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconNext height='2em' width='2em' /></td>
        <td>next</td>
        <td>
          import IconNext from 'terra-icon/lib/icon/IconNext';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconChevronUp height='2em' width='2em' /></td>
        <td>chevronUp</td>
        <td>
          import IconChevronUp from 'terra-icon/lib/icon/IconChevronUp';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconExpandLess height='2em' width='2em' /></td>
        <td>expandLess</td>
        <td>
          import IconExpandLess from 'terra-icon/lib/icon/IconExpandLess';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconChevron height='2em' width='2em' /></td>
        <td>chevron</td>
        <td>
          import IconChevron from 'terra-icon/lib/icon/IconChevron';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconChevronDown height='2em' width='2em' /></td>
        <td>chevronDown</td>
        <td>
          import IconChevronDown from 'terra-icon/lib/icon/IconChevronDown';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconExpandMore height='2em' width='2em' /></td>
        <td>expandMore</td>
        <td>
          import IconExpandMore from 'terra-icon/lib/icon/IconExpandMore';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconClock height='2em' width='2em' /></td>
        <td>clock</td>
        <td>
          import IconClock from 'terra-icon/lib/icon/IconClock';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconAway height='2em' width='2em' /></td>
        <td>away</td>
        <td>
          import IconAway from 'terra-icon/lib/icon/IconAway';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconSortAscending height='2em' width='2em' /></td>
        <td>sortAscending</td>
        <td>
          import IconSortAscending from 'terra-icon/lib/icon/IconSortAscending';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconSortDescending height='2em' width='2em' /></td>
        <td>sortDescending</td>
        <td>
          import IconSortDescending from 'terra-icon/lib/icon/IconSortDescending';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconTreemap height='2em' width='2em' /></td>
        <td>treemap</td>
        <td>
          import IconTreemap from 'terra-icon/lib/icon/IconTreemap';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconGlasses height='2em' width='2em' /></td>
        <td>glasses</td>
        <td>
          import IconGlasses from 'terra-icon/lib/icon/IconGlasses';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconImage height='2em' width='2em' /></td>
        <td>image</td>
        <td>
          import IconImage from 'terra-icon/lib/icon/IconImage';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconDoorOpen height='2em' width='2em' /></td>
        <td>doorOpen</td>
        <td>
          import IconDoorOpen from 'terra-icon/lib/icon/IconDoorOpen';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconEllipses height='2em' width='2em' /></td>
        <td>ellipses</td>
        <td>
          import IconEllipses from 'terra-icon/lib/icon/IconEllipses';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconExclamation height='2em' width='2em' /></td>
        <td>exclamation</td>
        <td>
          import IconExclamation from 'terra-icon/lib/icon/IconExclamation';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconItalicI height='2em' width='2em' /></td>
        <td>italic-i</td>
        <td>
          import IconItalicI from 'terra-icon/lib/icon/IconItalicI';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconMinus height='2em' width='2em' /></td>
        <td>minus</td>
        <td>
          import IconMinus from 'terra-icon/lib/icon/IconMinus';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconClose height='2em' width='2em' /></td>
        <td>close</td>
        <td>
          import IconClose from 'terra-icon/lib/icon/IconClose';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconClear height='2em' width='2em' /></td>
        <td>clear</td>
        <td>
          import IconClear from 'terra-icon/lib/icon/IconClear';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconNotMet height='2em' width='2em' /></td>
        <td>notMet</td>
        <td>
          import IconNotMet from 'terra-icon/lib/icon/IconNotMet';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconIncomplete height='2em' width='2em' /></td>
        <td>incomplete</td>
        <td>
          import IconIncomplete from 'terra-icon/lib/icon/IconIncomplete';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconPerson height='2em' width='2em' /></td>
        <td>person</td>
        <td>
          import IconPerson from 'terra-icon/lib/icon/IconPerson';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconLeft height='2em' width='2em' /></td>
        <td>left</td>
        <td>
          import IconLeft from 'terra-icon/lib/icon/IconLeft';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconRight height='2em' width='2em' /></td>
        <td>right</td>
        <td>
          import IconRight from 'terra-icon/lib/icon/IconRight';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconUp height='2em' width='2em' /></td>
        <td>up</td>
        <td>
          import IconUp from 'terra-icon/lib/icon/IconUp';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconDown height='2em' width='2em' /></td>
        <td>down</td>
        <td>
          import IconDown from 'terra-icon/lib/icon/IconDown';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconSettings height='2em' width='2em' /></td>
        <td>settings</td>
        <td>
          import IconSettings from 'terra-icon/lib/icon/IconSettings';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconEdit height='2em' width='2em' /></td>
        <td>edit</td>
        <td>
          import IconEdit from 'terra-icon/lib/icon/IconEdit';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconCalendar height='2em' width='2em' /></td>
        <td>calendar</td>
        <td>
          import IconCalendar from 'terra-icon/lib/icon/IconCalendar';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconLookback height='2em' width='2em' /></td>
        <td>lookback</td>
        <td>
          import IconLookback from 'terra-icon/lib/icon/IconLookback';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconRefresh height='2em' width='2em' /></td>
        <td>refresh</td>
        <td>
          import IconRefresh from 'terra-icon/lib/icon/IconRefresh';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconProvider height='2em' width='2em' /></td>
        <td>provider</td>
        <td>
          import IconProvider from 'terra-icon/lib/icon/IconProvider';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconPadlock height='2em' width='2em' /></td>
        <td>padlock</td>
        <td>
          import IconPadlock from 'terra-icon/lib/icon/IconPadlock';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconFeatured height='2em' width='2em' /></td>
        <td>featured</td>
        <td>
          import IconFeatured from 'terra-icon/lib/icon/IconFeatured';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconFeaturedOutline height='2em' width='2em' /></td>
        <td>featuredOutline</td>
        <td>
          import IconFeaturedOutline from 'terra-icon/lib/icon/IconFeaturedOutline';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconArchive height='2em' width='2em' /></td>
        <td>archive</td>
        <td>
          import IconArchive from 'terra-icon/lib/icon/IconArchive';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconFunnel height='2em' width='2em' /></td>
        <td>funnel</td>
        <td>
          import IconFunnel from 'terra-icon/lib/icon/IconFunnel';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconDocuments height='2em' width='2em' /></td>
        <td>documents</td>
        <td>
          import IconDocuments from 'terra-icon/lib/icon/IconDocuments';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconUnknown height='2em' width='2em' /></td>
        <td>unknown</td>
        <td>
          import IconUnknown from 'terra-icon/lib/icon/IconUnknown';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconHouse height='2em' width='2em' /></td>
        <td>house</td>
        <td>
          import IconHouse from 'terra-icon/lib/icon/IconHouse';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconSave height='2em' width='2em' /></td>
        <td>save</td>
        <td>
          import IconSave from 'terra-icon/lib/icon/IconSave';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconHospital height='2em' width='2em' /></td>
        <td>hospital</td>
        <td>
          import IconHospital from 'terra-icon/lib/icon/IconHospital';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconPending height='2em' width='2em' /></td>
        <td>pending</td>
        <td>
          import IconPending from 'terra-icon/lib/icon/IconPending';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconAnalytics height='2em' width='2em' /></td>
        <td>analytics</td>
        <td>
          import IconAnalytics from 'terra-icon/lib/icon/IconAnalytics';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconAnnouncement height='2em' width='2em' /></td>
        <td>announcement</td>
        <td>
          import IconAnnouncement from 'terra-icon/lib/icon/IconAnnouncement';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconCamera height='2em' width='2em' /></td>
        <td>camera</td>
        <td>
          import IconCamera from 'terra-icon/lib/icon/IconCamera';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconBriefcase height='2em' width='2em' /></td>
        <td>briefcase</td>
        <td>
          import IconBriefcase from 'terra-icon/lib/icon/IconBriefcase';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconLink height='2em' width='2em' /></td>
        <td>link</td>
        <td>
          import IconLink from 'terra-icon/lib/icon/IconLink';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconList height='2em' width='2em' /></td>
        <td>list</td>
        <td>
          import IconList from 'terra-icon/lib/icon/IconList';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconMenu height='2em' width='2em' /></td>
        <td>menu</td>
        <td>
          import IconMenu from 'terra-icon/lib/icon/IconMenu';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconChecklist height='2em' width='2em' /></td>
        <td>checklist</td>
        <td>
          import IconChecklist from 'terra-icon/lib/icon/IconChecklist';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconUnlock height='2em' width='2em' /></td>
        <td>unlock</td>
        <td>
          import IconUnlock from 'terra-icon/lib/icon/IconUnlock';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconDue height='2em' width='2em' /></td>
        <td>due</td>
        <td>
          import IconDue from 'terra-icon/lib/icon/IconDue';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconSpinner height='2em' width='2em' /></td>
        <td>spinner</td>
        <td>
          import IconSpinner from 'terra-icon/lib/icon/IconSpinner';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconTile height='2em' width='2em' /></td>
        <td>tile</td>
        <td>
          import IconTile from 'terra-icon/lib/icon/IconTile';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconUsers height='2em' width='2em' /></td>
        <td>users</td>
        <td>
          import IconUsers from 'terra-icon/lib/icon/IconUsers';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconKnurling height='2em' width='2em' /></td>
        <td>knurling</td>
        <td>
          import IconKnurling from 'terra-icon/lib/icon/IconKnurling';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconAddPerson height='2em' width='2em' /></td>
        <td>addPerson</td>
        <td>
          import IconAddPerson from 'terra-icon/lib/icon/IconAddPerson';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconUpload height='2em' width='2em' /></td>
        <td>upload</td>
        <td>
          import IconUpload from 'terra-icon/lib/icon/IconUpload';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconDownload height='2em' width='2em' /></td>
        <td>download</td>
        <td>
          import IconDownload from 'terra-icon/lib/icon/IconDownload';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconCancel height='2em' width='2em' /></td>
        <td>cancel</td>
        <td>
          import IconCancel from 'terra-icon/lib/icon/IconCancel';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconMaximize height='2em' width='2em' /></td>
        <td>maximize</td>
        <td>
          import IconMaximize from 'terra-icon/lib/icon/IconMaximize';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconMinimize height='2em' width='2em' /></td>
        <td>minimize</td>
        <td>
          import IconMinimize from 'terra-icon/lib/icon/IconMinimize';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconReply height='2em' width='2em' /></td>
        <td>reply</td>
        <td>
          import IconReply from 'terra-icon/lib/icon/IconReply';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconTable height='2em' width='2em' /></td>
        <td>table</td>
        <td>
          import IconTable from 'terra-icon/lib/icon/IconTable';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconRequired height='2em' width='2em' /></td>
        <td>required</td>
        <td>
          import IconRequired from 'terra-icon/lib/icon/IconRequired';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconGapChecking height='2em' width='2em' /></td>
        <td>gap checking</td>
        <td>
          import IconGapChecking from 'terra-icon/lib/icon/IconGapChecking';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconPersonHospital height='2em' width='2em' /></td>
        <td>personHospital</td>
        <td>
          import IconPersonHospital from 'terra-icon/lib/icon/IconPersonHospital';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconPersonnelPerson height='2em' width='2em' /></td>
        <td>personnelPerson</td>
        <td>
          import IconPersonnelPerson from 'terra-icon/lib/icon/IconPersonnelPerson';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconLeftPane height='2em' width='2em' /></td>
        <td>leftPane</td>
        <td>
          import IconLeftPane from 'terra-icon/lib/icon/IconLeftPane';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconFlowsheet height='2em' width='2em' /></td>
        <td>flowsheet</td>
        <td>
          import IconFlowsheet from 'terra-icon/lib/icon/IconFlowsheet';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconNotification height='2em' width='2em' /></td>
        <td>notification</td>
        <td>
          import IconNotification from 'terra-icon/lib/icon/IconNotification';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconLast height='2em' width='2em' /></td>
        <td>last</td>
        <td>
          import IconLast from 'terra-icon/lib/icon/IconLast';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconDevice height='2em' width='2em' /></td>
        <td>device</td>
        <td>
          import IconDevice from 'terra-icon/lib/icon/IconDevice';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconPaperPencil height='2em' width='2em' /></td>
        <td>paperPencil</td>
        <td>
          import IconPaperPencil from 'terra-icon/lib/icon/IconPaperPencil';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconClipboard height='2em' width='2em' /></td>
        <td>clipboard</td>
        <td>
          import IconClipboard from 'terra-icon/lib/icon/IconClipboard';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconZoomOut height='2em' width='2em' /></td>
        <td>zoomOut</td>
        <td>
          import IconZoomOut from 'terra-icon/lib/icon/IconZoomOut';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconZoomIn height='2em' width='2em' /></td>
        <td>zoomIn</td>
        <td>
          import IconZoomIn from 'terra-icon/lib/icon/IconZoomIn';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconEnvelope height='2em' width='2em' /></td>
        <td>envelope</td>
        <td>
          import IconEnvelope from 'terra-icon/lib/icon/IconEnvelope';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconAllergy height='2em' width='2em' /></td>
        <td>allergy</td>
        <td>
          import IconAllergy from 'terra-icon/lib/icon/IconAllergy';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconPhone height='2em' width='2em' /></td>
        <td>phone</td>
        <td>
          import IconPhone from 'terra-icon/lib/icon/IconPhone';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconPanelLeft height='2em' width='2em' /></td>
        <td>panelLeft</td>
        <td>
          import IconPanelLeft from 'terra-icon/lib/icon/IconPanelLeft';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconPanelRight height='2em' width='2em' /></td>
        <td>panelRight</td>
        <td>
          import IconPanelRight from 'terra-icon/lib/icon/IconPanelRight';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconTag height='2em' width='2em' /></td>
        <td>tag</td>
        <td>
          import IconTag from 'terra-icon/lib/icon/IconTag';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconIPass height='2em' width='2em' /></td>
        <td>iPass</td>
        <td>
          import IconIPass from 'terra-icon/lib/icon/IconIPass';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconScratchPad height='2em' width='2em' /></td>
        <td>scratchPad</td>
        <td>
          import IconScratchPad from 'terra-icon/lib/icon/IconScratchPad';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconPharmacyReview height='2em' width='2em' /></td>
        <td>pharmacyReview</td>
        <td>
          import IconPharmacyReview from 'terra-icon/lib/icon/IconPharmacyReview';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconBusy height='2em' width='2em' /></td>
        <td>busy</td>
        <td>
          import IconBusy from 'terra-icon/lib/icon/IconBusy';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconUnavailable height='2em' width='2em' /></td>
        <td>unavailable</td>
        <td>
          import IconUnavailable from 'terra-icon/lib/icon/IconUnavailable';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconImplant height='2em' width='2em' /></td>
        <td>implant</td>
        <td>
          import IconImplant from 'terra-icon/lib/icon/IconImplant';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconProtocol height='2em' width='2em' /></td>
        <td>protocol</td>
        <td>
          import IconProtocol from 'terra-icon/lib/icon/IconProtocol';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconVideoCamera height='2em' width='2em' /></td>
        <td>videoCamera</td>
        <td>
          import IconVideoCamera from 'terra-icon/lib/icon/IconVideoCamera';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconNoSignal height='2em' width='2em' /></td>
        <td>noSignal</td>
        <td>
          import IconNoSignal from 'terra-icon/lib/icon/IconNoSignal';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconReload height='2em' width='2em' /></td>
        <td>reload</td>
        <td>
          import IconReload from 'terra-icon/lib/icon/IconReload';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconRecurringEvent height='2em' width='2em' /></td>
        <td>recurringEvent</td>
        <td>
          import IconRecurringEvent from 'terra-icon/lib/icon/IconRecurringEvent';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconSeparate height='2em' width='2em' /></td>
        <td>separate</td>
        <td>
          import IconSeparate from 'terra-icon/lib/icon/IconSeparate';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconMerge height='2em' width='2em' /></td>
        <td>merge</td>
        <td>
          import IconMerge from 'terra-icon/lib/icon/IconMerge';
        </td>
      </tr>
    </Table.Rows>
  </Table>
  </div>);

export default IconAll;
