// This file is autogenerated from scripts/src/generate-example 
import React from 'react';
import { IconAdd } from '../src/Icon.jsx';
import { IconSearch } from '../src/Icon.jsx';
import { IconCommit } from '../src/Icon.jsx';
import { IconCheckmark } from '../src/Icon.jsx';
import { IconSuccess } from '../src/Icon.jsx';
import { IconSuccessInverse } from '../src/Icon.jsx';
import { IconAvailable } from '../src/Icon.jsx';
import { IconComplete } from '../src/Icon.jsx';
import { IconTrash } from '../src/Icon.jsx';
import { IconPaperFolded } from '../src/Icon.jsx';
import { IconPrinter } from '../src/Icon.jsx';
import { IconComment } from '../src/Icon.jsx';
import { IconBookmark } from '../src/Icon.jsx';
import { IconModified } from '../src/Icon.jsx';
import { IconFirst } from '../src/Icon.jsx';
import { IconFolder } from '../src/Icon.jsx';
import { IconAttachment } from '../src/Icon.jsx';
import { IconSend } from '../src/Icon.jsx';
import { IconPill } from '../src/Icon.jsx';
import { IconCritical } from '../src/Icon.jsx';
import { IconVisualization } from '../src/Icon.jsx';
import { IconLightbulb } from '../src/Icon.jsx';
import { IconForward } from '../src/Icon.jsx';
import { IconProjects } from '../src/Icon.jsx';
import { IconReplyAll } from '../src/Icon.jsx';
import { IconFlag } from '../src/Icon.jsx';
import { IconCalculator } from '../src/Icon.jsx';
import { IconCaretRight } from '../src/Icon.jsx';
import { IconCaretLeft } from '../src/Icon.jsx';
import { IconCaretUp } from '../src/Icon.jsx';
import { IconCaretDown } from '../src/Icon.jsx';
import { IconScheduled } from '../src/Icon.jsx';
import { IconTrophy } from '../src/Icon.jsx';
import { IconChevronLeft } from '../src/Icon.jsx';
import { IconPrevious } from '../src/Icon.jsx';
import { IconChevronRight } from '../src/Icon.jsx';
import { IconNext } from '../src/Icon.jsx';
import { IconChevronUp } from '../src/Icon.jsx';
import { IconExpandLess } from '../src/Icon.jsx';
import { IconChevron } from '../src/Icon.jsx';
import { IconChevronDown } from '../src/Icon.jsx';
import { IconExpandMore } from '../src/Icon.jsx';
import { IconClock } from '../src/Icon.jsx';
import { IconAway } from '../src/Icon.jsx';
import { IconSortAscending } from '../src/Icon.jsx';
import { IconSortDescending } from '../src/Icon.jsx';
import { IconTreemap } from '../src/Icon.jsx';
import { IconGlasses } from '../src/Icon.jsx';
import { IconImage } from '../src/Icon.jsx';
import { IconDoorOpen } from '../src/Icon.jsx';
import { IconEllipses } from '../src/Icon.jsx';
import { IconExclamation } from '../src/Icon.jsx';
import { IconHighPriority } from '../src/Icon.jsx';
import { IconAlert } from '../src/Icon.jsx';
import { IconWarning } from '../src/Icon.jsx';
import { IconItalicI } from '../src/Icon.jsx';
import { IconInformation } from '../src/Icon.jsx';
import { IconInformationInverse } from '../src/Icon.jsx';
import { IconMinus } from '../src/Icon.jsx';
import { IconError } from '../src/Icon.jsx';
import { IconDoNotDisturb } from '../src/Icon.jsx';
import { IconClose } from '../src/Icon.jsx';
import { IconClear } from '../src/Icon.jsx';
import { IconNotMet } from '../src/Icon.jsx';
import { IconIncomplete } from '../src/Icon.jsx';
import { IconPerson } from '../src/Icon.jsx';
import { IconLeft } from '../src/Icon.jsx';
import { IconRight } from '../src/Icon.jsx';
import { IconUp } from '../src/Icon.jsx';
import { IconDown } from '../src/Icon.jsx';
import { IconSettings } from '../src/Icon.jsx';
import { IconEdit } from '../src/Icon.jsx';
import { IconCalendar } from '../src/Icon.jsx';
import { IconLookback } from '../src/Icon.jsx';
import { IconRefresh } from '../src/Icon.jsx';
import { IconProvider } from '../src/Icon.jsx';
import { IconPadlock } from '../src/Icon.jsx';
import { IconFeatured } from '../src/Icon.jsx';
import { IconArchive } from '../src/Icon.jsx';
import { IconFunnel } from '../src/Icon.jsx';
import { IconDocuments } from '../src/Icon.jsx';
import { IconHelp } from '../src/Icon.jsx';
import { IconHelpInverse } from '../src/Icon.jsx';
import { IconUnknown } from '../src/Icon.jsx';
import { IconHouse } from '../src/Icon.jsx';
import { IconSave } from '../src/Icon.jsx';
import { IconHospital } from '../src/Icon.jsx';
import { IconPending } from '../src/Icon.jsx';
import { IconAnalytics } from '../src/Icon.jsx';
import { IconAnnouncement } from '../src/Icon.jsx';
import { IconCamera } from '../src/Icon.jsx';
import { IconBriefcase } from '../src/Icon.jsx';
import { IconLink } from '../src/Icon.jsx';
import { IconList } from '../src/Icon.jsx';
import { IconMenu } from '../src/Icon.jsx';
import { IconChecklist } from '../src/Icon.jsx';
import { IconUnlock } from '../src/Icon.jsx';
import { IconDue } from '../src/Icon.jsx';
import { IconDueSoon } from '../src/Icon.jsx';
import { IconSpinner } from '../src/Icon.jsx';
import { IconTile } from '../src/Icon.jsx';
import { IconOverDue } from '../src/Icon.jsx';
import { IconUsers } from '../src/Icon.jsx';
import { IconKnurling } from '../src/Icon.jsx';
import { IconAddPerson } from '../src/Icon.jsx';
import { IconUpload } from '../src/Icon.jsx';
import { IconDownload } from '../src/Icon.jsx';
import { IconCancel } from '../src/Icon.jsx';
import { IconMaximize } from '../src/Icon.jsx';
import { IconMinimize } from '../src/Icon.jsx';
import { IconReply } from '../src/Icon.jsx';
import { IconTable } from '../src/Icon.jsx';
import { IconRequired } from '../src/Icon.jsx';
import { IconGapChecking } from '../src/Icon.jsx';
import { IconPersonHospital } from '../src/Icon.jsx';
import { IconPersonnelPerson } from '../src/Icon.jsx';
import { IconHigh } from '../src/Icon.jsx';
import { IconLow } from '../src/Icon.jsx';
import { IconMax } from '../src/Icon.jsx';
import { IconMin } from '../src/Icon.jsx';
import { IconAbnormal } from '../src/Icon.jsx';
import { IconLeftPane } from '../src/Icon.jsx';
import { IconFlowsheet } from '../src/Icon.jsx';
import { IconNotification } from '../src/Icon.jsx';
import { IconLast } from '../src/Icon.jsx';
import { IconDevice } from '../src/Icon.jsx';
import { IconDeviceCheck } from '../src/Icon.jsx';
import { IconDeviceAlert } from '../src/Icon.jsx';
import { IconPaperPencil } from '../src/Icon.jsx';
import { IconClipboard } from '../src/Icon.jsx';
import { IconZoomOut } from '../src/Icon.jsx';
import { IconZoomIn } from '../src/Icon.jsx';
import { IconDiamond } from '../src/Icon.jsx';
import { IconEnvelope } from '../src/Icon.jsx';
import { IconAllergy } from '../src/Icon.jsx';
import { IconPhone } from '../src/Icon.jsx';
import { IconPanelLeft } from '../src/Icon.jsx';
import { IconPanelRight } from '../src/Icon.jsx';
import { IconTag } from '../src/Icon.jsx';
import { IconIPass } from '../src/Icon.jsx';
import { IconScratchPad } from '../src/Icon.jsx';
import { IconPharmacyReview } from '../src/Icon.jsx';
import { IconPharmacyReject } from '../src/Icon.jsx';
import { IconBusy } from '../src/Icon.jsx';
import { IconUnavailable } from '../src/Icon.jsx';
import { IconImplant } from '../src/Icon.jsx';
const IconAll = () => (
<div>
  <div>
    <div>
      <IconAdd />
      add
    </div>
  </div>
  <div>
    <div>
      <IconSearch />
      search
    </div>
  </div>
  <div>
    <div>
      <IconCommit />
      commit
    </div>
  </div>
  <div>
    <div>
      <IconCheckmark />
      checkmark
    </div>
  </div>
  <div>
    <div>
      <IconSuccess />
      success
    </div>
  </div>
  <div>
    <div>
      <IconSuccessInverse />
      success_inverse
    </div>
  </div>
  <div>
    <div>
      <IconAvailable />
      available
    </div>
  </div>
  <div>
    <div>
      <IconComplete />
      complete
    </div>
  </div>
  <div>
    <div>
      <IconTrash />
      trash
    </div>
  </div>
  <div>
    <div>
      <IconPaperFolded />
      paperFolded
    </div>
  </div>
  <div>
    <div>
      <IconPrinter />
      printer
    </div>
  </div>
  <div>
    <div>
      <IconComment />
      comment
    </div>
  </div>
  <div>
    <div>
      <IconBookmark />
      bookmark
    </div>
  </div>
  <div>
    <div>
      <IconModified />
      modified
    </div>
  </div>
  <div>
    <div>
      <IconFirst />
      first
    </div>
  </div>
  <div>
    <div>
      <IconFolder />
      folder
    </div>
  </div>
  <div>
    <div>
      <IconAttachment />
      attachment
    </div>
  </div>
  <div>
    <div>
      <IconSend />
      send
    </div>
  </div>
  <div>
    <div>
      <IconPill />
      pill
    </div>
  </div>
  <div>
    <div>
      <IconCritical />
      critical
    </div>
  </div>
  <div>
    <div>
      <IconVisualization />
      visualization
    </div>
  </div>
  <div>
    <div>
      <IconLightbulb />
      lightbulb
    </div>
  </div>
  <div>
    <div>
      <IconForward />
      forward
    </div>
  </div>
  <div>
    <div>
      <IconProjects />
      projects
    </div>
  </div>
  <div>
    <div>
      <IconReplyAll />
      replyAll
    </div>
  </div>
  <div>
    <div>
      <IconFlag />
      flag
    </div>
  </div>
  <div>
    <div>
      <IconCalculator />
      calculator
    </div>
  </div>
  <div>
    <div>
      <IconCaretRight />
      caretRight
    </div>
  </div>
  <div>
    <div>
      <IconCaretLeft />
      caretLeft
    </div>
  </div>
  <div>
    <div>
      <IconCaretUp />
      caretUp
    </div>
  </div>
  <div>
    <div>
      <IconCaretDown />
      caretDown
    </div>
  </div>
  <div>
    <div>
      <IconScheduled />
      scheduled
    </div>
  </div>
  <div>
    <div>
      <IconTrophy />
      trophy
    </div>
  </div>
  <div>
    <div>
      <IconChevronLeft />
      chevronLeft
    </div>
  </div>
  <div>
    <div>
      <IconPrevious />
      previous
    </div>
  </div>
  <div>
    <div>
      <IconChevronRight />
      chevronRight
    </div>
  </div>
  <div>
    <div>
      <IconNext />
      next
    </div>
  </div>
  <div>
    <div>
      <IconChevronUp />
      chevronUp
    </div>
  </div>
  <div>
    <div>
      <IconExpandLess />
      expandLess
    </div>
  </div>
  <div>
    <div>
      <IconChevron />
      chevron
    </div>
  </div>
  <div>
    <div>
      <IconChevronDown />
      chevronDown
    </div>
  </div>
  <div>
    <div>
      <IconExpandMore />
      expandMore
    </div>
  </div>
  <div>
    <div>
      <IconClock />
      clock
    </div>
  </div>
  <div>
    <div>
      <IconAway />
      away
    </div>
  </div>
  <div>
    <div>
      <IconSortAscending />
      sortAscending
    </div>
  </div>
  <div>
    <div>
      <IconSortDescending />
      sortDescending
    </div>
  </div>
  <div>
    <div>
      <IconTreemap />
      treemap
    </div>
  </div>
  <div>
    <div>
      <IconGlasses />
      glasses
    </div>
  </div>
  <div>
    <div>
      <IconImage />
      image
    </div>
  </div>
  <div>
    <div>
      <IconDoorOpen />
      doorOpen
    </div>
  </div>
  <div>
    <div>
      <IconEllipses />
      ellipses
    </div>
  </div>
  <div>
    <div>
      <IconExclamation />
      exclamation
    </div>
  </div>
  <div>
    <div>
      <IconHighPriority />
      highPriority
    </div>
  </div>
  <div>
    <div>
      <IconAlert />
      alert
    </div>
  </div>
  <div>
    <div>
      <IconWarning />
      warning
    </div>
  </div>
  <div>
    <div>
      <IconItalicI />
      italic-i
    </div>
  </div>
  <div>
    <div>
      <IconInformation />
      information
    </div>
  </div>
  <div>
    <div>
      <IconInformationInverse />
      information_inverse
    </div>
  </div>
  <div>
    <div>
      <IconMinus />
      minus
    </div>
  </div>
  <div>
    <div>
      <IconError />
      error
    </div>
  </div>
  <div>
    <div>
      <IconDoNotDisturb />
      doNotDisturb
    </div>
  </div>
  <div>
    <div>
      <IconClose />
      close
    </div>
  </div>
  <div>
    <div>
      <IconClear />
      clear
    </div>
  </div>
  <div>
    <div>
      <IconNotMet />
      notMet
    </div>
  </div>
  <div>
    <div>
      <IconIncomplete />
      incomplete
    </div>
  </div>
  <div>
    <div>
      <IconPerson />
      person
    </div>
  </div>
  <div>
    <div>
      <IconLeft />
      left
    </div>
  </div>
  <div>
    <div>
      <IconRight />
      right
    </div>
  </div>
  <div>
    <div>
      <IconUp />
      up
    </div>
  </div>
  <div>
    <div>
      <IconDown />
      down
    </div>
  </div>
  <div>
    <div>
      <IconSettings />
      settings
    </div>
  </div>
  <div>
    <div>
      <IconEdit />
      edit
    </div>
  </div>
  <div>
    <div>
      <IconCalendar />
      calendar
    </div>
  </div>
  <div>
    <div>
      <IconLookback />
      lookback
    </div>
  </div>
  <div>
    <div>
      <IconRefresh />
      refresh
    </div>
  </div>
  <div>
    <div>
      <IconProvider />
      provider
    </div>
  </div>
  <div>
    <div>
      <IconPadlock />
      padlock
    </div>
  </div>
  <div>
    <div>
      <IconFeatured />
      featured
    </div>
  </div>
  <div>
    <div>
      <IconArchive />
      archive
    </div>
  </div>
  <div>
    <div>
      <IconFunnel />
      funnel
    </div>
  </div>
  <div>
    <div>
      <IconDocuments />
      documents
    </div>
  </div>
  <div>
    <div>
      <IconHelp />
      help
    </div>
  </div>
  <div>
    <div>
      <IconHelpInverse />
      help_inverse
    </div>
  </div>
  <div>
    <div>
      <IconUnknown />
      unknown
    </div>
  </div>
  <div>
    <div>
      <IconHouse />
      house
    </div>
  </div>
  <div>
    <div>
      <IconSave />
      save
    </div>
  </div>
  <div>
    <div>
      <IconHospital />
      hospital
    </div>
  </div>
  <div>
    <div>
      <IconPending />
      pending
    </div>
  </div>
  <div>
    <div>
      <IconAnalytics />
      analytics
    </div>
  </div>
  <div>
    <div>
      <IconAnnouncement />
      announcement
    </div>
  </div>
  <div>
    <div>
      <IconCamera />
      camera
    </div>
  </div>
  <div>
    <div>
      <IconBriefcase />
      briefcase
    </div>
  </div>
  <div>
    <div>
      <IconLink />
      link
    </div>
  </div>
  <div>
    <div>
      <IconList />
      list
    </div>
  </div>
  <div>
    <div>
      <IconMenu />
      menu
    </div>
  </div>
  <div>
    <div>
      <IconChecklist />
      checklist
    </div>
  </div>
  <div>
    <div>
      <IconUnlock />
      unlock
    </div>
  </div>
  <div>
    <div>
      <IconDue />
      due
    </div>
  </div>
  <div>
    <div>
      <IconDueSoon />
      dueSoon
    </div>
  </div>
  <div>
    <div>
      <IconSpinner />
      spinner
    </div>
  </div>
  <div>
    <div>
      <IconTile />
      tile
    </div>
  </div>
  <div>
    <div>
      <IconOverDue />
      overDue
    </div>
  </div>
  <div>
    <div>
      <IconUsers />
      users
    </div>
  </div>
  <div>
    <div>
      <IconKnurling />
      knurling
    </div>
  </div>
  <div>
    <div>
      <IconAddPerson />
      addPerson
    </div>
  </div>
  <div>
    <div>
      <IconUpload />
      upload
    </div>
  </div>
  <div>
    <div>
      <IconDownload />
      download
    </div>
  </div>
  <div>
    <div>
      <IconCancel />
      cancel
    </div>
  </div>
  <div>
    <div>
      <IconMaximize />
      maximize
    </div>
  </div>
  <div>
    <div>
      <IconMinimize />
      minimize
    </div>
  </div>
  <div>
    <div>
      <IconReply />
      reply
    </div>
  </div>
  <div>
    <div>
      <IconTable />
      table
    </div>
  </div>
  <div>
    <div>
      <IconRequired />
      required
    </div>
  </div>
  <div>
    <div>
      <IconGapChecking />
      gap checking
    </div>
  </div>
  <div>
    <div>
      <IconPersonHospital />
      personHospital
    </div>
  </div>
  <div>
    <div>
      <IconPersonnelPerson />
      personnelPerson
    </div>
  </div>
  <div>
    <div>
      <IconHigh />
      high
    </div>
  </div>
  <div>
    <div>
      <IconLow />
      low
    </div>
  </div>
  <div>
    <div>
      <IconMax />
      max
    </div>
  </div>
  <div>
    <div>
      <IconMin />
      min
    </div>
  </div>
  <div>
    <div>
      <IconAbnormal />
      abnormal
    </div>
  </div>
  <div>
    <div>
      <IconLeftPane />
      leftPane
    </div>
  </div>
  <div>
    <div>
      <IconFlowsheet />
      flowsheet
    </div>
  </div>
  <div>
    <div>
      <IconNotification />
      notification
    </div>
  </div>
  <div>
    <div>
      <IconLast />
      last
    </div>
  </div>
  <div>
    <div>
      <IconDevice />
      device
    </div>
  </div>
  <div>
    <div>
      <IconDeviceCheck />
      deviceCheck
    </div>
  </div>
  <div>
    <div>
      <IconDeviceAlert />
      deviceAlert
    </div>
  </div>
  <div>
    <div>
      <IconPaperPencil />
      paperPencil
    </div>
  </div>
  <div>
    <div>
      <IconClipboard />
      clipboard
    </div>
  </div>
  <div>
    <div>
      <IconZoomOut />
      zoomOut
    </div>
  </div>
  <div>
    <div>
      <IconZoomIn />
      zoomIn
    </div>
  </div>
  <div>
    <div>
      <IconDiamond />
      diamond
    </div>
  </div>
  <div>
    <div>
      <IconEnvelope />
      envelope
    </div>
  </div>
  <div>
    <div>
      <IconAllergy />
      allergy
    </div>
  </div>
  <div>
    <div>
      <IconPhone />
      phone
    </div>
  </div>
  <div>
    <div>
      <IconPanelLeft />
      panelLeft
    </div>
  </div>
  <div>
    <div>
      <IconPanelRight />
      panelRight
    </div>
  </div>
  <div>
    <div>
      <IconTag />
      tag
    </div>
  </div>
  <div>
    <div>
      <IconIPass />
      iPass
    </div>
  </div>
  <div>
    <div>
      <IconScratchPad />
      scratchPad
    </div>
  </div>
  <div>
    <div>
      <IconPharmacyReview />
      pharmacyReview
    </div>
  </div>
  <div>
    <div>
      <IconPharmacyReject />
      pharmacyReject
    </div>
  </div>
  <div>
    <div>
      <IconBusy />
      busy
    </div>
  </div>
  <div>
    <div>
      <IconUnavailable />
      unavailable
    </div>
  </div>
  <div>
    <div>
      <IconImplant />
      implant
    </div>
  </div>
</div>
);

export default IconAll;