// This file is autogenerated from scripts/src/generate-example 
import React from 'react';
import { IconAdd } from '../src/Icon.jsx';
import { IconSearch } from '../src/Icon.jsx';
import { IconCommit } from '../src/Icon.jsx';
import { IconCheckmark } from '../src/Icon.jsx';
import { IconSuccess } from '../src/Icon.jsx';
import { IconSuccessInverse } from '../src/Icon.jsx';
import { IconAvailable } from '../src/Icon.jsx';
import { IconComplete } from '../src/Icon.jsx';
import { IconTrash } from '../src/Icon.jsx';
import { IconPaperFolded } from '../src/Icon.jsx';
import { IconPrinter } from '../src/Icon.jsx';
import { IconComment } from '../src/Icon.jsx';
import { IconBookmark } from '../src/Icon.jsx';
import { IconModified } from '../src/Icon.jsx';
import { IconFirst } from '../src/Icon.jsx';
import { IconFolder } from '../src/Icon.jsx';
import { IconAttachment } from '../src/Icon.jsx';
import { IconSend } from '../src/Icon.jsx';
import { IconPill } from '../src/Icon.jsx';
import { IconCritical } from '../src/Icon.jsx';
import { IconVisualization } from '../src/Icon.jsx';
import { IconLightbulb } from '../src/Icon.jsx';
import { IconForward } from '../src/Icon.jsx';
import { IconProjects } from '../src/Icon.jsx';
import { IconReplyAll } from '../src/Icon.jsx';
import { IconFlag } from '../src/Icon.jsx';
import { IconCalculator } from '../src/Icon.jsx';
import { IconCaretRight } from '../src/Icon.jsx';
import { IconCaretLeft } from '../src/Icon.jsx';
import { IconCaretUp } from '../src/Icon.jsx';
import { IconCaretDown } from '../src/Icon.jsx';
import { IconScheduled } from '../src/Icon.jsx';
import { IconTrophy } from '../src/Icon.jsx';
import { IconChevronLeft } from '../src/Icon.jsx';
import { IconPrevious } from '../src/Icon.jsx';
import { IconChevronRight } from '../src/Icon.jsx';
import { IconNext } from '../src/Icon.jsx';
import { IconChevronUp } from '../src/Icon.jsx';
import { IconExpandLess } from '../src/Icon.jsx';
import { IconChevron } from '../src/Icon.jsx';
import { IconChevronDown } from '../src/Icon.jsx';
import { IconExpandMore } from '../src/Icon.jsx';
import { IconClock } from '../src/Icon.jsx';
import { IconAway } from '../src/Icon.jsx';
import { IconSortAscending } from '../src/Icon.jsx';
import { IconSortDescending } from '../src/Icon.jsx';
import { IconTreemap } from '../src/Icon.jsx';
import { IconGlasses } from '../src/Icon.jsx';
import { IconImage } from '../src/Icon.jsx';
import { IconDoorOpen } from '../src/Icon.jsx';
import { IconEllipses } from '../src/Icon.jsx';
import { IconExclamation } from '../src/Icon.jsx';
import { IconHighPriority } from '../src/Icon.jsx';
import { IconAlert } from '../src/Icon.jsx';
import { IconWarning } from '../src/Icon.jsx';
import { IconItalicI } from '../src/Icon.jsx';
import { IconInformation } from '../src/Icon.jsx';
import { IconInformationInverse } from '../src/Icon.jsx';
import { IconMinus } from '../src/Icon.jsx';
import { IconError } from '../src/Icon.jsx';
import { IconDoNotDisturb } from '../src/Icon.jsx';
import { IconClose } from '../src/Icon.jsx';
import { IconClear } from '../src/Icon.jsx';
import { IconNotMet } from '../src/Icon.jsx';
import { IconIncomplete } from '../src/Icon.jsx';
import { IconPerson } from '../src/Icon.jsx';
import { IconLeft } from '../src/Icon.jsx';
import { IconRight } from '../src/Icon.jsx';
import { IconUp } from '../src/Icon.jsx';
import { IconDown } from '../src/Icon.jsx';
import { IconSettings } from '../src/Icon.jsx';
import { IconEdit } from '../src/Icon.jsx';
import { IconCalendar } from '../src/Icon.jsx';
import { IconLookback } from '../src/Icon.jsx';
import { IconRefresh } from '../src/Icon.jsx';
import { IconProvider } from '../src/Icon.jsx';
import { IconPadlock } from '../src/Icon.jsx';
import { IconFeatured } from '../src/Icon.jsx';
import { IconArchive } from '../src/Icon.jsx';
import { IconFunnel } from '../src/Icon.jsx';
import { IconDocuments } from '../src/Icon.jsx';
import { IconHelp } from '../src/Icon.jsx';
import { IconHelpInverse } from '../src/Icon.jsx';
import { IconUnknown } from '../src/Icon.jsx';
import { IconHouse } from '../src/Icon.jsx';
import { IconSave } from '../src/Icon.jsx';
import { IconHospital } from '../src/Icon.jsx';
import { IconPending } from '../src/Icon.jsx';
import { IconAnalytics } from '../src/Icon.jsx';
import { IconAnnouncement } from '../src/Icon.jsx';
import { IconCamera } from '../src/Icon.jsx';
import { IconBriefcase } from '../src/Icon.jsx';
import { IconLink } from '../src/Icon.jsx';
import { IconList } from '../src/Icon.jsx';
import { IconMenu } from '../src/Icon.jsx';
import { IconChecklist } from '../src/Icon.jsx';
import { IconUnlock } from '../src/Icon.jsx';
import { IconDue } from '../src/Icon.jsx';
import { IconDueSoon } from '../src/Icon.jsx';
import { IconSpinner } from '../src/Icon.jsx';
import { IconTile } from '../src/Icon.jsx';
import { IconOverDue } from '../src/Icon.jsx';
import { IconUsers } from '../src/Icon.jsx';
import { IconKnurling } from '../src/Icon.jsx';
import { IconAddPerson } from '../src/Icon.jsx';
import { IconUpload } from '../src/Icon.jsx';
import { IconDownload } from '../src/Icon.jsx';
import { IconCancel } from '../src/Icon.jsx';
import { IconMaximize } from '../src/Icon.jsx';
import { IconMinimize } from '../src/Icon.jsx';
import { IconReply } from '../src/Icon.jsx';
import { IconTable } from '../src/Icon.jsx';
import { IconRequired } from '../src/Icon.jsx';
import { IconGapChecking } from '../src/Icon.jsx';
import { IconPersonHospital } from '../src/Icon.jsx';
import { IconPersonnelPerson } from '../src/Icon.jsx';
import { IconHigh } from '../src/Icon.jsx';
import { IconLow } from '../src/Icon.jsx';
import { IconMax } from '../src/Icon.jsx';
import { IconMin } from '../src/Icon.jsx';
import { IconAbnormal } from '../src/Icon.jsx';
import { IconLeftPane } from '../src/Icon.jsx';
import { IconFlowsheet } from '../src/Icon.jsx';
import { IconNotification } from '../src/Icon.jsx';
import { IconLast } from '../src/Icon.jsx';
import { IconDevice } from '../src/Icon.jsx';
import { IconDeviceCheck } from '../src/Icon.jsx';
import { IconDeviceAlert } from '../src/Icon.jsx';
import { IconPaperPencil } from '../src/Icon.jsx';
import { IconClipboard } from '../src/Icon.jsx';
import { IconZoomOut } from '../src/Icon.jsx';
import { IconZoomIn } from '../src/Icon.jsx';
import { IconDiamond } from '../src/Icon.jsx';
import { IconEnvelope } from '../src/Icon.jsx';
import { IconAllergy } from '../src/Icon.jsx';
import { IconPhone } from '../src/Icon.jsx';
import { IconPanelLeft } from '../src/Icon.jsx';
import { IconPanelRight } from '../src/Icon.jsx';
import { IconTag } from '../src/Icon.jsx';
import { IconIPass } from '../src/Icon.jsx';
import { IconScratchPad } from '../src/Icon.jsx';
import { IconPharmacyReview } from '../src/Icon.jsx';
import { IconPharmacyReject } from '../src/Icon.jsx';
import { IconBusy } from '../src/Icon.jsx';
import { IconUnavailable } from '../src/Icon.jsx';
import { IconImplant } from '../src/Icon.jsx';
const IconAll = () => (
<div>
  <div>
    <IconAdd />
    add
  </div>
  <div>
    <IconSearch />
    search
  </div>
  <div>
    <IconCommit />
    commit
  </div>
  <div>
    <IconCheckmark />
    checkmark
  </div>
  <div>
    <IconSuccess />
    success
  </div>
  <div>
    <IconSuccessInverse />
    success_inverse
  </div>
  <div>
    <IconAvailable />
    available
  </div>
  <div>
    <IconComplete />
    complete
  </div>
  <div>
    <IconTrash />
    trash
  </div>
  <div>
    <IconPaperFolded />
    paperFolded
  </div>
  <div>
    <IconPrinter />
    printer
  </div>
  <div>
    <IconComment />
    comment
  </div>
  <div>
    <IconBookmark />
    bookmark
  </div>
  <div>
    <IconModified />
    modified
  </div>
  <div>
    <IconFirst />
    first
  </div>
  <div>
    <IconFolder />
    folder
  </div>
  <div>
    <IconAttachment />
    attachment
  </div>
  <div>
    <IconSend />
    send
  </div>
  <div>
    <IconPill />
    pill
  </div>
  <div>
    <IconCritical />
    critical
  </div>
  <div>
    <IconVisualization />
    visualization
  </div>
  <div>
    <IconLightbulb />
    lightbulb
  </div>
  <div>
    <IconForward />
    forward
  </div>
  <div>
    <IconProjects />
    projects
  </div>
  <div>
    <IconReplyAll />
    replyAll
  </div>
  <div>
    <IconFlag />
    flag
  </div>
  <div>
    <IconCalculator />
    calculator
  </div>
  <div>
    <IconCaretRight />
    caretRight
  </div>
  <div>
    <IconCaretLeft />
    caretLeft
  </div>
  <div>
    <IconCaretUp />
    caretUp
  </div>
  <div>
    <IconCaretDown />
    caretDown
  </div>
  <div>
    <IconScheduled />
    scheduled
  </div>
  <div>
    <IconTrophy />
    trophy
  </div>
  <div>
    <IconChevronLeft />
    chevronLeft
  </div>
  <div>
    <IconPrevious />
    previous
  </div>
  <div>
    <IconChevronRight />
    chevronRight
  </div>
  <div>
    <IconNext />
    next
  </div>
  <div>
    <IconChevronUp />
    chevronUp
  </div>
  <div>
    <IconExpandLess />
    expandLess
  </div>
  <div>
    <IconChevron />
    chevron
  </div>
  <div>
    <IconChevronDown />
    chevronDown
  </div>
  <div>
    <IconExpandMore />
    expandMore
  </div>
  <div>
    <IconClock />
    clock
  </div>
  <div>
    <IconAway />
    away
  </div>
  <div>
    <IconSortAscending />
    sortAscending
  </div>
  <div>
    <IconSortDescending />
    sortDescending
  </div>
  <div>
    <IconTreemap />
    treemap
  </div>
  <div>
    <IconGlasses />
    glasses
  </div>
  <div>
    <IconImage />
    image
  </div>
  <div>
    <IconDoorOpen />
    doorOpen
  </div>
  <div>
    <IconEllipses />
    ellipses
  </div>
  <div>
    <IconExclamation />
    exclamation
  </div>
  <div>
    <IconHighPriority />
    highPriority
  </div>
  <div>
    <IconAlert />
    alert
  </div>
  <div>
    <IconWarning />
    warning
  </div>
  <div>
    <IconItalicI />
    italic-i
  </div>
  <div>
    <IconInformation />
    information
  </div>
  <div>
    <IconInformationInverse />
    information_inverse
  </div>
  <div>
    <IconMinus />
    minus
  </div>
  <div>
    <IconError />
    error
  </div>
  <div>
    <IconDoNotDisturb />
    doNotDisturb
  </div>
  <div>
    <IconClose />
    close
  </div>
  <div>
    <IconClear />
    clear
  </div>
  <div>
    <IconNotMet />
    notMet
  </div>
  <div>
    <IconIncomplete />
    incomplete
  </div>
  <div>
    <IconPerson />
    person
  </div>
  <div>
    <IconLeft />
    left
  </div>
  <div>
    <IconRight />
    right
  </div>
  <div>
    <IconUp />
    up
  </div>
  <div>
    <IconDown />
    down
  </div>
  <div>
    <IconSettings />
    settings
  </div>
  <div>
    <IconEdit />
    edit
  </div>
  <div>
    <IconCalendar />
    calendar
  </div>
  <div>
    <IconLookback />
    lookback
  </div>
  <div>
    <IconRefresh />
    refresh
  </div>
  <div>
    <IconProvider />
    provider
  </div>
  <div>
    <IconPadlock />
    padlock
  </div>
  <div>
    <IconFeatured />
    featured
  </div>
  <div>
    <IconArchive />
    archive
  </div>
  <div>
    <IconFunnel />
    funnel
  </div>
  <div>
    <IconDocuments />
    documents
  </div>
  <div>
    <IconHelp />
    help
  </div>
  <div>
    <IconHelpInverse />
    help_inverse
  </div>
  <div>
    <IconUnknown />
    unknown
  </div>
  <div>
    <IconHouse />
    house
  </div>
  <div>
    <IconSave />
    save
  </div>
  <div>
    <IconHospital />
    hospital
  </div>
  <div>
    <IconPending />
    pending
  </div>
  <div>
    <IconAnalytics />
    analytics
  </div>
  <div>
    <IconAnnouncement />
    announcement
  </div>
  <div>
    <IconCamera />
    camera
  </div>
  <div>
    <IconBriefcase />
    briefcase
  </div>
  <div>
    <IconLink />
    link
  </div>
  <div>
    <IconList />
    list
  </div>
  <div>
    <IconMenu />
    menu
  </div>
  <div>
    <IconChecklist />
    checklist
  </div>
  <div>
    <IconUnlock />
    unlock
  </div>
  <div>
    <IconDue />
    due
  </div>
  <div>
    <IconDueSoon />
    dueSoon
  </div>
  <div>
    <IconSpinner />
    spinner
  </div>
  <div>
    <IconTile />
    tile
  </div>
  <div>
    <IconOverDue />
    overDue
  </div>
  <div>
    <IconUsers />
    users
  </div>
  <div>
    <IconKnurling />
    knurling
  </div>
  <div>
    <IconAddPerson />
    addPerson
  </div>
  <div>
    <IconUpload />
    upload
  </div>
  <div>
    <IconDownload />
    download
  </div>
  <div>
    <IconCancel />
    cancel
  </div>
  <div>
    <IconMaximize />
    maximize
  </div>
  <div>
    <IconMinimize />
    minimize
  </div>
  <div>
    <IconReply />
    reply
  </div>
  <div>
    <IconTable />
    table
  </div>
  <div>
    <IconRequired />
    required
  </div>
  <div>
    <IconGapChecking />
    gap checking
  </div>
  <div>
    <IconPersonHospital />
    personHospital
  </div>
  <div>
    <IconPersonnelPerson />
    personnelPerson
  </div>
  <div>
    <IconHigh />
    high
  </div>
  <div>
    <IconLow />
    low
  </div>
  <div>
    <IconMax />
    max
  </div>
  <div>
    <IconMin />
    min
  </div>
  <div>
    <IconAbnormal />
    abnormal
  </div>
  <div>
    <IconLeftPane />
    leftPane
  </div>
  <div>
    <IconFlowsheet />
    flowsheet
  </div>
  <div>
    <IconNotification />
    notification
  </div>
  <div>
    <IconLast />
    last
  </div>
  <div>
    <IconDevice />
    device
  </div>
  <div>
    <IconDeviceCheck />
    deviceCheck
  </div>
  <div>
    <IconDeviceAlert />
    deviceAlert
  </div>
  <div>
    <IconPaperPencil />
    paperPencil
  </div>
  <div>
    <IconClipboard />
    clipboard
  </div>
  <div>
    <IconZoomOut />
    zoomOut
  </div>
  <div>
    <IconZoomIn />
    zoomIn
  </div>
  <div>
    <IconDiamond />
    diamond
  </div>
  <div>
    <IconEnvelope />
    envelope
  </div>
  <div>
    <IconAllergy />
    allergy
  </div>
  <div>
    <IconPhone />
    phone
  </div>
  <div>
    <IconPanelLeft />
    panelLeft
  </div>
  <div>
    <IconPanelRight />
    panelRight
  </div>
  <div>
    <IconTag />
    tag
  </div>
  <div>
    <IconIPass />
    iPass
  </div>
  <div>
    <IconScratchPad />
    scratchPad
  </div>
  <div>
    <IconPharmacyReview />
    pharmacyReview
  </div>
  <div>
    <IconPharmacyReject />
    pharmacyReject
  </div>
  <div>
    <IconBusy />
    busy
  </div>
  <div>
    <IconUnavailable />
    unavailable
  </div>
  <div>
    <IconImplant />
    implant
  </div>
</div>
);

export default IconAll;