language: node_js
sudo: required
jdk: oraclejdk8
before_script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
script:
  - yarn test
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
    