language: node_js
jdk: oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
script:
  - yarn test
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
    